import { generateAdTags } from "config/ads.config";

const dfpIds = {
  home: () => {
    return {
      header_ATF_728: `NW18_HIND_Desktop/NW18_HIND_Home/NW18_HIND_Home_Home/NW18_HIND_ROS_HP_ATF_728`,
      ATF_728_id:
        "NW18_HIND_Desktop/NW18_HIND_Home/NW18_HIND_Home_Home/NW18_HIND_HP_ATF_728",
      ATF_300_id:
        "NW18_HIND_Desktop/NW18_HIND_Home/NW18_HIND_Home_Home/NW18_HIND_HP_ATF_300",
      BTF_300_id:
        "NW18_HIND_Desktop/NW18_HIND_Home/NW18_HIND_Home_Home/NW18_HIND_HP_BTF_300",
      MTF_300_id:
        "NW18_HIND_Desktop/NW18_HIND_Home/NW18_HIND_Home_Home/NW18_HIND_HP_MTF_300",
      MTF_728_id:
        "NW18_HIND_Desktop/NW18_HIND_Home/NW18_HIND_Home_Home/NW18_HIND_HP_MTF_728",
      BTF_728_id:
        "NW18_HIND_Desktop/NW18_HIND_Home/NW18_HIND_Home_Home/NW18_HIND_HP_BTF_728",
      NATIVE_id:
        "NW18_HIND_Desktop/NW18_HIND_Home/NW18_HIND_Home_Home/NW18_HIND_HP_NAT1",
      Shosh_OOP_id:
        "NW18_HIND_Desktop/NW18_HIND_Home/NW18_HIND_Home_Home/NW18_HIND_HP_Shosh_OOP",
      Skin_OOP_id:
        "NW18_HIND_Desktop/NW18_HIND_Home/NW18_HIND_Home_Home/NW18_HIND_HP_Skin_OOP",
      PG_1x1:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AS/NW18_HIND_ROS_AS_PG_1x1",
      PG_Slider_1x1:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AS/NW18_HIND_ROS_AS_PG_Slider_1x1",
      ATF_SLUG_300_id:
        "NW18_HIND_Desktop/NW18_HIND_Home/NW18_HIND_Home_Home/NW18_HIND_HP_ATF_SLUG_300",
      MTF_SLUG_300_id:
        "NW18_HIND_Desktop/NW18_HIND_Home/NW18_HIND_Home_Home/NW18_HIND_HP_MTF_SLUG_300",
      PG_1x1_2:
        "NW18_HIND_Desktop/NW18_HIND_Home/NW18_HIND_Home_Home/NW18_HIND_HP_PG_1x1_2",
      PG_1x1_3:
        "NW18_HIND_Desktop/NW18_HIND_Home/NW18_HIND_Home_Home/NW18_HIND_HP_PG_1x1_3",
    };
  },

  T20WcAds: () => {
    return {
      ATF_728_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_SCHEDULE_AL/CRINXT_HIND_IPLT20_SCHDL_AL_ROS_ATF_728",
      ATF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_SCHEDULE_AL/CRINXT_HIND_IPLT20_SCHDL_AL_ROS_ATF_300",
      MTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_SCHEDULE_AL/CRINXT_HIND_IPLT20_SCHDL_AL_ROS_MTF_300",
      BTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_SCHEDULE_AL/CRINXT_HIND_IPLT20_SCHDL_AL_ROS_BTF_300",
      Shosh_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_AL/CRINXT_HIND_ROS_AL_ROS_Shosh_OOP",
      Skin_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_Skin_OOP",
      PG_1x1: `CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AS/CRINXT_HIND_ROS_AS_ROS_PG_1x1`,
      PG_Slider_1x1:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_Slider_1x1",
      ScoreCard_ad:
        "NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_CRICKET_AS/NW18_HIND_KHEL_CRI_AS_ROS_SCORE_1244",
    };
  },

  T20WcResultAds: () => {
    return {
      ATF_728_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_RESULT_AL/CRINXT_HIND_IPLT20_RSLT_AL_ROS_ATF_728",
      ATF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_RESULT_AL/CRINXT_HIND_IPLT20_RSLT_AL_ROS_ATF_300",
      MTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_RESULT_AL/CRINXT_HIND_IPLT20_RSLT_AL_ROS_MTF_300",
      BTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_RESULT_AL/CRINXT_HIND_IPLT20_RSLT_AL_ROS_BTF_300",
      Shosh_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_AL/CRINXT_HIND_ROS_AL_ROS_Shosh_OOP",
      Skin_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_Skin_OOP",
      PG_1x1: `CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AS/CRINXT_HIND_ROS_AS_ROS_PG_1x1`,
      PG_Slider_1x1:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_Slider_1x1",
      ScoreCard_ad:
        "NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_CRICKET_AS/NW18_HIND_KHEL_CRI_AS_ROS_SCORE_1244",
    };
  },

  T20WcNewsAds: () => {
    return {
      ATF_728_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_NEWS_AL/CRINXT_HIND_IPLT20_NWS_AL_ROS_ATF_728",
      ATF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_NEWS_AL/CRINXT_HIND_IPLT20_NWS_AL_ROS_ATF_300",
      MTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_NEWS_AL/CRINXT_HIND_IPLT20_NWS_AL_ROS_MTF_300",
      BTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_NEWS_AL/CRINXT_HIND_IPLT20_NWS_AL_ROS_BTF_300",
      Shosh_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_AL/CRINXT_HIND_ROS_AL_ROS_Shosh_OOP",
      Skin_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_Skin_OOP",
      PG_1x1: `CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AS/CRINXT_HIND_ROS_AS_ROS_PG_1x1`,
      PG_Slider_1x1:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_Slider_1x1",
      ScoreCard_ad:
        "NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_CRICKET_AS/NW18_HIND_KHEL_CRI_AS_ROS_SCORE_1244",
    };
  },

  T20WcPhotoAds: () => {
    return {
      ATF_728_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_PHOTO_AL/CRINXT_HIND_IPLT20_PHT_AL_ROS_ATF_728",
      ATF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_PHOTO_AL/CRINXT_HIND_IPLT20_PHT_AL_ROS_ATF_300",
      MTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_PHOTO_AL/CRINXT_HIND_IPLT20_PHT_AL_ROS_MTF_300",
      BTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_PHOTO_AL/CRINXT_HIND_IPLT20_PHT_AL_ROS_BTF_300",
      Shosh_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_AL/CRINXT_HIND_ROS_AL_ROS_Shosh_OOP",
      Skin_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_Skin_OOP",
      PG_1x1: `CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AS/CRINXT_HIND_ROS_AS_ROS_PG_1x1`,
      PG_Slider_1x1:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_Slider_1x1",
      ScoreCard_ad:
        "NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_CRICKET_AS/NW18_HIND_KHEL_CRI_AS_ROS_SCORE_1244",
    };
  },

  T20WcMostWicketsAndRuns: () => {
    return {
      ATF_728_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_ATF_728",
      ATF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_ATF_300",
      MTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_MTF_300",
      BTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_BTF_300",
      Shosh_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_Shosh_OOP",
      Skin_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_Skin_OOP",
      PG_1x1: `CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AS/CRINXT_HIND_ROS_AS_ROS_PG_1x1`,
      PG_Slider_1x1:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_Slider_1x1",
      ScoreCard_ad:
        "NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_CRICKET_AS/NW18_HIND_KHEL_CRI_AS_ROS_SCORE_1244",
    };
  },

  T20WcHomeAds: () => {
    return {
      ATF_728_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_AL/CRINXT_HIND_IPLT20_AL_ROS_ATF_728",
      ATF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_AL/CRINXT_HIND_IPLT20_AL_ROS_ATF_300",
      MTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_AL/CRINXT_HIND_IPLT20_AL_ROS_MTF_300",
      BTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_AL/CRINXT_HIND_IPLT20_AL_ROS_BTF_300",
      Shosh_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_AL/CRINXT_HIND_ROS_AL_ROS_Shosh_OOP",
      Skin_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_AL/CRINXT_HIND_ROS_AL_ROS_Skin_OOP",
      PG_1x1: `CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AS/CRINXT_HIND_ROS_AS_ROS_PG_1x1`,
      PG_Slider_1x1:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_Slider_1x1",
      ScoreCard_ad:
        "NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_CRICKET_AS/NW18_HIND_KHEL_CRI_AS_ROS_SCORE_1244",
    };
  },
  silo: (listing = "AL") => {
    return {
      rhs_ATF_300: `NW18_HIND_Desktop/NW18_HIND_INFORMATIONS/NW18_HIND_INFORMATIONS_${listing}/NW18_HIND_INFMTNS_${listing}_ROS_ATF_300`,
      rhs_BTF_300: `NW18_HIND_Desktop/NW18_HIND_INFORMATIONS/NW18_HIND_INFORMATION_${listing}/NW18_HIND_INFMTNS_${listing}_ROS_BTF_300`,
      ATF_728_id: `NW18_HIND_Desktop/NW18_HIND_INFORMATIONS/NW18_HIND_INFORMATION_${listing}/NW18_HIND_INFMTNS_${listing}_ROS_ATF_728`,
      BTF_728: `NW18_HIND_Desktop/NW18_HIND_INFORMATIONS/NW18_HIND_INFORMATION_${listing}/NW18_HIND_INFMTNS_${listing}_ROS_BTF_728`,
      Shosh_OOP_id: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${listing}/NW18_HIND_ROS_${listing}_Shosh_OOP`,
      Skin_OOP_id: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${listing}/NW18_HIND_ROS_${listing}_ROS_Skin_OOP`,
      PG_1x1: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${listing}/NW18_HIND_ROS_${listing}_ROS_PG_1x1`,
      ATF_300_id: `NW18_HIND_Desktop/NW18_HIND_INFORMATIONS/NW18_HIND_INFORMATION_${listing}/NW18_HIND_INFMTNS_${listing}_ROS_ATF_300`,
      BTF_300_id: `NW18_HIND_Desktop/NW18_HIND_INFORMATIONS/NW18_HIND_INFORMATION_${listing}/NW18_HIND_INFMTNS_${listing}_ROS_BTF_300`,
    };
  },
  tag: () => {
    return {
      ATF_728_id:
        "NW18_HIND_Desktop/NW18_HIND_TOPIC/NW18_HIND_TOPIC_AL/NW18_HIND_TOPIC_AL_ROS_ATF_728",
      ATF_300_id:
        "NW18_HIND_Desktop/NW18_HIND_TOPIC/NW18_HIND_TOPIC_AL/NW18_HIND_TOPIC_AL_ROS_ATF_300",
      BTF_300_id:
        "NW18_HIND_Desktop/NW18_HIND_TOPIC/NW18_HIND_TOPIC_AL/NW18_HIND_TOPIC_AL_ROS_BTF_300",
      // "header" : "NW18_HIND_Desktop/NW18_HIND_TOPIC/NW18_HIND_TOPIC_AL/NW18_HIND_TOPIC_AL_ROS_ATF_728",
      // "sidebarTop" : "NW18_HIND_Desktop/NW18_HIND_TOPIC/NW18_HIND_TOPIC_AL/NW18_HIND_TOPIC_AL_ROS_ATF_300",
      // "sidebarMiddle" : "NW18_HIND_Desktop/NW18_HIND_TOPIC/NW18_HIND_TOPIC_AL/NW18_HIND_TOPIC_AL_ROS_BTF_300",
      // "sidebarBottom" : "",
      // "pageMiddle" : "",
      // "pageFooter" : ""
    };
  },
  category: (urlParam, isPhoto = false) => {
    const states = {
      "delhi-ncr": "दिल्ली-एनसीआर",
      "uttar-pradesh": "उत्तर प्रदेश",
      bihar: "बिहार",
      "madhya-pradesh": "मध्य प्रदेश",
      rajasthan: "राजस्थान",
      uttarakhand: "उत्तराखंड",
      haryana: "हरियाणा",
      jharkhand: "झारखंड",
      chhattisgarh: "छत्तीसगढ़",
      "himachal-pradesh": "हिमाचल प्रदेश",
      maharashtra: "महाराष्ट्र",
      punjab: "पंजाब",
    };
    const all_states = (state, key) => {
      if (state !== "") {
        return states[state];
      } else {
        if (key === "") {
          return states;
        } else {
          return Object.keys(states);
        }
      }
    };
    let _tf = urlParam.t || "";
    _tf = _tf.replace("-", "_");
    _tf = isPhoto ? "photogallery" : _tf;
    let _section = urlParam.section || "";
    _section = _section.replace("-", "_");
    let _subsection = urlParam.subsection || "";
    _subsection = _subsection.replace("-", "_");
    let allStates = {};
    allStates = all_states("", "key"); //Newly Added for states
    if (allStates.indexOf(urlParam.section) >= 0) {
      return _subsection
        ? generateAdTags("listing", _subsection, isPhoto)
        : _section
        ? generateAdTags("listing", _section, isPhoto)
        : generateAdTags("listing", _tf, isPhoto);
    } else {
      return _subsection
        ? generateAdTags("listing", _subsection, isPhoto)
        : _section
        ? generateAdTags("listing", _section, isPhoto)
        : generateAdTags("listing", _tf, isPhoto);
    }
  },
  states: (urlParam) => {
    let _tf = urlParam.t || "";
    _tf = _tf.replace("-", "_");
    let _section = urlParam.section || "";
    _section = _section.replace("-", "_");
    const isPhoto = false;
    return _section
      ? generateAdTags("listing", _section, isPhoto)
      : generateAdTags("listing", _tf, isPhoto);
  },
  videos: () => {
    const isPhoto = false;
    return generateAdTags("listing", "videos", isPhoto);
  },
  article: (cat, isPhoto, subCat, isDistrict = false) => {
    return generateAdTags("article", cat, isPhoto, subCat, isDistrict);
  },
  district: () => {
    return {
      rhs_ATF_300: `NW18_HIND_Desktop/NW18_HIND_NEWS_DISTRICT/NW18_HIND_NEWS_DISTRICT_AL/NW18_HIND_NWS_DIST_AL_ROS_ATF_300`,
      rhs_BTF_300: `NW18_HIND_Desktop/NW18_HIND_NEWS_DISTRICT/NW18_HIND_NEWS_DISTRICT_AL/NW18_HIND_NWS_DIST_AL_ROS_BTF_300`,
      ATF_728_id: `NW18_HIND_Desktop/NW18_HIND_NEWS_DISTRICT/NW18_HIND_NEWS_DISTRICT_AL/NW18_HIND_NWS_DIST_AL_ROS_ATF_728`,
      BTF_728: `NW18_HIND_Desktop/NW18_HIND_NEWS_DISTRICT/NW18_HIND_NEWS_DISTRICT_AL/NW18_HIND_NWS_DIST_AL_ROS_BTF_728`,
      Shosh_OOP_id: `NW18_HIND_Desktop/NW18_HIND_NEWS_DISTRICT/NW18_HIND_NEWS_DISTRICT_AL/NW18_HIND_NWS_DIST_AL_ROS_Shosh_OOP`,
      Skin_OOP_id: `NW18_HIND_Desktop/NW18_HIND_NEWS_DISTRICT/NW18_HIND_NEWS_DISTRICT_AL/NW18_HIND_NWS_DIST_AL_ROS_Skin_OOP`,
      PG_1x1: `NW18_HIND_Desktop/NW18_HIND_NEWS_DISTRICT/NW18_HIND_NEWS_DISTRICT_AL/NW18_HIND_NWS_DIST_AL_ROS_PG_1x1`,
      ATF_300_id: `NW18_HIND_Desktop/NW18_HIND_NEWS_DISTRICT/NW18_HIND_NEWS_DISTRICT_AL/NW18_HIND_NWS_DIST_AL_ROS_ATF_300`,
      BTF_300_id: `NW18_HIND_Desktop/NW18_HIND_NEWS_DISTRICT/NW18_HIND_NEWS_DISTRICT_AL/NW18_HIND_NWS_DIST_AL_ROS_BTF_300`,
    };
  },
  districtAs: () => {
    return {
      rhs_ATF_300: `NW18_HIND_Desktop/NW18_HIND_NEWS_DISTRICT/NW18_HIND_NEWS_DISTRICT_AS/NW18_HIND_NWS_DIST_AS_ROS_ATF_300`,
      rhs_BTF_300: `NW18_HIND_Desktop/NW18_HIND_NEWS_DISTRICT/NW18_HIND_NEWS_DISTRICT_AS/NW18_HIND_NWS_DIST_AS_ROS_BTF_300`,
      ATF_728_id: `NW18_HIND_Desktop/NW18_HIND_NEWS_DISTRICT/NW18_HIND_NEWS_DISTRICT_AS/NW18_HIND_NWS_DIST_AS_ROS_ATF_728`,
      BTF_728: `NW18_HIND_Desktop/NW18_HIND_NEWS_DISTRICT/NW18_HIND_NEWS_DISTRICT_AS/NW18_HIND_NWS_DIST_AS_ROS_BTF_728`,
      Shosh_OOP_id: `NW18_HIND_Desktop/NW18_HIND_NEWS_DISTRICT/NW18_HIND_NEWS_DISTRICT_AS/NW18_HIND_NWS_DIST_AS_ROS_Shosh_OOP`,
      Skin_OOP_id: `NW18_HIND_Desktop/NW18_HIND_NEWS_DISTRICT/NW18_HIND_NEWS_DISTRICT_AS/NW18_HIND_NWS_DIST_AS_ROS_Skin_OOP`,
      PG_1x1: `NW18_HIND_Desktop/NW18_HIND_NEWS_DISTRICT/NW18_HIND_NEWS_DISTRICT_AS/NW18_HIND_NWS_DIST_AS_ROS_PG_1x1`,
      ATF_300_id: `NW18_HIND_Desktop/NW18_HIND_NEWS_DISTRICT/NW18_HIND_NEWS_DISTRICT_AS/NW18_HIND_NWS_DIST_AS_ROS_ATF_300`,
      BTF_300_id: `NW18_HIND_Desktop/NW18_HIND_NEWS_DISTRICT/NW18_HIND_NEWS_DISTRICT_AS/NW18_HIND_NWS_DIST_AS_ROS_BTF_300`,
    };
  },
  cricketHome: () => {
    return {
      ATF_728_id: `CRINXT_HIND_DESKTOP/CRINXT_HIND_Home/CRINXT_HIND_Home_Home/CRINXT_HIND_HP_ATF_728`,
      MTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_Home/CRINXT_HIND_Home_Home/CRINXT_HIND_HP_MTF_300",
      BTF_728: `CRINXT_HIND_DESKTOP/CRINXT_HIND_Home/CRINXT_HIND_Home_Home/CRINXT_HIND_HP_BTF_728`,
      Shosh_OOP_id: `CRINXT_HIND_DESKTOP/CRINXT_HIND_Home/CRINXT_HIND_Home_Home/CRINXT_HIND_HP_Shosh_OOP`,
      Skin_OOP_id: `CRINXT_HIND_DESKTOP/CRINXT_HIND_Home/CRINXT_HIND_Home_Home/CRINXT_HIND_HP_Skin_OOP`,
      ATF_300_id: `CRINXT_HIND_DESKTOP/CRINXT_HIND_Home/CRINXT_HIND_Home_Home/CRINXT_HIND_HP_ATF_300`,
      BTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_Home/CRINXT_HIND_Home_Home/CRINXT_HIND_HP_BTF_300",
      PG_1x1: `CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AS/CRINXT_HIND_ROS_AS_ROS_PG_1x1`,
      ScoreCard_ad:
        "NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_CRICKET_AS/NW18_HIND_KHEL_CRI_AS_ROS_SCORE_1244",
    };
  },
  liveTv: (section) => {
    const TAGS = section !== undefined && section !== "" ? "AS" : "AL";
    return {
      ATF_728: `NW18_HIND_Desktop/NW18_HIND_LIVETV/NW18_HIND_LIVETV_${TAGS}/NW18_HIND_TV_${TAGS}_ROS_ATF_728`,
      rhs_ATF_300: `NW18_HIND_Desktop/NW18_HIND_LIVETV/NW18_HIND_LIVETV_${TAGS}/NW18_HIND_TV_${TAGS}_ROS_ATF_300`,
      MTF_300_id: "",
      rhs_BTF_300: `NW18_HIND_Desktop/NW18_HIND_LIVETV/NW18_HIND_LIVETV_${TAGS}/NW18_HIND_TV_${TAGS}_ROS_BTF_300`,
      BTF_728: `NW18_HIND_Desktop/NW18_HIND_LIVETV/NW18_HIND_LIVETV_${TAGS}/NW18_HIND_TV_${TAGS}_ROS_BTF_728`,
      Shosh_OOP_id: `NW18_HIND_Desktop/NW18_HIND_LIVETV/NW18_HIND_LIVETV_${TAGS}/NW18_HIND_TV_${TAGS}_ROS_Shosh_OOP`,
      Skin_OOP_id: `NW18_HIND_Desktop/NW18_HIND_LIVETV/NW18_HIND_LIVETV_${TAGS}/NW18_HIND_TV_${TAGS}_ROS_Skin_OOP`,
      PG_1x1: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${TAGS}/NW18_HIND_ROS_${TAGS}_PG_1x1`,
      PG_Slider_1x1: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${TAGS}/NW18_HIND_ROS_${TAGS}_PG_SLIDER_1x1`,
      PG_1x1_2: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${TAGS}/NW18_HIND_ROS_${TAGS}_PG_1x1_2`,
      PG_1x1_3: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${TAGS}/NW18_HIND_ROS_${TAGS}_PG_1x1_3`,
      ATF_728_id: `NW18_HIND_Desktop/NW18_HIND_LIVETV/NW18_HIND_LIVETV_${TAGS}/NW18_HIND_TV_${TAGS}_ROS_ATF_728`,
      ATF_300_id: `NW18_HIND_Desktop/NW18_HIND_LIVETV/NW18_HIND_LIVETV_${TAGS}/NW18_HIND_TV_${TAGS}_ROS_ATF_300`,
      TOP_BAND_940: `NW18_HIND_Desktop/NW18_HIND_LIVETV/NW18_HIND_LIVETV_${TAGS}/NW18_HIND_TV_${TAGS}_ROS_TOP_BAND_940`,
      BTF_300_id: `NW18_HIND_Desktop/NW18_HIND_LIVETV/NW18_HIND_LIVETV_${TAGS}/NW18_HIND_TV_${TAGS}_ROS_BTF_300`,
      BTM_BAND_940: `NW18_HIND_Desktop/NW18_HIND_LIVETV/NW18_HIND_LIVETV_${TAGS}/NW18_HIND_TV_${TAGS}_ROS_BTM_BAND_940`,
    };
  },
  photoGallery: () => {
    return {
      header_ATF_728: `NW18_HIND_Desktop/NW18_HIND_PHOTO/NW18_HIND_PHOTO_HP_AL/NW18_HIND_PHT_HP_AL_ROS_ATF_728`,
      rhs_ATF_300: `NW18_HIND_Desktop/NW18_HIND_PHOTO/NW18_HIND_PHOTO_HP_AL/NW18_HIND_PHT_HP_AL_ROS_ATF_300`,
      MTF_300_id: "",
      rhs_BTF_300: `NW18_HIND_Desktop/NW18_HIND_PHOTO/NW18_HIND_PHOTO_HP_AL/NW18_HIND_PHT_HP_AL_ROS_BTF_300`,
      BTF_728: `NW18_HIND_Desktop/NW18_HIND_PHOTO/NW18_HIND_PHOTO_HP_AL/NW18_HIND_PHT_HP_AL_ROS_BTF_728`,
      Shosh_OOP_id: `NW18_HIND_Desktop/NW18_HIND_PHOTO/NW18_HIND_PHOTO_HP_AL/NW18_HIND_PHT_HP_AL_ROS_Shosh_OOP`,
      Skin_OOP_id: `NW18_HIND_Desktop/NW18_HIND_PHOTO/NW18_HIND_PHOTO_HP_AL/NW18_HIND_PHT_HP_AL_ROS_Skin_OOP`,
      PG_1x1: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_PG_1x1`,
      PG_Slider_1x1: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_PG_SLIDER_1x1`,
      PG_1x1_2: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_PG_1x1_2`,
      ATF_728_id: `NW18_HIND_Desktop/NW18_HIND_PHOTO/NW18_HIND_PHOTO_HP_AL/NW18_HIND_PHT_HP_AL_ROS_ATF_728`,
      ATF_300_id: `NW18_HIND_Desktop/NW18_HIND_PHOTO/NW18_HIND_PHOTO_HP_AL/NW18_HIND_PHT_HP_AL_ROS_ATF_300`,
      BTF_300_id: `NW18_HIND_Desktop/NW18_HIND_PHOTO/NW18_HIND_PHOTO_HP_AL/NW18_HIND_PHT_HP_AL_ROS_BTF_300`,
      PG_1x1_3: `NW18_HIND_Desktop/NW18_HIND_PHOTO/NW18_HIND_PHOTO_HP_AL/NW18_HIND_PHT_HP_AL_ROS_PG_1x1_3`,
    };
  },
  cricketVideo: () => {
    return {
      ATF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_VIDEO/CRINXT_HIND_VIDEO_AL/CRINXT_HIND_VID_AL_ROS_ATF_300",
      MTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_VIDEO/CRINXT_HIND_VIDEO_AL/CRINXT_HIND_VID_AL_ROS_MTF_300",
      BTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_VIDEO/CRINXT_HIND_VIDEO_AL/CRINXT_HIND_VID_AL_ROS_BTF_300",
      ATF_728_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_VIDEO/CRINXT_HIND_VIDEO_AL/CRINXT_HIND_VID_AL_ROS_ATF_728",
      Shosh_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_Shosh_OOP",
      Skin_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_Skin_OOP",
      PG_1x1:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_1x1",
      ScoreCard_ad:
        "NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_CRICKET_AS/NW18_HIND_KHEL_CRI_AS_ROS_SCORE_1244",
    };
  },

  cricketLiveScore: () => {
    return {
      // ATF_300_id : `CRINXT_HIND_DESKTOP/CRINXT_HIND_LIVESCORECARD/CRINXT_HIND_LIVESCORECARD_AS/CRINXT_HIND_LIVSCRCRD_AS_ROS_ATF_300`,
      ATF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_IPLT20_AS/CRINXT_HIND_IPLT20_SCRCD_AS_ROS_ATF_300",
      // MTF_300_id : "CRINXT_HIND_DESKTOP/CRINXT_HIND_LIVESCORECARD/CRINXT_HIND_LIVESCORECARD_AS/CRINXT_HIND_LIVSCRCRD_AS_ROS_MTF_300",
      MTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_IPLT20_AS/CRINXT_HIND_IPLT20_SCRCD_AS_ROS_MTF_300",
      // BTF_300_id : "CRINXT_HIND_DESKTOP/CRINXT_HIND_LIVESCORECARD/CRINXT_HIND_LIVESCORECARD_AS/CRINXT_HIND_LIVSCRCRD_AS_ROS_BTF_300",
      BTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_IPLT20_AS/CRINXT_HIND_IPLT20_SCRCD_AS_ROS_BTF_300",
      ATF_728_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_LIVESCORECARD/CRINXT_HIND_LIVESCORECARD_AS/CRINXT_HIND_LIVSCRCRD_AS_ROS_ATF_728",
      BTF_728:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_LIVESCORECARD/CRINXT_HIND_LIVESCORECARD_AS/CRINXT_HIND_LIVSCRCRD_AS_ROS_BTF_728",
      MID_728:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_LIVESCORECARD/CRINXT_HIND_LIVESCORECARD_AS/CRINXT_HIND_LIVSCRCRD_AS_ROS_MID_728",
      Shosh_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_LIVESCORECARD/CRINXT_HIND_LIVESCORECARD_AS/CRINXT_HIND_LIVSCRCRD_AS_ROS_Shosh_OOP",
      Skin_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_LIVESCORECARD/CRINXT_HIND_LIVESCORECARD_AS/CRINXT_HIND_LIVSCRCRD_AS_ROS_Skin_OOP",
      PG_1x1:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AS/CRINXT_HIND_ROS_AS_ROS_PG_1x1",
    };
  },

  cricketLiveScorePage: () => {
    return {
      // ATF_300_id : `CRINXT_HIND_DESKTOP/CRINXT_HIND_LIVESCORECARD/CRINXT_HIND_LIVESCORECARD_AS/CRINXT_HIND_LIVSCRCRD_AS_ROS_ATF_300`,
      ATF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_IPLT20_AS/CRINXT_HIND_IPLT20_SCRCD_AS_ROS_ATF_300",
      // MTF_300_id : "CRINXT_HIND_DESKTOP/CRINXT_HIND_LIVESCORECARD/CRINXT_HIND_LIVESCORECARD_AS/CRINXT_HIND_LIVSCRCRD_AS_ROS_MTF_300",
      MTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_IPLT20_AS/CRINXT_HIND_IPLT20_SCRCD_AS_ROS_MTF_300",
      // BTF_300_id : "CRINXT_HIND_DESKTOP/CRINXT_HIND_LIVESCORECARD/CRINXT_HIND_LIVESCORECARD_AS/CRINXT_HIND_LIVSCRCRD_AS_ROS_BTF_300",
      BTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_IPLT20_AS/CRINXT_HIND_IPLT20_SCRCD_AS_ROS_BTF_300",
      ATF_728_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_LIVESCORECARD/CRINXT_HIND_LIVESCORECARD_AS/CRINXT_HIND_LIVSCRCRD_AS_ROS_ATF_728",
      BTF_728:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_LIVESCORECARD/CRINXT_HIND_LIVESCORECARD_AS/CRINXT_HIND_LIVSCRCRD_AS_ROS_BTF_728",
      MID_728:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_LIVESCORECARD/CRINXT_HIND_LIVESCORECARD_AS/CRINXT_HIND_LIVSCRCRD_AS_ROS_MID_728",
      Shosh_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_LIVESCORECARD/CRINXT_HIND_LIVESCORECARD_AS/CRINXT_HIND_LIVSCRCRD_AS_ROS_Shosh_OOP",
      Skin_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_LIVESCORECARD/CRINXT_HIND_LIVESCORECARD_AS/CRINXT_HIND_LIVSCRCRD_AS_ROS_Skin_OOP",
      PG_1x1:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AS/CRINXT_HIND_ROS_AS_ROS_PG_1x1",
      PG_1x1_2:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_1x1_2",
      PG_1x1_3:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_1x1_3",
      PG_Slider_1x1:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_Slider_1x1",
      ScoreCard_ad:
        "NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_CRICKET_AS/NW18_HIND_KHEL_CRI_AS_ROS_SCORE_1244",
    };
  },

  webstory: () => {
    return {
      ATF_728_id: `NW18_HIND_Desktop/NW18_HIND_WEB_STORIES/NW18_HIND_WEB_STORIES_AL/NW18_HIND_WEB_STRYS_AL_ROS_ATF_728`,
      ATF_300_id:
        "NW18_HIND_Desktop/NW18_HIND_WEB_STORIES/NW18_HIND_WEB_STORIES_AL/NW18_HIND_WEB_STRYS_AL_ROS_ATF_300",
      BTF_300_id:
        "NW18_HIND_Desktop/NW18_HIND_WEB_STORIES/NW18_HIND_WEB_STORIES_AL/NW18_HIND_WEB_STRYS_AL_ROS_BTF_300",
      BTF_728_id: `NW18_HIND_Desktop/NW18_HIND_WEB_STORIES/NW18_HIND_WEB_STORIES_AL/NW18_HIND_WEB_STRYS_AL_ROS_BTF_728`,
      Shosh_OOP_id:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_Shosh_OOP",
      Skin_OOP_id:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_Skin_OOP",
      OTH_OOP_id: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_OTH_OOP`,
      PG_1x1:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_PG_1x1",
    };
  },
  podcast: () => {
    return {
      ATF_728_id:
        "NW18_HIND_Desktop/NW18_HIND_Home/NW18_HIND_Home_Home/NW18_HIND_HP_ATF_728",
      ATF_300_id:
        "NW18_HIND_Desktop/NW18_HIND_PODCAST/NW18_HIND_PODCAST_AL/NW18_HIND_PDCST_AL_ROS_ATF_300",
      BTF_300_id:
        "NW18_HIND_Desktop/NW18_HIND_PODCAST/NW18_HIND_PODCAST_AL/NW18_HIND_PDCST_AL_ROS_BTF_300",
      Shosh_OOP_id:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_ROS_Shosh_OOP",
      Skin_OOP_id:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_ROS_Skin_OOP",
      PG_1x1:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AS/NW18_HIND_ROS_AS_PG_1x1",
      MTF_300_id:
        "NW18_HIND_Desktop/NW18_HIND_Home/NW18_HIND_Home_Home/NW18_HIND_HP_MTF_300",
      MTF_728_id:
        "NW18_HIND_Desktop/NW18_HIND_Home/NW18_HIND_Home_Home/NW18_HIND_HP_MTF_728",
      BTF_728_id:
        "NW18_HIND_Desktop/NW18_HIND_Home/NW18_HIND_Home_Home/NW18_HIND_HP_BTF_728",
      // NATIVE_id  : 'NW18_HIND_Desktop/NW18_HIND_Home/NW18_HIND_Home_Home/NW18_HIND_HP_NAT1',
    };
  },
  podcastDetails: () => {
    return {
      ATF_728_id:
        "NW18_HIND_Desktop/NW18_HIND_PODCAST/NW18_HIND_PODCAST_AS/NW18_HIND_PDCST_AS_ROS_ATF_728",
      ATF_300_id:
        "NW18_HIND_Desktop/NW18_HIND_PODCAST/NW18_HIND_PODCAST_AS/NW18_HIND_PDCST_AS_ROS_ATF_300",
      BTF_300_id:
        "NW18_HIND_Desktop/NW18_HIND_PODCAST/NW18_HIND_PODCAST_AS/NW18_HIND_PDCST_AS_ROS_BTF_300",
      Shosh_OOP_id:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AS/NW18_HIND_ROS_AS_ROS_Shosh_OOP",
      Skin_OOP_id:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AS/NW18_HIND_ROS_AS_ROS_Skin_OOP",
      PG_1x1:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AS/NW18_HIND_ROS_AS_PG_1x1",
      PG_1x1_2:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AS/NW18_HIND_ROS_AS_PG_1x1_2",
    };
  },
  podcastSubCategory: () => {
    return {
      ATF_728_id:
        "NW18_HIND_Desktop/NW18_HIND_PODCAST/NW18_HIND_PODCAST_AS/NW18_HIND_PDCST_AS_ROS_ATF_728",
      ATF_300_id:
        "NW18_HIND_Desktop/NW18_HIND_PODCAST/NW18_HIND_PODCAST_AS/NW18_HIND_PDCST_AS_ROS_ATF_300",
      BTF_300_id:
        "NW18_HIND_Desktop/NW18_HIND_PODCAST/NW18_HIND_PODCAST_AS/NW18_HIND_PDCST_AS_ROS_BTF_300",
      Shosh_OOP_id:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AS/NW18_HIND_ROS_AS_ROS_Shosh_OOP",
      Skin_OOP_id:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AS/NW18_HIND_ROS_AS_ROS_Skin_OOP",
      PG_Slider_1x1:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AS/NW18_HIND_ROS_AS_PG_Slider_1x1",
      PG_1x1:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AS/NW18_HIND_ROS_AS_PG_1x1",
      PG_1x1_2:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AS/NW18_HIND_ROS_AS_PG_1x1_2",
    };
  },
  cricketNews: () => {
    return {
      ATF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_NEWS/CRINXT_HIND_NEWS_AL/CRINXT_HIND_NWS_AL_ROS_ATF_300",
      MTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_NEWS/CRINXT_HIND_NEWS_AL/CRINXT_HIND_NWS_AL_ROS_MTF_300",
      BTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_NEWS/CRINXT_HIND_NEWS_AL/CRINXT_HIND_NWS_AL_ROS_BTF_300",
      ATF_728_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_NEWS/CRINXT_HIND_NEWS_AL/CRINXT_HIND_NWS_AL_ROS_ATF_728",
      Shosh_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_Shosh_OOP",
      Skin_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_Skin_OOP",
      PG_1x1:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_1x1",
      ScoreCard_ad:
        "NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_CRICKET_AS/NW18_HIND_KHEL_CRI_AS_ROS_SCORE_1244",
    };
  },

  cricketPhotos: () => {
    return {
      ATF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_PHOTO/CRINXT_HIND_PHOTO_AL/CRINXT_HIND_PHT_AL_ROS_ATF_300",
      MTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_PHOTO/CRINXT_HIND_PHOTO_AL/CRINXT_HIND_PHT_AL_ROS_MTF_300",
      BTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_PHOTO/CRINXT_HIND_PHOTO_AL/CRINXT_HIND_PHT_AL_ROS_BTF_300",
      ATF_728_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_PHOTO/CRINXT_HIND_PHOTO_AL/CRINXT_HIND_PHT_AL_ROS_ATF_728",
      Shosh_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_Shosh_OOP",
      Skin_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_Skin_OOP",
      PG_1x1:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_1x1",
      ScoreCard_ad:
        "NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_CRICKET_AS/NW18_HIND_KHEL_CRI_AS_ROS_SCORE_1244",
    };
  },
  cricketRankings: () => {
    return {
      ATF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_RANKING/CRINXT_HIND_RANKING_AL/CRINXT_HIND_RNKG_AL_ROS_ATF_300",
      MTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_RANKING/CRINXT_HIND_RANKING_AL/CRINXT_HIND_RNKG_AL_ROS_MTF_300",
      BTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_RANKING/CRINXT_HIND_RANKING_AL/CRINXT_HIND_RNKG_AL_ROS_BTF_300",
      ATF_728_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_RANKING/CRINXT_HIND_RANKING_AL/CRINXT_HIND_RNKG_AL_ROS_ATF_728",
      Shosh_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_Shosh_OOP",
      Skin_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_Skin_OOP",
      PG_1x1:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_1x1",
      PG_Slider_1x1:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_Slider_1x1",
      ScoreCard_ad:
        "NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_CRICKET_AS/NW18_HIND_KHEL_CRI_AS_ROS_SCORE_1244",
    };
  },
  bitbns: () => {
    return {
      header_ATF_728: `NW18_HIND_Desktop/NW18_HIND_CRYTOCURRENCY/NW18_HIND_CRYTOCURRENCY_MARKET_AL/NW18_HIND_CRYCRY_MKT_AL_ROS_ATF_728`,
      ATF_728_id: `NW18_HIND_Desktop/NW18_HIND_CRYTOCURRENCY/NW18_HIND_CRYTOCURRENCY_MARKET_AL/NW18_HIND_CRYCRY_MKT_AL_ROS_ATF_728`,
      ATF_300_id: `NW18_HIND_Desktop/NW18_HIND_CRYTOCURRENCY/NW18_HIND_CRYTOCURRENCY_MARKET_AL/NW18_HIND_CRYCRY_MKT_AL_ROS_ATF_300`,
      BTF_300_id: `NW18_HIND_Desktop/NW18_HIND_CRYTOCURRENCY/NW18_HIND_CRYTOCURRENCY_MARKET_AL/NW18_HIND_CRYCRY_MKT_AL_ROS_BTF_300`,
      rhs_BTF_300: `NW18_HIND_Desktop/NW18_HIND_CRYTOCURRENCY/NW18_HIND_CRYTOCURRENCY_MARKET_AL/NW18_HIND_CRYCRY_MKT_AL_ROS_BTF_300`,
      // Shosh_OOP_id: 'NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_ROS_Shosh_OOP',
      // Skin_OOP_id: 'NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_ROS_Skin_OOP',
      // PG_1x1: 'NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AS/NW18_HIND_ROS_AS_PG_1x1'
    };
  },
  bitbnscoins: () => {
    return {
      header_ATF_728: `NW18_HIND_Desktop/NW18_HIND_CRYTOCURRENCY/NW18_HIND_CRYTOCURRENCY_GRAPH_AL/NW18_HIND_CRYCRY_GRPH_AL_ROS_ATF_728`,
      ATF_728_id: `NW18_HIND_Desktop/NW18_HIND_CRYTOCURRENCY/NW18_HIND_CRYTOCURRENCY_GRAPH_AL/NW18_HIND_CRYCRY_GRPH_AL_ROS_ATF_728`,
      ATF_300_id: `NW18_HIND_Desktop/NW18_HIND_CRYTOCURRENCY/NW18_HIND_CRYTOCURRENCY_GRAPH_AL/NW18_HIND_CRYCRY_GRPH_AL_ROS_ATF_300`,
      BTF_300_id: `NW18_HIND_Desktop/NW18_HIND_CRYTOCURRENCY/NW18_HIND_CRYTOCURRENCY_GRAPH_AL/NW18_HIND_CRYCRY_GRPH_AL_ROS_BTF_300`,
      rhs_BTF_300: `NW18_HIND_Desktop/NW18_HIND_CRYTOCURRENCY/NW18_HIND_CRYTOCURRENCY_GRAPH_AL/NW18_HIND_CRYCRY_GRPH_AL_ROS_BTF_300`,
      // Shosh_OOP_id: 'NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_ROS_Shosh_OOP',
      // Skin_OOP_id: 'NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_ROS_Skin_OOP',
      // PG_1x1: 'NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AS/NW18_HIND_ROS_AS_PG_1x1'
    };
  },

  dataPages: () => {
    return {
      header_ATF_728: `NW18_HIND_Desktop/NW18_HIND_MOBILE/NW18_HIND_MOBILE_AL/NW18_HIND_MOB_AL_ROS_ATF_728`,
      ATF_728_id: `NW18_HIND_Desktop/NW18_HIND_MOBILE/NW18_HIND_MOBILE_AL/NW18_HIND_MOB_AL_ROS_ATF_728`,
      ATF_300_id: `NW18_HIND_Desktop/NW18_HIND_MOBILE/NW18_HIND_MOBILE_AL/NW18_HIND_MOB_AL_ROS_ATF_300`,
      BTF_300_id: `NW18_HIND_Desktop/NW18_HIND_MOBILE/NW18_HIND_MOBILE_AL/NW18_HIND_MOB_AL_ROS_BTF_300`,
      // rhs_BTF_300: `NW18_HIND_Desktop/NW18_HIND_CRYTOCURRENCY/NW18_HIND_CRYTOCURRENCY_MARKET_AL/NW18_HIND_CRYCRY_MKT_AL_ROS_BTF_300`,
      Shosh_OOP_id:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_Shosh_OOP",
      Skin_OOP_id:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_Skin_OOP",
      PG_1x1:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_PG_1x1",
      PG_Slider_1x1:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_PG_Slider_1x1",
      BTF_728: `NW18_HIND_Desktop/NW18_HIND_MOBILE/NW18_HIND_MOBILE_AL/NW18_HIND_MOB_AL_ROS_BTF_728`,
      PG_1x1_2:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_PG_1x1_2",
      PG_1x1_3:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_PG_1x1_3",
    };
  },
  aqi: () => {
    return {
      header_ATF_728: `NW18_HIND_Desktop/NW18_HIND_AQI_INDIA/NW18_HIND_AQI_INDIA_AL/NW18_HIND_AQI_IND_AL_ROS_ATF_728`,
      ATF_728_id: `NW18_HIND_Desktop/NW18_HIND_AQI_INDIA/NW18_HIND_AQI_INDIA_AL/NW18_HIND_AQI_IND_AL_ROS_ATF_728`,
      BTF_300_id: `NW18_HIND_Desktop/NW18_HIND_AQI_INDIA/NW18_HIND_AQI_INDIA_AL/NW18_HIND_AQI_IND_AL_ROS_BTF_300`,
      ATF_300_id: `NW18_HIND_Desktop/NW18_HIND_AQI_INDIA/NW18_HIND_AQI_INDIA_AL/NW18_HIND_AQI_IND_AL_ROS_ATF_300`,
      BTF_728: `NW18_HIND_Desktop/NW18_HIND_AQI_INDIA/NW18_HIND_AQI_INDIA_AL/NW18_HIND_AQI_IND_AL_ROS_BTF_728`,

      Shosh_OOP_id:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_Shosh_OOP",
      Skin_OOP_id:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_Skin_OOP",
      PG_1x1:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_PG_1x1",
      PG_1x1_2:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_PG_1x1_2",
    };
  },
  blogs: (targetType) => {
    const targetCode = targetType === "listing" ? "AL" : "AS";

    return {
      header_ATF_728: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_ROS_ATF_728`,

      ATF_728_id: `NW18_HIND_Desktop/NW18_HIND_BLOG/NW18_HIND_BLOG_${targetCode}/NW18_HIND_BLG_${targetCode}_ROS_ATF_728`,
      ATF_300_id: `NW18_HIND_Desktop/NW18_HIND_BLOG/NW18_HIND_BLOG_${targetCode}/NW18_HIND_BLG_${targetCode}_ROS_ATF_300`,

      BTF_300_id: `NW18_HIND_Desktop/NW18_HIND_BLOG/NW18_HIND_BLOG_${targetCode}/NW18_HIND_BLG_${targetCode}_ROS_BTF_300`,
      BTF_728: `NW18_HIND_Desktop/NW18_HIND_BLOG/NW18_HIND_BLOG_${targetCode}/NW18_HIND_BLG_${targetCode}_ROS_BTF_728`,

      Shosh_OOP_id: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_ROS_Shosh_OOP`,
      Skin_OOP_id: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_ROS_Skin_OOP`,
      PG_1x1: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_PG_1x1`,
      PG_1x1_2: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_PG_1x1_2`,
      PG_Slider_1x1: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_PG_SLIDER_1x1`,
    };
  },
  shortvideos: (targetType) => {
    const targetCode = targetType === "listing" ? "AL" : "AS";
    return {
      ATF_728_id: `NW18_HIND_Desktop/NW18_HIND_SHORTS_VIDEO/NW18_HIND_SHORT_VIDEO_${targetCode}/NW18_HIND_SHRTS_VDO_${targetCode}_ROS_ATF_728`,
      ATF_300_id: `NW18_HIND_Desktop/NW18_HIND_SHORTS_VIDEO/NW18_HIND_SHORT_VIDEO_${targetCode}/NW18_HIND_SHRTS_VDO_${targetCode}_ROS_ATF_300`,
      BTF_300_id: `NW18_HIND_Desktop/NW18_HIND_SHORTS_VIDEO/NW18_HIND_SHORT_VIDEO_${targetCode}/NW18_HIND_SHRTS_VDO_${targetCode}_ROS_BTF_300`,
      BTF_728: `NW18_HIND_Desktop/NW18_HIND_SHORTS_VIDEO/NW18_HIND_SHORT_VIDEO_${targetCode}/NW18_HIND_SHRTS_VDO_${targetCode}_ROS_BTF_728`,
      Shosh_OOP_id: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_Shosh_OOP`,
      Skin_OOP_id: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_Skin_OOP`,
      PG_1x1: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_PG_1x1`,
      PG_Slider_1x1: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_PG_SLIDER_1x1`,
    };
  },
  cricketMatchSchedule: () => {
    return {
      ATF_728_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_SCHEDULE/CRINXT_HIND_SCHEDULE_AL/CRINXT_HIND_SDLE_AL_ROS_ATF_728",
      ATF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_SCHEDULE/CRINXT_HIND_SCHEDULE_AL/CRINXT_HIND_SDLE_AL_ROS_ATF_300",
      MTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_SCHEDULE/CRINXT_HIND_SCHEDULE_AL/CRINXT_HIND_SDLE_AL_ROS_MTF_300",
      BTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_SCHEDULE/CRINXT_HIND_SCHEDULE_AL/CRINXT_HIND_SDLE_AL_ROS_BTF_300",
      Shosh_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_Shosh_OOP",
      Skin_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_Skin_OOP",
      PG_1x1:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_1x1",
      PG_1x1_2:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_1x1_2",
      PG_1x1_3:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_1x1_3",
      PG_Slider_1x1:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_Slider_1x1",
      ScoreCard_ad:
        "NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_CRICKET_AS/NW18_HIND_KHEL_CRI_AS_ROS_SCORE_1244",
    };
  },
  cricketPlayerProfile: () => {
    return {
      ATF_728_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_ATF_728",
      ATF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_ATF_300",
      MTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_MTF_300",
      BTF_728:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_BTF_728",
      BTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_BTF_300",
      Shosh_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_Shosh_OOP",
      Skin_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_Skin_OOP",
      PG_1x1:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_1x1",
      PG_1x1_2:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_1x1_2",
      PG_1x1_3:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_1x1_3",
      PG_Slider_1x1:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_Slider_1x1",
      ScoreCard_ad:
        "NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_CRICKET_AS/NW18_HIND_KHEL_CRI_AS_ROS_SCORE_1244",
    };
  },
  cricketResult: () => {
    return {
      ATF_728_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_RESULT/CRINXT_HIND_RESULT_AL/CRINXT_HIND_RSLT_AL_ROS_ATF_728",
      ATF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_RESULT/CRINXT_HIND_RESULT_AL/CRINXT_HIND_RSLT_AL_ROS_ATF_300",
      MTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_RESULT/CRINXT_HIND_RESULT_AL/CRINXT_HIND_RSLT_AL_ROS_MTF_300",
      BTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_RESULT/CRINXT_HIND_RESULT_AL/CRINXT_HIND_RSLT_AL_ROS_BTF_300",
      Shosh_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_Shosh_OOP",
      Skin_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_Skin_OOP",
      PG_1x1:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_1x1",
      PG_1x1_2:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_1x1_2",
      PG_1x1_3:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_1x1_3",
      PG_Slider_1x1:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_Slider_1x1",
      ScoreCard_ad:
        "NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_CRICKET_AS/NW18_HIND_KHEL_CRI_AS_ROS_SCORE_1244",
    };
  },
  cricketSeries: ({ firstSlotName, secondSlotName, thirdSlotName }) => {
    return {
      ATF_728_id: `CRINXT_HIND_DESKTOP/CRINXT_HIND_${firstSlotName}/CRINXT_HIND_${secondSlotName}_AL/CRINXT_HIND_${thirdSlotName}_AL_ROS_ATF_728`,
      ATF_300_id: `CRINXT_HIND_DESKTOP/CRINXT_HIND_${firstSlotName}/CRINXT_HIND_${secondSlotName}_AL/CRINXT_HIND_${thirdSlotName}_AL_ROS_ATF_300`,
      MTF_300_id: `CRINXT_HIND_DESKTOP/CRINXT_HIND_${firstSlotName}/CRINXT_HIND_${secondSlotName}_AL/CRINXT_HIND_${thirdSlotName}_AL_ROS_MTF_300`,
      BTF_728: `CRINXT_HIND_DESKTOP/CRINXT_HIND_${firstSlotName}/CRINXT_HIND_${secondSlotName}_AL/CRINXT_HIND_${thirdSlotName}_AL_ROS_BTF_728`,
      BTF_300_id: `CRINXT_HIND_DESKTOP/CRINXT_HIND_${firstSlotName}/CRINXT_HIND_${secondSlotName}_AL/CRINXT_HIND_${thirdSlotName}_AL_ROS_BTF_300`,
      Shosh_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_Shosh_OOP",
      Skin_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_Skin_OOP",
      PG_1x1:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_1x1",
      PG_1x1_2:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_1x1_2",
      PG_1x1_3:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_1x1_3",
      PG_Slider_1x1:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_Slider_1x1",
      ScoreCard_ad:
        "NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_CRICKET_AS/NW18_HIND_KHEL_CRI_AS_ROS_SCORE_1244",
    };
  },
  budget: () => {
    return {
      ATF_728_id: `NW18_HIND_Desktop/NW18_HIND_BUDGET/NW18_HIND_BUDGET_HOME/NW18_HIND_BDGT_HP_ATF_728`,
      BTF_728_0: `NW18_HIND_Desktop/NW18_HIND_BUDGET/NW18_HIND_BUDGET_HOME/NW18_HIND_BDGT_HP_BTF_728`,
      MTF_728_0: `NW18_HIND_Desktop/NW18_HIND_BUDGET/NW18_HIND_BUDGET_HOME/NW18_HIND_BDGT_HP_MTF_728`,
      HP_ATF_300:
        "NW18_HIND_Desktop/NW18_HIND_BUDGET/NW18_HIND_BUDGET_HOME/NW18_HIND_BDGT_HP_ATF_300",
      Shosh_OOP_id:
        "NW18_HIND_Desktop/NW18_HIND_BUDGET/NW18_HIND_BUDGET_HOME/NW18_HIND_BDGT_HP_Shosh_OOP",
      PG_Slider_1x1:
        "NW18_HIND_Desktop/NW18_HIND_BUDGET/NW18_HIND_BUDGET_HOME/NW18_HIND_BDGT_HP_PG_Slider_1x1",
      Skin_OOP_id:
        "NW18_HIND_Desktop/NW18_HIND_BUDGET/NW18_HIND_BUDGET_HOME/NW18_HIND_BDGT_HP_Skin_OOP",
      BTF_300_id:
        "NW18_HIND_Desktop/NW18_HIND_BUDGET/NW18_HIND_BUDGET_HOME/NW18_HIND_BDGT_HP_BTF_300",
      PG_1x1:
        "NW18_HIND_Desktop/NW18_HIND_BUDGET/NW18_HIND_BUDGET_HOME/NW18_HIND_BDGT_HP_PG_1x1",
      PG_1x1_2:
        "NW18_HIND_Desktop/NW18_HIND_BUDGET/NW18_HIND_BUDGET_HOME/NW18_HIND_BDGT_HP_PG_1x1_2",
      companion_banner:
        "NW18_HIND_Desktop/NW18_HIND_EVENT_Home/NW18_HIND_EVENT_Home_Home/NW18_HIND_HP_ROS_EVENT_TOP_1244x60",
    };
  },
  minis: () => {
    return {
      ATF_728_id: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_ROS_ATF_728`,
      ATF_300_id: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_ROS_ATF_300`,
      BTF_300_id: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_ROS_BTF_300`,
    };
  },
  staticPages: () => {
    return {
      ATF_728_id: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_ROS_ATF_728`,
      ATF_300_id: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_ROS_ATF_300`,
      BTF_300_id: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_ROS_BTF_300`,
      Shosh_OOP_id: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_ROS_Shosh_OOP`,
      Skin_OOP_id: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_ROS_Skin_OOP`,
      PG_1x1: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AS/NW18_HIND_ROS_AS_PG_1x1`,
      PG_1x1_2: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AS/NW18_HIND_ROS_AS_PG_1x1_2`,
    };
  },
  boardresult: () => {
    return {
      ATF_728_id: `NW18_HIND_Desktop/NW18_HIND_BOARDRESULT/NW18_HIND_BOARDRESULT_AS/NW18_HIND_BRDRST_AS_ROS_ATF_728`,
      BTF_728_0: `NW18_HIND_Desktop/NW18_HIND_BOARDRESULT/NW18_HIND_BOARDRESULT_AS/NW18_HIND_BRDRST_AS_ROS_BTF_728`,
      MTF_728_0: `NW18_HIND_Desktop/NW18_HIND_BOARDRESULT/NW18_HIND_BOARDRESULT_AS/NW18_HIND_BRDRST_AS_ROS_BTF_728`,
      HP_ATF_300:
        "NW18_HIND_Desktop/NW18_HIND_BOARDRESULT/NW18_HIND_BOARDRESULT_AS/NW18_HIND_BRDRST_AS_ROS_ATF_300",
      Shosh_OOP_id:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_Shosh_OOP",
      PG_Slider_1x1:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_PG_Slider_1x1",
      Skin_OOP_id:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_Skin_OOP",
      BTF_300_id:
        "NW18_HIND_Desktop/NW18_HIND_BOARDRESULT/NW18_HIND_BOARDRESULT_AS/NW18_HIND_BRDRST_AS_ROS_BTF_300",
      PG_1x1_2:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_PG_1x1_2",
      PG_1x1_3:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_PG_1x1_3",
    };
  },
  IPLPage: () => {
    return {
      ATF_728_id: `NW18_HIND_Desktop/NW18_HIND_IPLT20/NW18_HIND_IPLT20_AL/NW18_HIND_IPLT20_AL_ROS_ATF_728`,
      MTF_300_id:
        "NW18_HIND_Desktop/NW18_HIND_IPLT20/NW18_HIND_IPLT20_AL/NW18_HIND_IPLT20_AL_ROS_MTF_300",
      BTF_728: `NW18_HIND_Desktop/NW18_HIND_IPLT20/NW18_HIND_IPLT20_AL/NW18_HIND_IPLT20_AL_ROS_BTF_728`,
      Shosh_OOP_id: `NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_CRICKET_AL/NW18_HIND_KHEL_CRI_AL_ROS_Shosh_OOP`,
      Skin_OOP_id: `NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_CRICKET_AL/NW18_HIND_KHEL_CRI_AL_ROS_Skin_OOP`,
      ATF_300_id: `NW18_HIND_Desktop/NW18_HIND_IPLT20/NW18_HIND_IPLT20_AL/NW18_HIND_IPLT20_AL_ROS_ATF_300`,
      BTF_300_id:
        "NW18_HIND_Desktop/NW18_HIND_IPLT20/NW18_HIND_IPLT20_AL/NW18_HIND_IPLT20_AL_ROS_BTF_300",
      PG_1x1: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_ROS_PG_1x1`,
      PG_1x1_2: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_PG_1x1_2`,
      PG_SLIDER_1x1: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_PG_SLIDER_1x1`,
      ScoreCard_ad:
        "NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_CRICKET_AS/NW18_HIND_KHEL_CRI_AS_ROS_SCORE_1244",
    };
  },
  isInfographics: () => {
    return {
      ATF_728_id: `NW18_HIND_Desktop/NW18_HIND_PHOTO/NW18_HIND_PHOTO_STORIES_AS/NW18_HIND_PHT_STRYS_AS_ROS_ATF_728`,
      ATF_300_id: `NW18_HIND_Desktop/NW18_HIND_PHOTO/NW18_HIND_PHOTO_STORIES_AS/NW18_HIND_PHT_STRYS_AS_ROS_ATF_300`,
      BTF_300_id: `NW18_HIND_Desktop/NW18_HIND_PHOTO/NW18_HIND_PHOTO_STORIES_AS/NW18_HIND_PHT_STRYS_AS_ROS_BTF_300`,
      Shosh_OOP_id: `NW18_HIND_Desktop/NW18_HIND_PHOTO/NW18_HIND_PHOTO_STORIES_AS/NW18_HIND_ROS_AS_Shosh_OOP`,
      Skin_OOP_id: `NW18_HIND_Desktop/NW18_HIND_PHOTO/NW18_HIND_PHOTO_STORIES_AS/NW18_HIND_ROS_AS_Skin_OOP`,
      PG_1x1: `NW18_HIND_Desktop/NW18_HIND_PHOTO/NW18_HIND_PHOTO_STORIES_AS/NW18_HIND_ROS_AS_PG_1x1`,
      PG_Slider_1x1: `NW18_HIND_Desktop/NW18_HIND_PHOTO/NW18_HIND_PHOTO_STORIES_AS/NW18_HIND_ROS_AS_PG_SLIDER_1x1`,
    };
  },

  proKabaddiHome: () => {
    return {
      ATF_728_id: `NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_AS/NW18_HIND_KHEL_AS_ROS_ATF_728`,
      BTF_728_id: `NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_AS/NW18_HIND_KHEL_AS_ROS_BTF_728`,
      ATF_300_id: `NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_AS/NW18_HIND_KHEL_AS_ROS_ATF_300`,
      BTF_300_id: `NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_AL/NW18_HIND_KHEL_AL_ROS_BTF_300`,
      Shosh_OOP_id: `NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_AS/NW18_HIND_KHEL_AS_ROS_Shosh_OOP`,
      Skin_OOP_id: `NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_AS/NW18_HIND_KHEL_AS_ROS_Skin_OOP`,
      PG_1x1:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AS/NW18_HIND_ROS_AS_PG_1x1",
      PG_1x1_2:
        "NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AS/NW18_HIND_ROS_AS_PG_1x1_2",
    };
  },
  liveblog: () => {
    return {
      ATF_728_id: `NW18_HIND_Desktop/NW18_HIND_LIVEBLOG/NW18_HIND_LIVEBLOG_AS/NW18_HIND_LIVBLG_AS_ROS_ATF_728`,
      ATF_300_id: `NW18_HIND_Desktop/NW18_HIND_LIVEBLOG/NW18_HIND_LIVEBLOG_AS/NW18_HIND_LIVBLG_AS_ROS_ATF_300`,
      BTF_300_id: `NW18_HIND_Desktop/NW18_HIND_LIVEBLOG/NW18_HIND_LIVEBLOG_AS/NW18_HIND_LIVBLG_AS_ROS_BTF_300`,
      BTF_728: `NW18_HIND_Desktop/NW18_HIND_LIVEBLOG/NW18_HIND_LIVEBLOG_AS/NW18_HIND_LIVBLG_AS_ROS_BTF_728`,
      Shosh_OOP_id: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AS/NW18_HIND_ROS_AS_ROS_Shosh_OOP`,
      Skin_OOP_id: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AS/NW18_HIND_ROS_AS_ROS_Skin_OOP`,
      PG_1x1: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AS/NW18_HIND_ROS_AS_ROS_PG_1x1`,
      PG_Slider_1x1: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AS/NW18_HIND_ROS_AS_ROS_PG_Slider_1x1`,
      PG_1x1_2: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AS/NW18_HIND_ROS_AS_PG_1x1_2`,
    };
  },
  rammandir: () => {
    return {
      ATF_728_id: `NW18_HIND_Desktop/NW18_HIND_EVENT/NW18_HIND_EVENT_AL/NW18_HIND_EVNT_AL_ROS_ATF_728`,
      ATF_300_id: `NW18_HIND_Desktop/NW18_HIND_EVENT/NW18_HIND_EVENT_AL/NW18_HIND_EVNT_AL_ROS_ATF_300`,
      MTF_728_id: `NW18_HIND_Desktop/NW18_HIND_EVENT/NW18_HIND_EVENT_AL/NW18_HIND_EVNT_AL_ROS_MTF_728`,
      MID_728_id: `NW18_HIND_Desktop/NW18_HIND_EVENT/NW18_HIND_EVENT_AL/NW18_HIND_EVNT_AL_ROS_MID_728`,
      ROS_MID_728: `NW18_HIND_Desktop/NW18_HIND_EVENT/NW18_HIND_EVENT_AL/NW18_HIND_EVNT_AL_ROS_MID_728`,
      BTF_300: `NW18_HIND_Desktop/NW18_HIND_EVENT/NW18_HIND_EVENT_AL/NW18_HIND_EVNT_AL_ROS_BTF_300`,
      BTF_728: `NW18_HIND_Desktop/NW18_HIND_EVENT/NW18_HIND_EVENT_AL/NW18_HIND_EVNT_AL_ROS_BTF_728`,
      Shosh_OOP_id: `NW18_HIND_Desktop/NW18_HIND_EVENT/NW18_HIND_EVENT_AL/NW18_HIND_EVNT_AL_ROS_Shosh_OOP`,
      Skin_OOP_id: `NW18_HIND_Desktop/NW18_HIND_EVENT/NW18_HIND_EVENT_AL/NW18_HIND_EVNT_AL_ROS_Skin_OOP`,
      PG_1x1: `NW18_HIND_Desktop/NW18_HIND_EVENT/NW18_HIND_EVENT_AL/NW18_HIND_EVNT_AL_ROS_PG_1x1`,
      PG_Slider_1x1: `NW18_HIND_Desktop/NW18_HIND_EVENT/NW18_HIND_EVENT_AL/NW18_HIND_EVNT_AL_ROS_PG_SLIDER_1x1`,
      companion_banner: `NW18_HIND_Desktop/NW18_HIND_EVENT/NW18_HIND_EVENT_AL/NW18_HIND_EVNT_SPONSOR_TOP_STRIP_1244x60`,
    };
  },
  boardResultLanding: () => {
    return {
      ATF_728_id: `NW18_HIND_Desktop/NW18_HIND_BOARDRESULT/NW18_HIND_BOARDRESULT_AL/NW18_HIND_BRDRSLT_AL_ROS_ATF_728`,
      ATF_300_id: `NW18_HIND_Desktop/NW18_HIND_BOARDRESULT/NW18_HIND_BOARDRESULT_AL/NW18_HIND_BRDRSLT_AL_ROS_ATF_300`,
      BTF_300: `NW18_HIND_Desktop/NW18_HIND_BOARDRESULT/NW18_HIND_BOARDRESULT_AL/NW18_HIND_BRDRSLT_AL_ROS_BTF_300`,
      MTF_300_id:`NW18_HIND_Desktop/NW18_HIND_BOARDRESULT/NW18_HIND_BOARDRESULT_AL/NW18_HIND_BRDRSLT_AL_ROS_MTF_300`,
      BTF_728: `NW18_HIND_Desktop/NW18_HIND_BOARDRESULT/NW18_HIND_BOARDRESULT_AL/NW18_HIND_BRDRSLT_AL_ROS_BTF_728`,
    };
  },
  boardResultConsum: () => {
    return {
      ATF_728_id: `NW18_HIND_Desktop/NW18_HIND_BOARDRESULT/NW18_HIND_BOARDRESULT_AS/NW18_HIND_BRDRSLT_AS_ROS_ATF_728`,
      ATF_300_id: `NW18_HIND_Desktop/NW18_HIND_BOARDRESULT/NW18_HIND_BOARDRESULT_AS/NW18_HIND_BRDRSLT_AS_ROS_ATF_300`,
      BTF_300: `NW18_HIND_Desktop/NW18_HIND_BOARDRESULT/NW18_HIND_BOARDRESULT_AS/NW18_HIND_BRDRSLT_AS_ROS_BTF_300`,
      MTF_300_id:`NW18_HIND_Desktop/NW18_HIND_BOARDRESULT/NW18_HIND_BOARDRESULT_AS/NW18_HIND_BRDRSLT_AS_ROS_MTF_300`,
      BTF_728: `NW18_HIND_Desktop/NW18_HIND_BOARDRESULT/NW18_HIND_BOARDRESULT_AS/NW18_HIND_BRDRSLT_AS_ROS_BTF_728`,
    };
  },
  T20WC_MR_MW_P: () => {
    return {
      ATF_728_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_AL/CRINXT_HIND_IPLT20_AL_ROS_ATF_728",
      ATF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_AL/CRINXT_HIND_IPLT20_AL_ROS_ATF_300",
      MTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_MTF_300",
      BTF_300_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_IPLT20/CRINXT_HIND_IPLT20_AL/CRINXT_HIND_IPLT20_AL_ROS_BTF_300",
      Shosh_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_Shosh_OOP",
      Skin_OOP_id:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_Skin_OOP",
      PG_1x1: `CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AS/CRINXT_HIND_ROS_AS_ROS_PG_1x1`,
      PG_Slider_1x1:
        "CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_Slider_1x1",
      ScoreCard_ad:
        "NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_CRICKET_AS/NW18_HIND_KHEL_CRI_AS_ROS_SCORE_1244",
    };
  },
  olympics: () => {
    return {
      ATF_300_id: 'NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_AL/NW18_HIND_KHEL_AL_ROS_ATF_300',
      ATF_728_id: 'NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_AL/NW18_HIND_KHEL_AL_ROS_ATF_728',
      BTF_300_id: 'NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_AL/NW18_HIND_KHEL_AL_ROS_BTF_300',
      BTF_728: 'NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_AL/NW18_HIND_KHEL_AL_ROS_BTF_728',
      header_ATF_728: 'NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_AL/NW18_HIND_KHEL_AL_ROS_MID_728',
      LBAND_1x1: 'NW18_HIND_Desktop/NW18_HIND_LOCAL18_NEWS/NW18_HIND_LOCAL18_NEWS_AS/NW18_HIND_LOCAS18_NWS_AS_ROS_LBAND_1x1',
      LBAND_480X60: 'NW18_HIND_Desktop/NW18_HIND_LOCAL18_NEWS/NW18_HIND_LOCAL18_NEWS_AS/NW18_HIND_LOCAS18_NWS_AS_ROS_LBAND_480x60',
      MTF_300: 'NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_AL/NW18_HIND_KHEL_AL_ROS_MTF_300',
      PG_1x1: 'NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_ROS_PG_1x1',
      PG_1x1_2: 'NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_PG_1x1_2',
      PG_1x1_3: 'NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_PG_1x1_3',
      PG_Slider_1x1: 'NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_ROS_PG_Slider_1x1',
      rhs_ATF_300: 'NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_AL/NW18_HIND_KHEL_AL_ROS_ATF_300',
      rhs_BTF_300: 'NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_AL/NW18_HIND_KHEL_AL_ROS_BTF_300',
      rhs_MTF_300: 'NW18_HIND_Desktop/NW18_HIND_KHEL/NW18_HIND_KHEL_AL/NW18_HIND_KHEL_AL_ROS_MTF_300',
      Shosh_OOP_id: 'NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_ROS_Shosh_OOP',
      Skin_OOP_id: 'NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_ROS_Skin_OOP'
    };
  },
}

module.exports = dfpIds;
