import { generateMobileAdTags } from "config/ads_pwa.config";

const dfpMobileIds = {
  home: () => {
    return {
      ATF_320: `NW18_HIND_PWA/NW18_HIND_IPLT20_PWA/NW18_HIND_IPLT20_PWA_AL/NW18_HIND_IPLT20_AL_PWA_ROS_ATF_320`,
      first:
        "News18_Hindi_WAP/News18_Hindi_WAP_HP/News18_Hindi_WAP_HP_Native_Fluid",
      second:
        "News18_Hindi_WAP/News18_Hindi_WAP_HP/News18_Hindi_WAP_HP_300x250_1",
      mobile_first:
        "NW18_HIND_PWA/NW18_HIND_HOME_PWA/NW18_HIND_HOME_HOME_PWA/NW18_HIND_PWA_HP_ATF_320",
      mobile_second:
        "NW18_HIND_PWA/NW18_HIND_HOME_PWA/NW18_HIND_HOME_HOME_PWA/NW18_HIND_PWA_HP_ATF_300",
      mobile_third:
        "NW18_HIND_PWA/NW18_HIND_HOME_PWA/NW18_HIND_HOME_HOME_PWA/NW18_HIND_PWA_HP_NAT1",
      ATF_SLUG_300_id:
        "NW18_HIND_PWA/NW18_HIND_HOME_PWA/NW18_HIND_HOME_HOME_PWA/NW18_HIND_PWA_HP_ATF_SLUG_300",
      mobile_fifth:
        "NW18_HIND_PWA/NW18_HIND_HOME_PWA/NW18_HIND_HOME_HOME_PWA/NW18_HIND_PWA_HP_BTF_300",
      MTF_SLUG_300_id:
        "NW18_HIND_PWA/NW18_HIND_HOME_PWA/NW18_HIND_HOME_HOME_PWA/NW18_HIND_PWA_HP_MTF_SLUG_300",
      FBN_320:
        "NW18_HIND_PWA/NW18_HIND_HOME_PWA/NW18_HIND_HOME_HOME_PWA/NW18_HIND_PWA_HP_FBN_320",
      SHOSH_OOP:
        "NW18_HIND_PWA/NW18_HIND_HOME_PWA/NW18_HIND_HOME_HOME_PWA/NW18_HIND_PWA_HP_Shosh_OOP",
      SKIN_OOP:
        "NW18_HIND_PWA/NW18_HIND_HOME_PWA/NW18_HIND_HOME_HOME_PWA/NW18_HIND_PWA_HP_SKIN_OOP",
      PG_Slider_1x1:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_PG_1x1",
      PG_1x1_2:
        "NW18_HIND_PWA/NW18_HIND_HOME_PWA/NW18_HIND_HOME_HOME_PWA/NW18_HIND_PWA_HP_PG_1x1_2",
      PG_1x1_3:
        "NW18_HIND_PWA/NW18_HIND_HOME_PWA/NW18_HIND_HOME_HOME_PWA/NW18_HIND_PWA_HP_PG_1x1_3",
      PG_1x1_4:
        "NW18_HIND_PWA/NW18_HIND_HOME_PWA/NW18_HIND_HOME_HOME_PWA/NW18_HIND_PWA_HP_PG_1x1_4",
    };
  },
  T20WcSchedule: () => {
    return {
      ATF_320: `CRINXT_HIND_PWA/CRINXT_HIND_IPLT20_PWA/CRINXT_HIND_IPLT20_SCHEDULE_PWA_AL/CRINXT_HIND_IPLT20_SCHDL_AL_PWA_ROS_ATF_320`,
      ATF_300: `CRINXT_HIND_PWA/CRINXT_HIND_IPLT20_PWA/CRINXT_HIND_IPLT20_SCHEDULE_PWA_AL/CRINXT_HIND_IPLT20_SCHDL_AL_PWA_ROS_ATF_300`,
      BTF_300: `CRINXT_HIND_PWA/CRINXT_HIND_IPLT20_PWA/CRINXT_HIND_IPLT20_SCHEDULE_PWA_AL/CRINXT_HIND_IPLT20_SCHDL_AL_PWA_ROS_BTF_300`,
      FBN_320:
        "CRINXT_HIND_PWA/CRINXT_HIND_IPLT20_PWA/CRINXT_HIND_IPLT20_SCHEDULE_PWA_AL/CRINXT_HIND_IPLT20_SCHDL_AL_PWA_ROS_FBN_320",
      scoreCard_Ad: `NW18_HIND_PWA/NW18_HIND_KHEL_PWA/NW18_HIND_KHEL_CRI_PWA_AS/NW18_HIND_KHEL_CRI_AS_PWA_ROS_SCORE_32O`,
      SKIN_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SKIN_OOP",
      SHOSH_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SHOSH_OOP",
      PG_1x1: `CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1`,
      PG_Slider_1x1: `CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_Slider_1x1`,
    };
  },

  T20WcResults: () => {
    return {
      ATF_320: `CRINXT_HIND_PWA/CRINXT_HIND_IPLT20_PWA/CRINXT_HIND_IPLT20_RESULT_PWA_AL/CRINXT_HIND_IPLT20_RSLT_AL_PWA_ROS_ATF_320`,
      ATF_300: `CRINXT_HIND_PWA/CRINXT_HIND_IPLT20_PWA/CRINXT_HIND_IPLT20_RESULT_PWA_AL/CRINXT_HIND_IPLT20_RSLT_AL_PWA_ROS_ATF_300`,
      BTF_300: `CRINXT_HIND_PWA/CRINXT_HIND_IPLT20_PWA/CRINXT_HIND_IPLT20_RESULT_PWA_AL/CRINXT_HIND_IPLT20_RSLT_AL_PWA_ROS_BTF_300`,
      FBN_320:
        "CRINXT_HIND_PWA/CRINXT_HIND_IPLT20_PWA/CRINXT_HIND_IPLT20_RESULT_PWA_AL/CRINXT_HIND_IPLT20_RSLT_AL_PWA_ROS_FBN_320",
      scoreCard_Ad: `NW18_HIND_PWA/NW18_HIND_KHEL_PWA/NW18_HIND_KHEL_CRI_PWA_AS/NW18_HIND_KHEL_CRI_AS_PWA_ROS_SCORE_32O`,
      SKIN_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SKIN_OOP",
      SHOSH_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SHOSH_OOP",
      PG_1x1: `CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1`,
      PG_Slider_1x1: `CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_Slider_1x1`,
    };
  },
  category: (urlParam, isPhoto = false) => {
    let _tf = urlParam.t || "";
    _tf = _tf.replace("-", "_");
    _tf = isPhoto ? "photogallery" : _tf;
    let _section = urlParam.section || "";
    _section = _section.replace("-", "_");
    let _subsection = urlParam.subsection || "";
    _subsection = _subsection.replace("-", "_");

    const ads = _subsection
      ? generateMobileAdTags("listing", _subsection, isPhoto)
      : _section
      ? generateMobileAdTags("listing", _section, isPhoto)
      : generateMobileAdTags("listing", _tf, isPhoto);

    return {
      header_ATF_320: ads.header_ATF_320,
      FBN_320: ads.FBN_320,
      ATF_300: ads.ATF_300,
      NAT1: "",
      NAT2: "",
      NAT3: "",
      BTF_300: ads.BTF_300,
      SHOSH_OOP: ads.SHOSH_OOP,
      SKIN_OOP: ads.SKIN_OOP,
      PG_1x1: ads.PG_1x1,
      PG_Slider_1x1: ads.PG_Slider_1x1,
      ATF_320: ads.header_ATF_320,
      PG_1x1_2: ads.PG_1x1_2,
      PG_1x1_3: ads.PG_1x1_3,
      PG_1x1_4: ads.PG_1x1_4,
    };
  },
  states: (urlParam) => {
    let _tf = urlParam.t || "";
    _tf = _tf.replace("-", "_");
    let _section = urlParam.section || "";
    _section = _section.replace("-", "_");
    const isPhoto = false;
    const ads = _section
      ? generateMobileAdTags("listing", _section, isPhoto)
      : generateMobileAdTags("listing", _tf, isPhoto);
    return {
      header_ATF_320: ads.header_ATF_320,
      FBN_320: ads.FBN_320,
      ATF_300: ads.ATF_300,
      NAT1: "",
      NAT2: "",
      NAT3: "",
      BTF_300: ads.BTF_300,
      SHOSH_OOP: ads.SHOSH_OOP,
      SKIN_OOP: ads.SKIN_OOP,
      PG_1x1: ads.PG_1x1,
      PG_Slider_1x1: "",
      ATF_320: ads.header_ATF_320,
    };
  },
  videos: () => {
    const isPhoto = false;
    const ads = generateMobileAdTags("listing", "videos", isPhoto);
    return {
      header_ATF_320: ads.header_ATF_320,
      FBN_320: ads.FBN_320,
      ATF_300: ads.ATF_300,
      NAT1: "",
      NAT2: "",
      NAT3: "",
      BTF_300: ads.BTF_300,
      SHOSH_OOP: ads.SHOSH_OOP,
      SKIN_OOP: ads.SKIN_OOP,
      PG_1x1: ads.PG_1x1,
      PG_Slider_1x1: ads.PG_Slider_1x1,
      ATF_320: ads.header_ATF_320,
    };
  },
  article: (params, isPhoto, opt = "", isDistrict = false) => {
    let _cat = params.cat;

    if (params.subCat) {
      _cat = _cat + "_" + params.subCat;
    }
    const ads = generateMobileAdTags("article", _cat, isPhoto, {}, isDistrict);

    return {
      header_ATF_320: ads.header_ATF_320,
      FBN_320: ads.FBN_320,
      ATF_300: ads.ATF_300,
      NAT1: "",
      NAT2: "",
      NAT3: "",
      BTF_300: ads.BTF_300,
      SHOSH_OOP: ads.SHOSH_OOP,
      SKIN_OOP: ads.SKIN_OOP,
      PG_1x1: ads.PG_1x1,
      PG_Slider_1x1: ads.PG_Slider_1x1,
      PG_1x1_2: ads.PG_1x1_2,
      PG_1x1_3: ads.PG_1x1_3,
      LBAND_340x60: ads.LBAND_340x60,
      PG_1x1_4: ads.PG_1x1_4,
      MTF_300: ads?.MTF_300 || null,
    };
  },
  district: () => {
    return {
      header_ATF_320:
        "NW18_HIND_PWA/NW18_HIND_NEWS_DISTRICT_PWA/NW18_HIND_NEWS_DISTRICT_PWA_AL/NW18_HIND_NWS_DIST_AL_PWA_ROS_ATF_320",
      ATF_300:
        "NW18_HIND_PWA/NW18_HIND_NEWS_DISTRICT_PWA/NW18_HIND_NEWS_DISTRICT_PWA_AL/NW18_HIND_NWS_DIST_AL_PWA_ROS_ATF_300",
      BTF_300:
        "NW18_HIND_PWA/NW18_HIND_NEWS_DISTRICT_PWA/NW18_HIND_NEWS_DISTRICT_PWA_AL/NW18_HIND_NWS_DIST_AL_PWA_ROS_BTF_300",
      FBN_320:
        "NW18_HIND_PWA/NW18_HIND_NEWS_DISTRICT_PWA/NW18_HIND_NEWS_DISTRICT_PWA_AL/NW18_HIND_NWS_DIST_AL_PWA_ROS_FBN_320",
      PG_1x1:
        "NW18_HIND_PWA/NW18_HIND_NEWS_DISTRICT_PWA/NW18_HIND_NEWS_DISTRICT_PWA_AL/NW18_HIND_NWS_DIST_AL_PWA_ROS_PG_1x1",
      PG_Slider_1x1:
        "NW18_HIND_PWA/NW18_HIND_NEWS_DISTRICT_PWA/NW18_HIND_NEWS_DISTRICT_PWA_AL/NW18_HIND_NWS_DIST_AL_PWA_ROS_PG_Slider_1x1",
    };
  },
  districtAs: () => {
    return {
      header_ATF_320:
        "NW18_HIND_PWA/NW18_HIND_NEWS_DISTRICT_PWA/NW18_HIND_NEWS_DISTRICT_PWA_AS/NW18_HIND_NWS_DIST_AS_PWA_ROS_ATF_320",
      ATF_300:
        "NW18_HIND_PWA/NW18_HIND_NEWS_DISTRICT_PWA/NW18_HIND_NEWS_DISTRICT_PWA_AS/NW18_HIND_NWS_DIST_AS_PWA_ROS_ATF_300",
      BTF_300:
        "NW18_HIND_PWA/NW18_HIND_NEWS_DISTRICT_PWA/NW18_HIND_NEWS_DISTRICT_PWA_AS/NW18_HIND_NWS_DIST_AS_PWA_ROS_BTF_300",
      FBN_320:
        "NW18_HIND_PWA/NW18_HIND_NEWS_DISTRICT_PWA/NW18_HIND_NEWS_DISTRICT_PWA_AS/NW18_HIND_NWS_DIST_AS_PWA_ROS_FBN_320",
      PG_1x1:
        "NW18_HIND_PWA/NW18_HIND_NEWS_DISTRICT_PWA/NW18_HIND_NEWS_DISTRICT_PWA_AS/NW18_HIND_NWS_DIST_AS_PWA_ROS_PG_1x1",
      PG_Slider_1x1:
        "NW18_HIND_PWA/NW18_HIND_NEWS_DISTRICT_PWA/NW18_HIND_NEWS_DISTRICT_PWA_AS/NW18_HIND_NWS_DIST_AS_PWA_ROS_PG_Slider_1x1",
    };
  },
  liveTv: (section) => {
    const TAGS = section !== undefined && section !== "" ? "AS" : "AL";
    return {
      ATF_320: `NW18_HIND_PWA/NW18_HIND_LIVETV_PWA/NW18_HIND_LIVETV_PWA_${TAGS}/NW18_HIND_TV_${TAGS}_PWA_ROS_ATF_320`,
      FBN_320: `NW18_HIND_PWA/NW18_HIND_LIVETV_PWA/NW18_HIND_LIVETV_PWA_${TAGS}/NW18_HIND_TV_${TAGS}_PWA_ROS_FBN_320`,
      ATF_300: `NW18_HIND_PWA/NW18_HIND_LIVETV_PWA/NW18_HIND_LIVETV_PWA_${TAGS}/NW18_HIND_TV_${TAGS}_PWA_ROS_ATF_300`,
      NAT1: `NW18_HIND_PWA/NW18_HIND_LIVETV_PWA/NW18_HIND_LIVETV_PWA_${TAGS}/NW18_HIND_TV_${TAGS}_PWA_ROS_BTF_300`,
      NAT2: `NW18_HIND_PWA/NW18_HIND_LIVETV_PWA/NW18_HIND_LIVETV_PWA_${TAGS}/NW18_HIND_TV_${TAGS}_PWA_ROS_BTF_728`,
      NAT3: `NW18_HIND_PWA/NW18_HIND_LIVETV_PWA/NW18_HIND_LIVETV_PWA_${TAGS}/NW18_HIND_TV_${TAGS}_PWA_ROS_BTF_728`,
      BTF_300: `NW18_HIND_PWA/NW18_HIND_LIVETV_PWA/NW18_HIND_LIVETV_PWA_${TAGS}/NW18_HIND_TV_${TAGS}_PWA_ROS_BTF_300`,
      PG_1x1: `NW18_HIND_PWA/NW18_HIND_LIVETV_PWA/NW18_HIND_LIVETV_PWA_${TAGS}/NW18_HIND_${TAGS}_PWA_ROS_PG_1x1`,
      PG_Slider_1x1: `NW18_HIND_PWA/NW18_HIND_LIVETV_PWA/NW18_HIND_LIVETV_PWA_${TAGS}/NW18_HIND_${TAGS}_PWA_ROS_PG_SLIDER_1x1`,
      SHOSH_OOP: `NW18_HIND_PWA/NW18_HIND_LIVETV_PWA/NW18_HIND_LIVETV_PWA_${TAGS}/NW18_HIND_${TAGS}_PWA_ROS_SHOSH_OOP`,
      SKIN_OOP: `NW18_HIND_PWA/NW18_HIND_LIVETV_PWA/NW18_HIND_LIVETV_PWA_${TAGS}/NW18_HIND_${TAGS}_PWA_ROS_SKIN_OOP`,
      PG_1x1_2: `NW18_HIND_PWA/NW18_HIND_LIVETV_PWA/NW18_HIND_LIVETV_PWA_${TAGS}/NW18_HIND_${TAGS}_PWA_ROS_PG_1x1_2`,
      PG_1x1_3: `NW18_HIND_PWA/NW18_HIND_LIVETV_PWA/NW18_HIND_LIVETV_PWA_${TAGS}/NW18_HIND_${TAGS}_PWA_ROS_PG_1x1_3`,
      BAND_TOP_340: `NW18_HIND_PWA/NW18_HIND_LIVETV_PWA/NW18_HIND_LIVETV_PWA_${TAGS}/NW18_HIND_LIVTV_${TAGS}_PWA_ROS_BAND_TOP_340`,
    };
  },
  photoGallery: () => {
    return {
      ATF_320: `NW18_HIND_PWA/NW18_HIND_PHOTO_PWA/NW18_HIND_PHOTO_PWA_AL/NW18_HIND_PHT_AL_PWA_ROS_ATF_320`,
      FBN_320: `NW18_HIND_PWA/NW18_HIND_PHOTO_PWA/NW18_HIND_PHOTO_PWA_AL/NW18_HIND_PHT_AL_PWA_ROS_FBN_320`,
      ATF_300: `NW18_HIND_PWA/NW18_HIND_PHOTO_PWA/NW18_HIND_PHOTO_PWA_AL/NW18_HIND_PHT_AL_PWA_ROS_ATF_300`,
      NAT1: `NW18_HIND_PWA/NW18_HIND_PHOTO_PWA/NW18_HIND_PHOTO_PWA_AL/NW18_HIND_PHT_AL_PWA_ROS_BTF_300`,
      NAT2: `NW18_HIND_PWA/NW18_HIND_PHOTO_PWA/NW18_HIND_PHOTO_PWA_AL/NW18_HIND_PHT_AL_PWA_ROS_BTF_728`,
      NAT3: `NW18_HIND_PWA/NW18_HIND_PHOTO_PWA/NW18_HIND_PHOTO_PWA_AL/NW18_HIND_PHT_AL_PWA_ROS_BTF_728`,
      BTF_300: `NW18_HIND_PWA/NW18_HIND_PHOTO_PWA/NW18_HIND_PHOTO_PWA_AL/NW18_HIND_PHT_AL_PWA_ROS_BTF_300`,
      PG_1x1: `NW18_HIND_PWA/NW18_HIND_PHOTO_PWA/NW18_HIND_PHOTO_PWA_AL/NW18_HIND_AL_PWA_ROS_PG_1x1`,
      PG_Slider_1x1: `NW18_HIND_PWA/NW18_HIND_PHOTO_PWA/NW18_HIND_PHOTO_PWA_AL/NW18_HIND_AL_PWA_ROS_PG_SLIDER_1x1`,
      SHOSH_OOP: `NW18_HIND_PWA/NW18_HIND_PHOTO_PWA/NW18_HIND_PHOTO_PWA_AL/NW18_HIND_AL_PWA_ROS_SHOSH_OOP`,
      SKIN_OOP: `NW18_HIND_PWA/NW18_HIND_PHOTO_PWA/NW18_HIND_PHOTO_PWA_AL/NW18_HIND_AL_PWA_ROS_SKIN_OOP`,
      PG_1x1_2: `NW18_HIND_PWA/NW18_HIND_PHOTO_PWA/NW18_HIND_PHOTO_PWA_AL/NW18_HIND_AL_PWA_ROS_PG_1x1_2`,
      PG_1x1_3: `NW18_HIND_PWA/NW18_HIND_PHOTO_PWA/NW18_HIND_PHOTO_PWA_AL/NW18_HIND_AL_PWA_ROS_PG_1x1_3`,
      PG_1x1_4: `NW18_HIND_PWA/NW18_HIND_PHOTO_PWA/NW18_HIND_PHOTO_PWA_AL/NW18_HIND_PHT_AL_PWA_ROS_PG_1x1_4`,
    };
  },
  cricketLiveScore: () => {
    return {
      header_ATF_320:
        "CRINXT_HIND_PWA/CRINXT_HIND_LIVESCORE_PWA/CRINXT_HIND_LIVESCORE_PWA_AS/CRINXT_HIND_LIVSCR_AS_PWA_ROS_ATF_320",
      ATF_300:
        "CRINXT_HIND_PWA/CRINXT_HIND_LIVESCORE_PWA/CRINXT_HIND_LIVESCORE_PWA_AS/CRINXT_HIND_LIVSCR_AS_PWA_ROS_ATF_300",
      BTF_300:
        "CRINXT_HIND_PWA/CRINXT_HIND_LIVESCORE_PWA/CRINXT_HIND_LIVESCORE_PWA_AS/CRINXT_HIND_LIVSCR_AS_PWA_ROS_BTF_300",
      FBN_320:
        "CRINXT_HIND_PWA/CRINXT_HIND_LIVESCORE_PWA/CRINXT_HIND_LIVESCORE_PWA_AS/CRINXT_HIND_LIVSCR_AS_PWA_ROS_FBN_320",
      SHOSH_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_LIVESCORE_PWA/CRINXT_HIND_LIVESCORE_PWA_AS/CRINXT_HIND_LIVSCR_AS_PWA_ROS_SHOSH_OOP",
      SKIN_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_LIVESCORE_PWA/CRINXT_HIND_LIVESCORE_PWA_AS/CRINXT_HIND_LIVSCR_AS_PWA_ROS_SKIN_OOP",
      PG_1x1:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AS/CRINXT_HIND_ROS_AS_PWA_ROS_PG_1x1",
      PG_Slider_1x1:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AS/CRINXT_HIND_AS_PWA_ROS_PG_Slider_1x1",
    };
  },
  cricketLiveScorePage: () => {
    return {
      header_ATF_320:
        "CRINXT_HIND_PWA/CRINXT_HIND_LIVESCORE_PWA/CRINXT_HIND_LIVESCORE_PWA_AS/CRINXT_HIND_LIVSCR_AS_PWA_ROS_ATF_320",
      ATF_300:
        "CRINXT_HIND_PWA/CRINXT_HIND_LIVESCORE_PWA/CRINXT_HIND_LIVESCORE_PWA_AS/CRINXT_HIND_LIVSCR_AS_PWA_ROS_ATF_300",
      BTF_300:
        "CRINXT_HIND_PWA/CRINXT_HIND_LIVESCORE_PWA/CRINXT_HIND_LIVESCORE_PWA_AS/CRINXT_HIND_LIVSCR_AS_PWA_ROS_BTF_300",
      FBN_320:
        "CRINXT_HIND_PWA/CRINXT_HIND_LIVESCORE_PWA/CRINXT_HIND_LIVESCORE_PWA_AS/CRINXT_HIND_LIVSCR_AS_PWA_ROS_FBN_320",
      SHOSH_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_LIVESCORE_PWA/CRINXT_HIND_LIVESCORE_PWA_AS/CRINXT_HIND_LIVSCR_AS_PWA_ROS_SHOSH_OOP",
      SKIN_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_LIVESCORE_PWA/CRINXT_HIND_LIVESCORE_PWA_AS/CRINXT_HIND_LIVSCR_AS_PWA_ROS_SKIN_OOP",
      PG_1x1:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AS/CRINXT_HIND_ROS_AS_PWA_ROS_PG_1x1",
      PG_1x1_2:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1_2",
      PG_1x1_3:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1_3",
      PG_1x1_4:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1_4",
      PG_Slider_1x1:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AS/CRINXT_HIND_AS_PWA_ROS_PG_Slider_1x1",
      ScoreCard_ad:
        "NW18_HIND_PWA/NW18_HIND_KHEL_PWA/NW18_HIND_KHEL_CRI_PWA_AS/NW18_HIND_KHEL_CRI_AS_PWA_ROS_SCORE_32O",
    };
  },

  cricketNews: () => {
    return {
      header_ATF_320:
        "CRINXT_HIND_PWA/CRINXT_HIND_NEWS_PWA/CRINXT_HIND_NEWS_PWA_AL/CRINXT_HIND_NWS_AL_PWA_ROS_ATF_320",
      ATF_300:
        "CRINXT_HIND_PWA/CRINXT_HIND_NEWS_PWA/CRINXT_HIND_NEWS_PWA_AL/CRINXT_HIND_NWS_AL_PWA_ROS_ATF_300",
      BTF_300:
        "CRINXT_HIND_PWA/CRINXT_HIND_NEWS_PWA/CRINXT_HIND_NEWS_PWA_AL/CRINXT_HIND_NWS_AL_PWA_ROS_BTF_300",
      FBN_320:
        "CRINXT_HIND_PWA/CRINXT_HIND_NEWS_PWA/CRINXT_HIND_NEWS_PWA_AL/CRINXT_HIND_NWS_AL_PWA_ROS_FBN_320",
      SHOSH_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SHOSH_OOP",
      SKIN_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SKIN_OOP",
      PG_1x1:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1",
      PG_Slider_1x1:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_Slider_1x1",
      ScoreCard_ad:
        "NW18_HIND_PWA/NW18_HIND_KHEL_PWA/NW18_HIND_KHEL_CRI_PWA_AS/NW18_HIND_KHEL_CRI_AS_PWA_ROS_SCORE_32O",
    };
  },

  T20WcNews: () => {
    return {
      ATF_320: `CRINXT_HIND_PWA/CRINXT_HIND_IPLT20_PWA/CRINXT_HIND_IPLT20_NEWS_PWA_AL/CRINXT_HIND_IPLT20_NWS_AL_PWA_ROS_ATF_320`,
      ATF_300: `CRINXT_HIND_PWA/CRINXT_HIND_IPLT20_PWA/CRINXT_HIND_IPLT20_NEWS_PWA_AL/CRINXT_HIND_IPLT20_NWS_AL_PWA_ROS_ATF_300`,
      BTF_300: `CRINXT_HIND_PWA/CRINXT_HIND_IPLT20_PWA/CRINXT_HIND_IPLT20_NEWS_PWA_AL/CRINXT_HIND_IPLT20_NWS_AL_PWA_ROS_BTF_300`,
      FBN_320:
        "CRINXT_HIND_PWA/CRINXT_HIND_IPLT20_PWA/CRINXT_HIND_IPLT20_NEWS_PWA_AL/CRINXT_HIND_IPLT20_NWS_AL_PWA_ROS_FBN_320",
      scoreCard_Ad: `NW18_HIND_PWA/NW18_HIND_KHEL_PWA/NW18_HIND_KHEL_CRI_PWA_AS/NW18_HIND_KHEL_CRI_AS_PWA_ROS_SCORE_32O`,
      SKIN_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SKIN_OOP",
      SHOSH_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SHOSH_OOP",
      PG_1x1: `CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1`,
      PG_Slider_1x1: `CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_Slider_1x1`,
    };
  },

  T20WcPointTable: () => {
    return {
      ATF_320: `CRINXT_HIND_PWA/CRINXT_HIND_IPLT20_PWA/CRINXT_HIND_IPLT20_NEWS_PWA_AL/CRINXT_HIND_IPLT20_NWS_AL_PWA_ROS_ATF_320`,
      ATF_300: `CRINXT_HIND_PWA/CRINXT_HIND_IPLT20_PWA/CRINXT_HIND_IPLT20_NEWS_PWA_AL/CRINXT_HIND_IPLT20_NWS_AL_PWA_ROS_ATF_300`,
      BTF_300: `CRINXT_HIND_PWA/CRINXT_HIND_IPLT20_PWA/CRINXT_HIND_IPLT20_NEWS_PWA_AL/CRINXT_HIND_IPLT20_NWS_AL_PWA_ROS_BTF_300`,
      FBN_320:
        "CRINXT_HIND_PWA/CRINXT_HIND_IPLT20_PWA/CRINXT_HIND_IPLT20_NEWS_PWA_AL/CRINXT_HIND_IPLT20_NWS_AL_PWA_ROS_FBN_320",
      scoreCard_Ad: `NW18_HIND_PWA/NW18_HIND_KHEL_PWA/NW18_HIND_KHEL_CRI_PWA_AS/NW18_HIND_KHEL_CRI_AS_PWA_ROS_SCORE_32O`,
      SKIN_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SKIN_OOP",
      SHOSH_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SHOSH_OOP",
      PG_1x1: `CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1`,
      PG_Slider_1x1: `CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_Slider_1x1`,
    };
  },

  T20WcHome: () => {
    return {
      ATF_320: `CRINXT_HIND_PWA/CRINXT_HIND_IPLT20_PWA/CRINXT_HIND_IPLT20_PWA_AL/CRINXT_HIND_IPLT20_AL_PWA_ROS_ATF_320`,
      ATF_300: `CRINXT_HIND_PWA/CRINXT_HIND_IPLT20_PWA/CRINXT_HIND_IPLT20_PWA_AL/CRINXT_HIND_IPLT20_AL_PWA_ROS_ATF_300`,
      BTF_300: `CRINXT_HIND_PWA/CRINXT_HIND_IPLT20_PWA/CRINXT_HIND_IPLT20_PWA_AL/CRINXT_HIND_IPLT20_AL_PWA_ROS_BTF_300`,
      FBN_320:
        "CRINXT_HIND_PWA/CRINXT_HIND_IPLT20_PWA/CRINXT_HIND_IPLT20_PWA_AL/CRINXT_HIND_IPLT20_AL_PWA_ROS_FBN_320",
      scoreCard_Ad: `NW18_HIND_PWA/NW18_HIND_KHEL_PWA/NW18_HIND_KHEL_CRI_PWA_AS/NW18_HIND_KHEL_CRI_AS_PWA_ROS_SCORE_32O`,
      SKIN_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SKIN_OOP",
      SHOSH_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SHOSH_OOP",
      PG_1x1: `CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1`,
      PG_Slider_1x1: `CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_Slider_1x1`,
    };
  },

  T20WcPhoto: () => {
    return {
      ATF_320: `CRINXT_HIND_PWA/CRINXT_HIND_IPLT20_PWA/CRINXT_HIND_IPLT20_PHOTO_PWA_AL/CRINXT_HIND_IPLT20_PHT_AL_PWA_ROS_ATF_320`,
      ATF_300: `CRINXT_HIND_PWA/CRINXT_HIND_IPLT20_PWA/CRINXT_HIND_IPLT20_PHOTO_PWA_AL/CRINXT_HIND_IPLT20_PHT_AL_PWA_ROS_ATF_300`,
      BTF_300: `CRINXT_HIND_PWA/CRINXT_HIND_IPLT20_PWA/CRINXT_HIND_IPLT20_PHOTO_PWA_AL/CRINXT_HIND_IPLT20_PHT_AL_PWA_ROS_BTF_300`,
      FBN_320:
        "CRINXT_HIND_PWA/CRINXT_HIND_IPLT20_PWA/CRINXT_HIND_IPLT20_PHOTO_PWA_AL/CRINXT_HIND_IPLT20_PHT_AL_PWA_ROS_FBN_320",
      scoreCard_Ad: `NW18_HIND_PWA/NW18_HIND_KHEL_PWA/NW18_HIND_KHEL_CRI_PWA_AS/NW18_HIND_KHEL_CRI_AS_PWA_ROS_SCORE_32O`,
      SKIN_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SKIN_OOP",
      SHOSH_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SHOSH_OOP",
      PG_1x1: `CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1`,
      PG_Slider_1x1: `CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_Slider_1x1`,
    };
  },

  cricketVideo: () => {
    return {
      header_ATF_320:
        "CRINXT_HIND_PWA/CRINXT_HIND_VIDEO_PWA/CRINXT_HIND_VIDEO_PWA_AL/CRINXT_HIND_VID_AL_PWA_ROS_ATF_320",
      ATF_300:
        "CRINXT_HIND_PWA/CRINXT_HIND_VIDEO_PWA/CRINXT_HIND_VIDEO_PWA_AL/CRINXT_HIND_VID_AL_PWA_ROS_ATF_300",
      BTF_300:
        "CRINXT_HIND_PWA/CRINXT_HIND_VIDEO_PWA/CRINXT_HIND_VIDEO_PWA_AL/CRINXT_HIND_VID_AL_PWA_ROS_BTF_300",
      FBN_320:
        "CRINXT_HIND_PWA/CRINXT_HIND_VIDEO_PWA/CRINXT_HIND_VIDEO_PWA_AL/CRINXT_HIND_VID_AL_PWA_ROS_FBN_320",
      SHOSH_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SHOSH_OOP",
      SKIN_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SKIN_OOP",
      PG_1x1:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1",
      PG_Slider_1x1:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_Slider_1x1",
      ScoreCard_ad:
        "NW18_HIND_PWA/NW18_HIND_KHEL_PWA/NW18_HIND_KHEL_CRI_PWA_AS/NW18_HIND_KHEL_CRI_AS_PWA_ROS_SCORE_32O",
    };
  },
  cricketHome: () => {
    return {
      header_ATF_320:
        "CRINXT_HIND_PWA/CRINXT_HIND_HOME_PWA/CRINXT_HIND_HOME_PWA/CRINXT_HIND_HP_PWA_HP_ATF_320",
      ATF_300:
        "CRINXT_HIND_PWA/CRINXT_HIND_HOME_PWA/CRINXT_HIND_HOME_PWA/CRINXT_HIND_HP_PWA_HP_ATF_300",
      ATF_320:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_ATF_320",
      BTF_300:
        "CRINXT_HIND_PWA/CRINXT_HIND_HOME_PWA/CRINXT_HIND_HOME_PWA/CRINXT_HIND_HP_PWA_HP_BTF_300",
      FBN_320:
        "CRINXT_HIND_PWA/CRINXT_HIND_HOME_PWA/CRINXT_HIND_HOME_PWA/CRINXT_HIND_HP_PWA_HP_FBN_320",
      SHOSH_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_HOME_PWA/CRINXT_HIND_HOME_PWA/CRINXT_HIND_HP_PWA_HP_SHOSH_OOP",
      SKIN_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_HOME_PWA/CRINXT_HIND_HOME_PWA/CRINXT_HIND_HP_PWA_HP_SKIN_OOP",
      PG_1x1:
        "CRINXT_HIND_PWA/CRINXT_HIND_HOME_PWA/CRINXT_HIND_HOME_PWA/CRINXT_HIND_HP_PWA_HP_PG_1x1",
      PG_Slider_1x1:
        "CRINXT_HIND_PWA/CRINXT_HIND_HOME_PWA/CRINXT_HIND_HOME_PWA/CRINXT_HIND_HP_PWA_HP_PG_Slider_1x1",
      ScoreCard_ad:
        "NW18_HIND_PWA/NW18_HIND_KHEL_PWA/NW18_HIND_KHEL_CRI_PWA_AS/NW18_HIND_KHEL_CRI_AS_PWA_ROS_SCORE_32O",
    };
  },
  silo: (listing = "AL") => {
    return {
      header_ATF_320: `NW18_HIND_PWA/NW18_HIND_INFORMATIONS_PWA/NW18_HIND_INFORMATION_PWA_${listing}/NW18_HIND_INFMTNS_${listing}_PWA_ROS_ATF_320`,
      FBN_320: `NW18_HIND_PWA/NW18_HIND_INFORMATIONS_PWA/NW18_HIND_INFORMATION_PWA_${listing}/NW18_HIND_INFMTNS_${listing}_PWA_ROS_FBN_320`,
      ATF_300: `NW18_HIND_PWA/NW18_HIND_INFORMATIONS_PWA/NW18_HIND_INFORMATION_PWA_${listing}/NW18_HIND_INFMTNS_${listing}_PWA_ROS_ATF_300`,
      BTF_300: `NW18_HIND_PWA/NW18_HIND_INFORMATIONS_PWA/NW18_HIND_INFORMATION_PWA_${listing}/NW18_HIND_INFMTNS_${listing}_PWA_ROS_BTF_300`,
      SHOSH_OOP: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_${listing}/NW18_HIND_${listing}_PWA_ROS_SHOSH_OOP`,
      SKIN_OOP: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_${listing}/NW18_HIND_${listing}_PWA_ROS_SKIN_OOP`,
      PG_Slider_1x1: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_${listing}/NW18_HIND_${listing}_PWA_ROS_PG_SLIDER_1x1`,
      PG_1x1: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_${listing}/NW18_HIND_${listing}_PWA_ROS_PG_1x1`,
      PG_1x1_2: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_${listing}/NW18_HIND_${listing}_PWA_ROS_PG_1x1_2`,
      PG_1x1_3: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_${listing}/NW18_HIND_${listing}_PWA_ROS_PG_1x1_3`,
    };
  },
  podcast: () => {
    return {
      header_ATF_320:
        "NW18_HIND_PWA/NW18_HIND_PODCAST_PWA/NW38_HIND_PODCAST_PWA_AL/NW58_HIND_PDCST_AL_PWA_ROS_ATF_320",
      ATF_300:
        "NW18_HIND_PWA/NW18_HIND_PODCAST_PWA/NW18_HIND_PODCAST_PWA_AL/NW18_HIND_PDCST_AL_PWA_ROS_ATF_300",
      FBN_320:
        "NW18_HIND_PWA/NW18_HIND_PODCAST_PWA/NW18_HIND_PODCAST_PWA_AL/NW18_HIND_PDCST_AL_PWA_ROS_FBN_320",
      SKIN_OOP:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_SKIN_OOP",
      SHOSH_OOP:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_Shosh_OOP",
      PG_1x1:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_PG_1x1",
      PG_1x1_2:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_PG_1x1_2",
      PG_1x1_3:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_PG_1x1_3",
      PG_Slider_1x1:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_PG_SLIDER_1x1",
      ATF_320:
        "NW18_HIND_PWA/NW18_HIND_PODCAST_PWA/NW18_HIND_PODCAST_PWA_AL/NW18_HIND_PDCST_AL_PWA_ROS_ATF_320",
      BTF_300:
        "NW18_HIND_PWA/NW18_HIND_PODCAST_PWA/NW18_HIND_PODCAST_PWA_AL/NW18_HIND_PDCST_AL_PWA_ROS_BTF_300",
    };
  },
  podcastSubCategory: () => {
    return {
      header_ATF_320:
        "NW18_HIND_PWA/NW18_HIND_PODCAST_PWA/NW38_HIND_PODCAST_PWA_AL/NW58_HIND_PDCST_AL_PWA_ROS_ATF_320",
      ATF_320:
        "NW18_HIND_PWA/NW18_HIND_PODCAST_PWA/NW18_HIND_PODCAST_PWA_AL/NW18_HIND_PDCST_AL_PWA_ROS_ATF_320",
      ATF_300:
        "NW18_HIND_PWA/NW18_HIND_PODCAST_PWA/NW18_HIND_PODCAST_PWA_AL/NW18_HIND_PDCST_AL_PWA_ROS_ATF_300",
      FBN_320:
        "NW18_HIND_PWA/NW18_HIND_PODCAST_PWA/NW18_HIND_PODCAST_PWA_AL/NW18_HIND_PDCST_AL_PWA_ROS_FBN_320",
      SKIN_OOP:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_SKIN_OOP",
      SHOSH_OOP:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_Shosh_OOP",
      PG_1x1:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_PG_1x1",
      PG_1x1_2:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_PG_1x1_2",
      PG_1x1_3:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_PG_1x1_3",
    };
  },
  podcastDetails: () => {
    return {
      ATF_320:
        "NW18_HIND_PWA/NW18_HIND_PODCAST_PWA/NW18_HIND_PODCAST_PWA_AS/NW18_HIND_PDCST_AS_PWA_ROS_ATF_320",
      ATF_300:
        "NW18_HIND_PWA/NW18_HIND_PODCAST_PWA/NW18_HIND_PODCAST_PWA_AS/NW18_HIND_PDCST_AS_PWA_ROS_ATF_300",
      FBN_320:
        "NW18_HIND_PWA/NW18_HIND_PODCAST_PWA/NW18_HIND_PODCAST_PWA_AS/NW18_HIND_PDCST_AS_PWA_ROS_FBN_320",
      FBN_300:
        "NW18_HIND_PWA/NW18_HIND_PODCAST_PWA/NW18_HIND_PODCAST_PWA_AS/NW18_HIND_PDCST_AS_PWA_ROS_FBN_300",
      SKIN_OOP:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_SKIN_OOP",
      SHOSH_OOP:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_Shosh_OOP",
      PG_1x1:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_PG_1x1",
      PG_1x1_2:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_PG_1x1_2",
      PG_1x1_3:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_PG_1x1_3",
    };
  },
  cricketPhotos: () => {
    return {
      header_ATF_320:
        "CRINXT_HIND_PWA/CRINXT_HIND_PHOTO_PWA/CRINXT_HIND_PHOTO_PWA_AL/CRINXT_HIND_PHT_AL_PWA_ROS_ATF_320",
      ATF_300:
        "CRINXT_HIND_PWA/CRINXT_HIND_PHOTO_PWA/CRINXT_HIND_PHOTO_PWA_AL/CRINXT_HIND_PHT_AL_PWA_ROS_ATF_300",
      BTF_300:
        "CRINXT_HIND_PWA/CRINXT_HIND_PHOTO_PWA/CRINXT_HIND_PHOTO_PWA_AL/CRINXT_HIND_PHT_AL_PWA_ROS_BTF_300",
      FBN_320:
        "CRINXT_HIND_PWA/CRINXT_HIND_PHOTO_PWA/CRINXT_HIND_PHOTO_PWA_AL/CRINXT_HIND_PHT_AL_PWA_ROS_FBN_320",
      SHOSH_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SHOSH_OOP",
      SKIN_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SKIN_OOP",
      PG_1x1:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1",
      PG_Slider_1x1:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_Slider_1x1",
      ScoreCard_ad:
        "NW18_HIND_PWA/NW18_HIND_KHEL_PWA/NW18_HIND_KHEL_CRI_PWA_AS/NW18_HIND_KHEL_CRI_AS_PWA_ROS_SCORE_32O",
    };
  },
  bitbns: () => {
    return {
      header_ATF_320: `NW18_HIND_PWA/NW18_HIND_CRYPTOCURRENCY_PWA/NW18_HIND_CRYPTOCURRENCY_MARKET_PWA_AL/NW18_HIND_CRYCRY_MKT_AL_PWA_ROS_ATF_320`,
      FBN_320: `NW18_HIND_PWA/NW18_HIND_CRYPTOCURRENCY_PWA/NW18_HIND_CRYPTOCURRENCY_MARKET_PWA_AL/NW18_HIND_CRYCRY_MKT_AL_PWA_ROS_FBN_320`,
      ATF_300: `NW18_HIND_PWA/NW18_HIND_CRYPTOCURRENCY_PWA/NW18_HIND_CRYPTOCURRENCY_MARKET_PWA_AL/NW18_HIND_CRYCRY_MKT_AL_PWA_ROS_ATF_300`,
      BTF_300: `NW18_HIND_PWA/NW18_HIND_CRYPTOCURRENCY_PWA/NW18_HIND_CRYPTOCURRENCY_MARKET_PWA_AL/NW18_HIND_CRYCRY_MKT_AL_PWA_ROS_BTF_300`,
      // SHOSH_OOP: "NW18_HIND_PWA/NW18_HIND_HOME_PWA/NW18_HIND_HOME_HOME_PWA/NW18_HIND_PWA_HP_Shosh_OOP",
      // SKIN_OOP: "NW18_HIND_PWA/NW18_HIND_HOME_PWA/NW18_HIND_HOME_HOME_PWA/NW18_HIND_PWA_HP_SKIN_OOP",
      // PG_Slider_1x1: "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_PG_1x1",
    };
  },
  bitbnscoins: () => {
    return {
      header_ATF_320: `NW18_HIND_PWA/NW18_HIND_CRYPTOCURRENCY_PWA/NW18_HIND_CRYPTOCURRENCY_GRAPH_PWA_AL/NW18_HIND_CRYCRY_GRAPH_AL_PWA_ROS_ATF_320`,
      FBN_320: `NW18_HIND_PWA/NW18_HIND_CRYPTOCURRENCY_PWA/NW18_HIND_CRYPTOCURRENCY_GRAPH_PWA_AL/NW18_HIND_CRYCRY_GRAPH_AL_PWA_ROS_FBN_320`,
      ATF_300: `NW18_HIND_PWA/NW18_HIND_CRYPTOCURRENCY_PWA/NW18_HIND_CRYPTOCURRENCY_GRAPH_PWA_AL/NW18_HIND_CRYCRY_GRAPH_AL_PWA_ROS_ATF_300`,
      BTF_300: `NW18_HIND_PWA/NW18_HIND_CRYPTOCURRENCY_PWA/NW18_HIND_CRYPTOCURRENCY_GRAPH_PWA_AL/NW18_HIND_CRYCRY_GRAPH_AL_PWA_ROS_BTF_300`,
      // SHOSH_OOP: "NW18_HIND_PWA/NW18_HIND_HOME_PWA/NW18_HIND_HOME_HOME_PWA/NW18_HIND_PWA_HP_Shosh_OOP",
      // SKIN_OOP: "NW18_HIND_PWA/NW18_HIND_HOME_PWA/NW18_HIND_HOME_HOME_PWA/NW18_HIND_PWA_HP_SKIN_OOP",
      // PG_Slider_1x1: "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_PG_1x1",
    };
  },

  dataPages: () => {
    return {
      header_ATF_320: `NW18_HIND_PWA/NW18_HIND_MOBILE_PWA/NW18_HIND_MOBILE_PWA_AL/NW18_HIND_MOB_AL_PWA_ROS_ATF_320`,
      FBN_320: `NW18_HIND_PWA/NW18_HIND_MOBILE_PWA/NW18_HIND_MOBILE_PWA_AL/NW18_HIND_MOB_AL_PWA_ROS_FBN_320`,
      ATF_300: `NW18_HIND_PWA/NW18_HIND_MOBILE_PWA/NW18_HIND_MOBILE_PWA_AL/NW18_HIND_MOB_AL_PWA_ROS_ATF_300`,
      BTF_300: `NW18_HIND_PWA/NW18_HIND_MOBILE_PWA/NW18_HIND_MOBILE_PWA_AL/NW18_HIND_MOB_AL_PWA_ROS_BTF_300`,
      SHOSH_OOP:
        "NW18_HIND_PWA/NW18_HIND_HOME_PWA/NW18_HIND_HOME_HOME_PWA/NW18_HIND_PWA_HP_Shosh_OOP",
      SKIN_OOP:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_SKIN_OOP",
      PG_Slider_1x1:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_PG_SLIDER_1x1",
      PG_1x1:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_PG_1x1",
      PG_1x1_2:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_PG_1x1_2",
      PG_1x1_3:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_PG_1x1_3",
    };
  },

  aqi: () => {
    return {
      header_ATF_320: `NW18_HIND_PWA/NW18_HIND_AQI_INDIA_PWA/NW18_HIND_AQI_INDIA_PWA_AL/NW18_HIND_AQI_IND_AL_PWA_ROS_ATF_320`,
      FBN_320: `NW18_HIND_PWA/NW18_HIND_AQI_INDIA_PWA/NW18_HIND_AQI_INDIA_PWA_AL/NW18_HIND_AQI_IND_AL_PWA_ROS_FBN_320`,
      ATF_300: `NW18_HIND_PWA/NW18_HIND_AQI_INDIA_PWA/NW18_HIND_AQI_INDIA_PWA_AL/NW18_HIND_AQI_IND_AL_PWA_ROS_ATF_300`,
      BTF_300: `NW18_HIND_PWA/NW18_HIND_AQI_INDIA_PWA/NW18_HIND_AQI_INDIA_PWA_AL/NW18_HIND_AQI_IND_AL_PWA_ROS_BTF_300`,
      SHOSH_OOP:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_SHOSH_OOP",
      SKIN_OOP:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_SKIN_OOP",
      PG_Slider_1x1:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_PG_SLIDER_1x1",
      PG_1x1:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_PG_1x1",
      PG_1x1_2:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_PG_1x1_2",
      PG_1x1_3:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_PG_1x1_3",
    };
  },
  blogs: (targetType) => {
    const targetCode = targetType === "listing" ? "AL" : "AS";
    return {
      ATF_320: `NW18_HIND_PWA/NW18_HIND_BLOG_PWA/NW18_HIND_BLOG_PWA_${targetCode}/NW18_HIND_BLG_${targetCode}_PWA_ROS_ATF_320`,
      ATF_300_id: `NW18_HIND_PWA/NW18_HIND_BLOG_PWA/NW18_HIND_BLOG_PWA_${targetCode}/NW18_HIND_BLG_${targetCode}_PWA_ROS_ATF_300`,
      BTF_300_id: `NW18_HIND_PWA/NW18_HIND_BLOG_PWA/NW18_HIND_BLOG_PWA_${targetCode}/NW18_HIND_BLG_${targetCode}_PWA_ROS_BTF_300`,
      FBN_320: `NW18_HIND_PWA/NW18_HIND_BLOG_PWA/NW18_HIND_BLOG_PWA_${targetCode}/NW18_HIND_BLG_${targetCode}_PWA_ROS_FBN_320`,
      SHOSH_OOP: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_${targetCode}/NW18_HIND_${targetCode}_PWA_ROS_Shosh_OOP`,
      SKIN_OOP: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_${targetCode}/NW18_HIND_${targetCode}_PWA_ROS_SKIN_OOP`,
      PG_1x1: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_${targetCode}/NW18_HIND_${targetCode}_PWA_ROS_PG_1x1`,
      PG_1x1_2: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_${targetCode}/NW18_HIND_${targetCode}_PWA_ROS_PG_1x1_2`,
      PG_1x1_3: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_${targetCode}/NW18_HIND_${targetCode}_PWA_ROS_PG_1x1_3`,
      PG_Slider_1x1: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_${targetCode}/NW18_HIND_${targetCode}_PWA_ROS_PG_1x1`,
    };
  },
  shortvideos: (targetType) => {
    const targetCode = targetType === "listing" ? "AL" : "AS";
    return {
      ATF_320: `NW18_HIND_PWA/NW18_HIND_SHORTS_VIDEO_PWA/NW18_HIND_SHORT_VIDEO_PWA_${targetCode}/NW18_HIND_SHRTS_VDO_${targetCode}_PWA_ROS_ATF_320`,
      FBN_320: `NW18_HIND_PWA/NW18_HIND_SHORTS_VIDEO_PWA/NW18_HIND_SHORT_VIDEO_PWA_${targetCode}/NW18_HIND_SHRTS_VDO_${targetCode}_PWA_ROS_FBN_320`,
      ATF_300_id: `NW18_HIND_PWA/NW18_HIND_SHORTS_VIDEO_PWA/NW18_HIND_SHORT_VIDEO_PWA_${targetCode}/NW18_HIND_SHRTS_VDO_${targetCode}_PWA_ROS_ATF_300`,
      BTF_300_id: `NW18_HIND_PWA/NW18_HIND_SHORTS_VIDEO_PWA/NW18_HIND_SHORT_VIDEO_PWA_${targetCode}/NW18_HIND_SHRTS_VDO_${targetCode}_PWA_ROS_BTF_300`,
      Shosh_OOP_id: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_${targetCode}/NW18_HIND_${targetCode}_PWA_ROS_SHOSH_OOP`,
      Skin_OOP_id: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_${targetCode}/NW18_HIND_${targetCode}_PWA_ROS_SKIN_OOP`,
      PG_1x1: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_${targetCode}/NW18_HIND_${targetCode}_PWA_ROS_PG_1x1`,
      PG_Slider_1x1: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_${targetCode}/NW18_HIND_${targetCode}_PWA_ROS_PG_SLIDER_1x1`,
    };
  },

  cricketMatchSchedule: () => {
    return {
      ATF_320:
        "CRINXT_HIND_PWA/CRINXT_HIND_SCHEDULE_PWA/CRINXT_HIND_SCHEDULE_PWA_AL/CRINXT_HIND_SDLE_AL_PWA_ROS_ATF_320",
      FBN_320:
        "CRINXT_HIND_PWA/CRINXT_HIND_SCHEDULE_PWA/CRINXT_HIND_SCHEDULE_PWA_AL/CRINXT_HIND_SDLE_AL_PWA_ROS_FBN_320",
      BTF_300:
        "CRINXT_HIND_PWA/CRINXT_HIND_SCHEDULE_PWA/CRINXT_HIND_SCHEDULE_PWA_AL/CRINXT_HIND_SDLE_AL_PWA_ROS_BTF_300",
      SHOSH_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SHOSH_OOP",
      SKIN_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SKIN_OOP",
      PG_1x1:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1",
      PG_1x1_2:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1_2",
      PG_1x1_3:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1_3",
      PG_1x1_4:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1_4",
      PG_Slider_1x1:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_Slider_1x1",
      ScoreCard_ad:
        "NW18_HIND_PWA/NW18_HIND_KHEL_PWA/NW18_HIND_KHEL_CRI_PWA_AS/NW18_HIND_KHEL_CRI_AS_PWA_ROS_SCORE_32O",
    };
  },
  cricketPlayerProfile: () => {
    return {
      ATF_320:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_ATF_320",
      ATF_300:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_ATF_300",
      FBN_320:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_FBN_320",
      BTF_300:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_BTF_300",
      SHOSH_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SHOSH_OOP",
      SKIN_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SKIN_OOP",
      PG_1x1:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1",
      PG_1x1_2:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1_2",
      PG_1x1_3:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1_3",
      PG_1x1_4:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1_4",
      PG_Slider_1x1:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_Slider_1x1",
      ScoreCard_ad:
        "NW18_HIND_PWA/NW18_HIND_KHEL_PWA/NW18_HIND_KHEL_CRI_PWA_AS/NW18_HIND_KHEL_CRI_AS_PWA_ROS_SCORE_32O",
    };
  },
  cricketRankings: () => {
    return {
      ATF_320:
        "CRINXT_HIND_PWA/CRINXT_HIND_RANKING_PWA/CRINXT_HIND_RANKING_PWA_AL/RINXT_HIND_RNKG_AL_PWA_ROS_ATF_320",
      BTF_300:
        "CRINXT_HIND_PWA/CRINXT_HIND_RANKING_PWA/CRINXT_HIND_RANKING_PWA_AL/CRINXT_HIND_RNKG_AL_PWA_ROS_BTF_300",
      FBN_320:
        "CRINXT_HIND_PWA/CRINXT_HIND_RANKING_PWA/CRINXT_HIND_RANKING_PWA_AL/CRINXT_HIND_RNKG_AL_PWA_ROS_FBN_320",
      SKIN_OOP:
        " CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SKIN_OOP",
      SHOSH_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SHOSH_OOP",
      PG_1x1:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1",
      PG_Slider_1x1:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_Slider_1x1",
      PG_1x1_2:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1_2",
      PG_1x1_3:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1_3",
      PG_1x1_4:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1_4",
      ScoreCard_ad:
        " NW18_HIND_PWA/NW18_HIND_KHEL_PWA/NW18_HIND_KHEL_CRI_PWA_AS/NW18_HIND_KHEL_CRI_AS_PWA_ROS_SCORE_32O",
    };
  },
  cricketResult: () => {
    return {
      ATF_320:
        "CRINXT_HIND_PWA/CRINXT_HIND_RESULT_PWA/CRINXT_HIND_RESULT_PWA_AL/CRINXT_HIND_RSLT_AL_PWA_ROS_ATF_320",
      FBN_320:
        "CRINXT_HIND_PWA/CRINXT_HIND_RESULT_PWA/CRINXT_HIND_RESULT_PWA_AL/CRINXT_HIND_RSLT_AL_PWA_ROS_FBN_320",
      ATF_300:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_ATF_300",
      BTF_300:
        "CRINXT_HIND_PWA/CRINXT_HIND_RESULT_PWA/CRINXT_HIND_RESULT_PWA_AL/CRINXT_HIND_RSLT_AL_PWA_ROS_BTF_300",
      SHOSH_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SHOSH_OOP",
      SKIN_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SKIN_OOP",
      PG_1x1:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1",
      PG_1x1_2:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_1x1_2", // Not on live old stack
      PG_1x1_3:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_1x1_3", //Not on live old stack
      PG_1x1_4:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1_4",
      PG_Slider_1x1:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_Slider_1x1",
      ScoreCard_ad:
        "NW18_HIND_PWA/NW18_HIND_KHEL_PWA/NW18_HIND_KHEL_CRI_PWA_AS/NW18_HIND_KHEL_CRI_AS_PWA_ROS_SCORE_32O",
    };
  },
  cricketSeries: (slotName, slotShortName, target) => {
    return {
      ATF_320: `CRINXT_HIND_PWA/CRINXT_HIND_${slotName}_PWA/CRINXT_HIND_${slotName}_PWA_${target}/CRINXT_HIND_${slotShortName}_AL_PWA_ROS_ATF_320`,
      ATF_300: `CRINXT_HIND_PWA/CRINXT_HIND_${slotName}_PWA/CRINXT_HIND_${slotName}_PWA_${target}/CRINXT_HIND_${slotShortName}_AL_PWA_ROS_ATF_300`,
      FBN_320: `CRINXT_HIND_PWA/CRINXT_HIND_${slotName}_PWA/CRINXT_HIND_${slotName}_PWA_${target}/CRINXT_HIND_${slotShortName}_AL_PWA_ROS_FBN_320`,
      BTF_300: `CRINXT_HIND_PWA/CRINXT_HIND_${slotName}_PWA/CRINXT_HIND_${slotName}_PWA_${target}/CRINXT_HIND_${slotShortName}_AL_PWA_ROS_BTF_300`,
      SHOSH_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SHOSH_OOP",
      SKIN_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SKIN_OOP",
      PG_1x1:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1",
      PG_1x1_2:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1_2",
      PG_1x1_3:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1_3",
      PG_1x1_4:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1_4",
      PG_Slider_1x1:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_Slider_1x1",
      ScoreCard_ad:
        "NW18_HIND_PWA/NW18_HIND_KHEL_PWA/NW18_HIND_KHEL_CRI_PWA_AS/NW18_HIND_KHEL_CRI_AS_PWA_ROS_SCORE_32O",
    };
  },
  budget: () => {
    return {
      ATF_320_0: `NW18_HIND_PWA/NW18_HIND_BUDGET_PWA/NW18_HIND_BUDGET_HOME_PWA/NW18_HIND_BDGT_PWA_HP_ATF_320`,
      BTF_300_id:
        "NW18_HIND_PWA/NW18_HIND_BUDGET_PWA/NW18_HIND_BUDGET_HOME_PWA/NW18_HIND_BDGT_PWA_HP_BTF_300",
      ATF_300:
        "NW18_HIND_PWA/NW18_HIND_BUDGET_PWA/NW18_HIND_BUDGET_HOME_PWA/NW18_HIND_BDGT_PWA_HP_ATF_300",
      MTF_728_0:
        "NW18_HIND_PWA/NW18_HIND_BUDGET_PWA/NW18_HIND_BUDGET_HOME_PWA/NW18_HIND_BDGT_PWA_HP_MTF_728",
      SHOSH_OOP:
        "NW18_HIND_PWA/NW18_HIND_BUDGET_PWA/NW18_HIND_BUDGET_HOME_PWA/NW18_HIND_BDGT_PWA_HP_SHOSH_OOP",
      SKIN_OOP:
        "NW18_HIND_PWA/NW18_HIND_BUDGET_PWA/NW18_HIND_BUDGET_HOME_PWA/NW18_HIND_BDGT_PWA_HP_SKIN_OOP",
      PG_1x1:
        "NW18_HIND_PWA/NW18_HIND_BUDGET_PWA/NW18_HIND_BUDGET_HOME_PWA/NW18_HIND_BDGT_PWA_HP_PG_1x1",
      PG_1x1_2:
        "NW18_HIND_PWA/NW18_HIND_BUDGET_PWA/NW18_HIND_BUDGET_HOME_PWA/NW18_HIND_BDGT_PWA_HP_PG_1x1_2",
      PG_1x1_3:
        "NW18_HIND_PWA/NW18_HIND_BUDGET_PWA/NW18_HIND_BUDGET_HOME_PWA/NW18_HIND_BDGT_PWA_HP_PG_1x1_3",
      PG_1x1_4:
        "NW18_HIND_PWA/NW18_HIND_BUDGET_PWA/NW18_HIND_BUDGET_HOME_PWA/NW18_HIND_BDGT_PWA_HP_PG_1x1_4",
      PG_Slider_1x1:
        "NW18_HIND_PWA/NW18_HIND_BUDGET_PWA/NW18_HIND_BUDGET_HOME_PWA/NW18_HIND_BDGT_PWA_HP_PG_Slider_1x1",
      FBN_320:
        "NW18_HIND_PWA/NW18_HIND_BUDGET_PWA/NW18_HIND_BUDGET_HOME_PWA/NW18_HIND_BDGT_PWA_HP_FBN_320",
      companion_banner:
        "NW18_HIND_PWA/NW18_HIND_HOME_EVENT_PWA/NW18_HIND_HOME_HOME_EVENT_PWA/NW18_HIND_EVNT_PWA_HP_ROS_EVENT_TOP_320x60"
    };
  },
  minis: () => {
    return {
      ATF_320:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_ATF_320",
      FBN_320:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_FBN_320",
      BTF_300:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_BTF_300",
      SHOSH_OOP:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_SHOSH_OOP",
      SKIN_OOP:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_SKIN_OOP",
      PG_Slider_1x1:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_PG_SLIDER_1x1",
      PG_1x1:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_PG_1x1",
      PG_1x1_2:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_PG_1x1_2",
      PG_1x1_3:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_PG_1x1_3",
    };
  },
  staticPagesMobile: () => {
    return {
      ATF_320: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_ATF_320`,
      ATF_300: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_ATF_300`,
      BTF_300: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_BTF_300`,
      FBN_320: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_FBN_320`,
      FLY_300: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_FLY_300`,
      SKIN_OOP: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_SKIN_OOP`,
      SHOSH_OOP: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_Shosh_OOP`,
      PG_1x1: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_PG_1x1`,
      PG_1x1_2: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_PG_1x1_2`,
      PG_1x1_3: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_PG_1x1_3`,
    };
  },
  boardresult: () => {
    return {
      ATF_320_0: `NW18_HIND_PWA/NW18_HIND_BOARDRESULT_PWA/NW18_HIND_BOARDRESULT_PWA_AS/NW18_HIND_BRDRST_AS_PWA_ROS_ATF_320`,
      BTF_300_id:
        "NW18_HIND_PWA/NW18_HIND_BOARDRESULT_PWA/NW18_HIND_BOARDRESULT_PWA_AS/NW18_HIND_BRDRST_AS_PWA_ROS_BTF_300",
      ATF_300:
        "NW18_HIND_PWA/NW18_HIND_BOARDRESULT_PWA/NW18_HIND_BOARDRESULT_PWA_AS/NW18_HIND_BRDRST_AS_PWA_ROS_ATF_300",
      MTF_728_0: "",
      PG_1x1_4: "",
      FBN_320: "",
      SHOSH_OOP:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_SHOSH_OOP",
      SKIN_OOP:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_SKIN_OOP",
      PG_Slider_1x1:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_PG_SLIDER_1x1",
      PG_1x1:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_PG_1x1",
      PG_1x1_2:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_PG_1x1_2",
      PG_1x1_3:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_PG_1x1_3",
    };
  },
  IPLPage: () => {
    return {
      ATF_320: `NW18_HIND_PWA/NW18_HIND_IPLT20_PWA/NW18_HIND_IPLT20_PWA_AL/NW18_HIND_IPLT20_AL_PWA_ROS_ATF_320`,
      ATF_300: `NW18_HIND_PWA/NW18_HIND_IPLT20_PWA/NW18_HIND_IPLT20_PWA_AL/NW18_HIND_IPLT20_AL_PWA_ROS_ATF_300`,
      BTF_300: `NW18_HIND_PWA/NW18_HIND_IPLT20_PWA/NW18_HIND_IPLT20_PWA_AL/NW18_HIND_IPLT20_AL_PWA_ROS_BTF_300`,
      FBN_320: `NW18_HIND_PWA/NW18_HIND_IPLT20_PWA/NW18_HIND_IPLT20_PWA_AL/NW18_HIND_IPLT20_AL_PWA_ROS_FBN_320`,
      FLY_300: `NW18_HIND_PWA/NW18_HIND_IPLT20_PWA/NW18_HIND_IPLT20_PWA_AL/NW18_HIND_IPLT20_AL_PWA_ROS_FLY_300`,
      SKIN_OOP: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_SKIN_OOP`,
      SHOSH_OOP: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_Shosh_OOP`,
      PG_1x1: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA/NW18_HIND_AS_PWA_ROS_PG_1x1`,
      PG_1x1_2: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_PG_1x1_2`,
      PG_1x1_3: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_PG_1x1_3`,
      PG_SLIDER_1x1: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_PG_SLIDER_1x1`,
      ScoreCard_ad: `NW18_HIND_PWA/NW18_HIND_KHEL_PWA/NW18_HIND_KHEL_CRI_PWA_AS/NW18_HIND_KHEL_CRI_AS_PWA_ROS_SCORE_32O`,
    };
  },
  webstory: () => {
    return {
      ATF_320: `NW18_HIND_PWA/NW18_HIND_WEB_STORIES_PWA/NW18_HIND_WEB_STORIES_PWA_AL/NW18_HIND_WEB_STRYS_AL_PWA_ROS_ATF_320`,
      ATF_300: `NW18_HIND_PWA/NW18_HIND_WEB_STORIES_PWA/NW18_HIND_WEB_STORIES_PWA_AL/NW18_HIND_WEB_STRYS_AL_PWA_ROS_ATF_300`,
      BTF_300: `NW18_HIND_PWA/NW18_HIND_WEB_STORIES_PWA/NW18_HIND_WEB_STORIES_PWA_AL/NW18_HIND_WEB_STRYS_AL_PWA_ROS_BTF_300`,
      FBN_320: `NW18_HIND_PWA/NW18_HIND_WEB_STORIES_PWA/NW18_HIND_WEB_STORIES_PWA_AL/NW18_HIND_WEB_STRYS_AL_PWA_ROS_FBN_320`,
      SHOSH_OOP: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_SHOSH_OOP`,
      SKIN_OOP: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_SKIN_OOP`,
      PG_1x1: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_PG_1x1`,
      PG_Slider_1x1: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_PG_Slider_1x1`,
    };
  },
  isInfographics: () => {
    return {
      ATF_320: `NW18_HIND_PWA/NW18_HIND_PHOTO_PWA/NW18_HIND_PHOTO_STORIES_PWA_AS/NW18_HIND_PHT_STRYS_AS_PWA_ROS_ATF_320`,
      ATF_300: `NW18_HIND_PWA/NW18_HIND_PHOTO_PWA/NW18_HIND_PHOTO_STORIES_PWA_AS/NW18_HIND_PHT_STRYS_AS_PWA_ROS_ATF_300`,
      BTF_300: `NW18_HIND_PWA/NW18_HIND_PHOTO_PWA/NW18_HIND_PHOTO_STORIES_PWA_AS/NW18_HIND_PHT_STRYS_AS_PWA_ROS_BTF_300`,
      FBN_320: `NW18_HIND_PWA/NW18_HIND_PHOTO_PWA/NW18_HIND_PHOTO_STORIES_PWA_AS/NW18_HIND_PHT_STRYS_AS_PWA_ROS_FBN_320`,
      SHOSH_OOP: `NW18_HIND_PWA/NW18_HIND_PHOTO_PWA/NW18_HIND_PHOTO_STORIES_PWA_AS/NW18_HIND_AS_PWA_ROS_SHOSH_OOP`,
      SKIN_OOP: `NW18_HIND_PWA/NW18_HIND_PHOTO_PWA/NW18_HIND_PHOTO_STORIES_PWA_AS/NW18_HIND_AS_PWA_ROS_SKIN_OOP`,
      PG_1x1: `NW18_HIND_PWA/NW18_HIND_PHOTO_PWA/NW18_HIND_PHOTO_STORIES_PWA_AS/NW18_HIND_AS_PWA_ROS_PG_1x1`,
      PG_Slider_1x1: `NW18_HIND_PWA/NW18_HIND_PHOTO_PWA/NW18_HIND_PHOTO_STORIES_PWA_AS/NW18_HIND_AS_PWA_ROS_PG_SLIDER_1x1`,
      PG_1x1_2: ``,
      PG_1x1_3: ``,
    };
  },

  ProKabaddi: () => {
    return {
      ATF_320: `NW18_HIND_PWA/NW18_HIND_KHEL_PWA/NW18_HIND_KHEL_PWA_AL/NW18_HIND_KHEL_AL_PWA_ROS_ATF_320`,
      ATF_300: `NW18_HIND_PWA/NW18_HIND_KHEL_PWA/NW18_HIND_KHEL_PWA_AL/NW18_HIND_KHEL_AL_PWA_ROS_ATF_300`,
      BTF_300: `NW18_HIND_PWA/NW18_HIND_KHEL_PWA/NW18_HIND_KHEL_PWA_AL/NW18_HIND_KHEL_AL_PWA_ROS_BTF_300`,
      FBN_320: `NW18_HIND_PWA/NW18_HIND_KHEL_PWA/NW18_HIND_KHEL_PWA_AL/NW18_HIND_KHEL_AL_PWA_ROS_FBN_320`,
    };
  },

  liveblog: () => {
    return {
      header_ATF_320: `NW18_HIND_PWA/NW18_HIND_LIVEBLOG_PWA/NW18_HIND_LIVEBLOG_PWA_AS/NW18_HIND_LIVBLG_AS_PWA_ROS_ATF_320`,
      ATF_300: `NW18_HIND_PWA/NW18_HIND_LIVEBLOG_PWA/NW18_HIND_LIVEBLOG_PWA_AS/NW18_HIND_LIVBLG_AS_PWA_ROS_ATF_300`,
      BTF_300: `NW18_HIND_PWA/NW18_HIND_LIVEBLOG_PWA/NW18_HIND_LIVEBLOG_PWA_AS/NW18_HIND_LIVBLG_AS_PWA_ROS_BTF_300`,
      FBN_320: `NW18_HIND_PWA/NW18_HIND_LIVEBLOG_PWA/NW18_HIND_LIVEBLOG_PWA_AS/NW18_HIND_LIVBLG_AS_PWA_ROS_FBN_320`,
      PG_1x1: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_PG_1x1`,
      PG_Slider_1x1: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_PG_SLIDER_1x1`,
      SHOSH_OOP: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_SHOSH_OOP`,
      SKIN_OOP: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_SKIN_OOP`,
      PG_1x1_2: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_PG_1x1_2`,
      PG_1x1_3: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_PG_1x1_3`,
      PG_1x1_4:
        "NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_PG_1x1_4",
    };
  },

  rammandir: () => {
    return {
      header_ATF_320: `NW18_HIND_PWA/NW18_HIND_EVENT_PWA/NW18_HIND_EVENT_PWA_AL/NW18_HIND_EVNT_AL_PWA_ROS_ATF_320x60`,
      ATF_300: `NW18_HIND_PWA/NW18_HIND_EVENT_PWA/NW18_HIND_EVENT_PWA_AL/NW18_HIND_EVNT_AL_PWA_ROS_ATF_300`,
      BTF_300: `NW18_HIND_PWA/NW18_HIND_EVENT_PWA/NW18_HIND_EVENT_PWA_AL/NW18_HIND_EVNT_AL_PWA_ROS_BTF_300`,
      MID_300: `NW18_HIND_PWA/NW18_HIND_EVENT_PWA/NW18_HIND_EVENT_PWA_AL/NW18_HIND_EVNT_AL_PWA_ROS_MID_300`,
      MTF_300: `NW18_HIND_PWA/NW18_HIND_EVENT_PWA/NW18_HIND_EVENT_PWA_AL/NW18_HIND_EVNT_AL_PWA_ROS_MTF_300`,
      FBN_320: `NW18_HIND_PWA/NW18_HIND_EVENT_PWA/NW18_HIND_EVENT_PWA_AL/NW18_HIND_EVNT_AL_PWA_ROS_FBN_320`,
      SHOSH_OOP: `NW18_HIND_PWA/NW18_HIND_EVENT_PWA/NW18_HIND_EVENT_PWA_AL/NW18_HIND_EVNT_AL_PWA_ROS_SHOSH_OOP`,
      SKIN_OOP: `NW18_HIND_PWA/NW18_HIND_EVENT_PWA/NW18_HIND_EVENT_PWA_AL/NW18_HIND_EVNT_AL_PWA_ROS_SKIN_OOP`,
      PG_1x1_2: `NW18_HIND_PWA/NW18_HIND_EVENT_PWA/NW18_HIND_EVENT_PWA_AL/NW18_HIND_EVNT_AL_PWA_ROS_PG_1x1_2`,
      PG_1x1_3: `NW18_HIND_PWA/NW18_HIND_EVENT_PWA/NW18_HIND_EVENT_PWA_AL/NW18_HIND_EVNT_AL_PWA_ROS_PG_1x1_3`,
      PG_1x1_4:
        "NW18_HIND_PWA/NW18_HIND_EVENT_PWA/NW18_HIND_EVENT_PWA_AL/NW18_HIND_EVNT_AL_PWA_ROS_PG_1x1_4",
      PG_1x1: `NW18_HIND_PWA/NW18_HIND_EVENT_PWA/NW18_HIND_EVENT_PWA_AL/NW18_HIND_EVNT_AL_PWA_ROS_PG_1x1`,
      PG_Slider_1x1: `NW18_HIND_PWA/NW18_HIND_EVENT_PWA/NW18_HIND_EVENT_PWA_AL/NW18_HIND_EVNT_AL_PWA_ROS_PG_SLIDER_1x1`,
      companion_banner: `NW18_HIND_PWA/NW18_HIND_EVENT_PWA/NW18_HIND_EVENT_PWA_AL/NW18_HIND_EVNT_SPONSOR_TOP_STRIP_320x60`,
    };
  },
  boardResultLanding: () => {
    return {
      header_ATF_320: `NW18_HIND_PWA/NW18_HIND_BOARDRESULT_PWA/NW18_HIND_BOARDRESULT_PWA_AL/NW18_HIND_BRDRSLT_AL_PWA_ROS_ATF_320`,
      ATF_300: `NW18_HIND_PWA/NW18_HIND_BOARDRESULT_PWA/NW18_HIND_BOARDRESULT_PWA_AL/NW18_HIND_BRDRSLT_AL_PWA_ROS_ATF_300`,
      BTF_300: `NW18_HIND_PWA/NW18_HIND_BOARDRESULT_PWA/NW18_HIND_BOARDRESULT_PWA_AL/NW18_HIND_BRDRSLT_AL_PWA_ROS_BTF_300`,      
      MTF_300: `NW18_HIND_PWA/NW18_HIND_EVENT_PWA/NW18_HIND_EVENT_PWA_AL/NW18_HIND_EVNT_AL_PWA_ROS_MTF_300`,
      FBN_320: `NW18_HIND_PWA/NW18_HIND_BOARDRESULT_PWA/NW18_HIND_BOARDRESULT_PWA_AL/NW18_HIND_BRDRSLT_AL_PWA_ROS_FBN_320`,
    };
  },
  boardResultConsum: () => {
    return {
      header_ATF_320: `NW18_HIND_PWA/NW18_HIND_BOARDRESULT_PWA/NW18_HIND_BOARDRESULT_PWA_AS/NW18_HIND_BRDRSLT_AS_PWA_ROS_ATF_320`,
      ATF_300: `NW18_HIND_PWA/NW18_HIND_BOARDRESULT_PWA/NW18_HIND_BOARDRESULT_PWA_AS/NW18_HIND_BRDRSLT_AS_PWA_ROS_ATF_300`,
      BTF_300: `NW18_HIND_PWA/NW18_HIND_BOARDRESULT_PWA/NW18_HIND_BOARDRESULT_PWA_AS/NW18_HIND_BRDRSLT_AS_PWA_ROS_BTF_300`,      
      MTF_300: `NW18_HIND_PWA/NW18_HIND_BOARDRESULT_PWA/NW18_HIND_BOARDRESULT_PWA_AS/NW18_HIND_BRDRSLT_AS_PWA_ROS_MTF_300`,
      FBN_320: `NW18_HIND_PWA/NW18_HIND_BOARDRESULT_PWA/NW18_HIND_BOARDRESULT_PWA_AS/NW18_HIND_BRDRSLT_AS_PWA_ROS_FBN_320`,
    };
  },
  T20WC_MR_MW_P: () => {
    return {
      ATF_320:
        "CRINXT_HIND_PWA/CRINXT_HIND_IPLT20_PWA/CRINXT_HIND_IPLT20_PWA_AL/CRINXT_HIND_IPLT20_AL_PWA_ROS_ATF_320",
      ATF_300:
        "CRINXT_HIND_PWA/CRINXT_HIND_IPLT20_PWA/CRINXT_HIND_IPLT20_PWA_AL/CRINXT_HIND_IPLT20_AL_PWA_ROS_ATF_300",
      FBN_320:
        "CRINXT_HIND_PWA/CRINXT_HIND_IPLT20_PWA/CRINXT_HIND_IPLT20_PWA_AL/CRINXT_HIND_IPLT20_AL_PWA_ROS_FBN_320",
      BTF_300:
        "CRINXT_HIND_PWA/CRINXT_HIND_IPLT20_PWA/CRINXT_HIND_IPLT20_PWA_AL/CRINXT_HIND_IPLT20_AL_PWA_ROS_BTF_300",
      SHOSH_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SHOSH_OOP",
      SKIN_OOP:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SKIN_OOP",
      PG_1x1:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1",
      PG_1x1_2:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1_2",
      PG_1x1_3:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1_3",
      PG_1x1_4:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1_4",
      PG_Slider_1x1:
        "CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_Slider_1x1",
      ScoreCard_ad:
        "NW18_HIND_PWA/NW18_HIND_KHEL_PWA/NW18_HIND_KHEL_CRI_PWA_AS/NW18_HIND_KHEL_CRI_AS_PWA_ROS_SCORE_32O",
    };
  },
  olympics: () => {
    return {
      ATF_300: 'NW18_HIND_PWA/NW18_HIND_KHEL_PWA/NW18_HIND_KHEL_PWA_AL/NW18_HIND_KHEL_AL_PWA_ROS_ATF_300',
      ATF_320: 'NW18_HIND_PWA/NW18_HIND_KHEL_PWA/NW18_HIND_KHEL_PWA_AL/NW18_HIND_KHEL_AL_PWA_ROS_ATF_320',
      BTF_300: 'NW18_HIND_PWA/NW18_HIND_KHEL_PWA/NW18_HIND_KHEL_PWA_AL/NW18_HIND_KHEL_AL_PWA_ROS_BTF_300',
      FBN_320: 'NW18_HIND_PWA/NW18_HIND_KHEL_PWA/NW18_HIND_KHEL_PWA_AL/NW18_HIND_KHEL_AL_PWA_ROS_FBN_320',
      header_ATF_320: 'NW18_HIND_PWA/NW18_HIND_KHEL_PWA/NW18_HIND_KHEL_PWA_AL/NW18_HIND_KHEL_AL_PWA_ROS_ATF_320',
      NAT1: '',
      NAT2: '',
      NAT3: '',
      PG_1x1: 'NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_PG_1x1',
      PG_1x1_2: 'NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_PG_1x1_2',
      PG_1x1_3: 'NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_PG_1x1_3',
      PG_1x1_4: 'NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_PG_1x1_4',
      PG_Slider_1x1: 'NW18_HIND_PWA/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_PG_Slider_1x1',
      SHOSH_OOP: 'NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_SHOSH_OOP',
      SKIN_OOP: 'NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_SKIN_OOP',
    }
  }
};

module.exports = dfpMobileIds;
