import { createContext, useState } from "react";

const GlobalContext = createContext();
function GlobalStore(props) {
  const [globalState, setGlobalState] = useState(initialState);
  const updateData = (value, key) => setGlobalState((prev) => ({ ...prev, [key]: value }));
  return <GlobalContext.Provider value={{ globalState, updateData }}>{props.children}</GlobalContext.Provider>;
}
export { GlobalStore, GlobalContext };
const initialState = {
  // cats: {
  //   "andhra-pradesh": 'आंध्र प्रदेश',
  //   aarti: "Aarti",
  //   ahmedabad: "Ahmedabad",
  //   amritsar: "Amritsar",
  //   aurangabad: "Aurangabad",
  //   bhuj: "Bhuj",
  //   "board-results": "Board Results",
  //   education: "शिक्षा",
  //   gandhinagar: "Gandhinagar",
  //   gujarat: "Gujarat",
  //   "ipl-2018": "IPL 2018",
  //   jalandhar: "Jalandhar",
  //   jamnagar: "Jamnagar",
  //   junagadh: "Junagadh",
  //   "relationship-crime": "LSD",
  //   ludhiana: "Ludhiana",
  //   mohali: "Mohali",
  //   mumbai: "Mumbai",
  //   nagpur: "Nagpur",
  //   nashik: "Nashik",
  //   nri: "NRI",
  //   "ajab-gajab": "OMG",
  //   patiala: "Patiala",
  //   porbandar: "PORBANDAR",
  //   "press-release": "Press Release",
  //   pune: "Pune",
  //   punjab: "पंजाब",
  //   rajkot: "Rajkot",
  //   states: "States",
  //   surat: "Surat",
  //   thane: "Thane",
  //   vadodara: "Vadodara",
  //   ambala: "अंबाला",
  //   ajmer: "अजमेर",
  //   "adhure-khawab": "अधूरे ख्‍वाब",
  //   anuppur: "अनूपपुर",
  //   others: "अन्य खेल",
  //   "rest-of-world": "अन्य देश",
  //   afghanistan: "अफ़ग़ानिस्तान",
  //   amethi: "अमेठी",
  //   america: "अमेरिका",
  //   "ambedkar-nagar-uttar-pradesh": "अम्बेडकर नगर",
  //   ayodhya: "अयोध्या",
  //   araria: "अररिया",
  //   arwal: "अरवल",
  //   alwar: "अलवर",
  //   aligarh: "अलीगढ़",
  //   alirajpur: "अलीराजपुर",
  //   almora: "अल्मोड़ा",
  //   ashoknagar: "अशोकनगर",
  //   "agar-malwa": "आगर मालवा",
  //   agra: "आगरा",
  //   azamgarh: "आजमगढ़",
  //   "aadhi-haqeeqat-aadha-fasana": "आधी हकीकत, आधा फसाना",
  //   "eye-witness": "आपबीती",
  //   "aamne-saamne": "आमने सामने",
  //   "aar-paar": "आर पार",
  //   "indian-army-vacancy": "आर्मी",
  //   "international-studies": "इंटरनेश्नल स्टडीज",
  //   interview: "इंटरव्यू",
  //   indore: "इंदौर",
  //   etawah: "इटावा",
  //   innovation: "इनोवेशन",
  //   allahabad: "इलाहाबाद",
  //   ujjain: "उज्जैन",
  //   "uttar-pradesh": "उत्तर प्रदेश",
  //   uttarakhand: "उत्तराखंड",
  //   uttarkashi: "उत्‍तरकाशी",
  //   udaipur: "उदयपुर",
  //   unnao: "उन्नाव",
  //   umaria: "उमरिया",
  //   "udham-singh-nagar": "ऊधमसिंह नगर",
  //   una: "ऊना",
  //   etah: "एटा",
  //   accessories: "एसेसरीज़",
  //   apps: "ऐप्स",
  //   auto: "ऑटो",
  //   "online-business": "ऑनलाइन बिज़नेस",
  //   australia: "ऑस्ट्रेलिया",
  //   "aurangabad-bihar": "औरंगाबाद",
  //   "kachchaa-chitthaa": "कच्चा चिट्ठा",
  //   kutchh: "कच्छ",
  //   katni: "कटनी",
  //   katihar: "कटिहार",
  //   kannauj: "कन्नौज",
  //   kapurthala: "कपूरथला",
  //   karnal: "करनाल",
  //   career: "करियर",
  //   karauli: "करौली",
  //   culture: "कल्चर",
  //   kawardha: "कवर्धा",
  //   kanker: "कांकेर",
  //   kanpur: "कानपुर",
  //   cars: "कार",
  //   "cartoon-corner": "कार्टून कॉर्नर",
  //   kasganj: "कासगंज",
  //   kishanganj: "किशनगंज",
  //   kurukshetra: "कुरुक्षेत्र",
  //   kullu: "कुल्‍लू",
  //   kushinagar: "कुशीनगर",
  //   keylong: "केलांग",
  //   kaithal: "कैथल",
  //   kaimur: "कैमूर",
  //   kondagaon: "कोंडागांव",
  //   kota: "कोटा",
  //   koderma: "कोडरमा",
  //   korba: "कोरबा",
  //   korea: "कोरिया",
  //   kaushambi: "कौशाम्बी",
  //   crime: "क्राइम",
  //   "crime-tv": "क्राइम टीवी",
  //   cricket: "क्रिकेट",
  //   khandwa: "खंडवा",
  //   khagaria: "खगड़िया",
  //   khargone: "खरगोन",
  //   khunti: "खूंटी",
  //   sports: "खेल",
  //   garhwa: "गढ़वा",
  //   "crime-report": "गतांक से आगे",
  //   gaya: "गया",
  //   gariaband: "गरियाबंद",
  //   ghazipur: "गाजीपुर",
  //   giridih: "गिरिडीह",
  //   guna: "गुना",
  //   gumla: "गुमला",
  //   gurdaspur: "गुरदासपुर",
  //   gadgets: "गैजेट्स",
  //   gonda: "गोंडा",
  //   godda: "गोड्डा",
  //   gopalganj: "गोपालगंज",
  //   gorakhpur: "गोरखपुर",
  //   "gorband-shows": "गोरबंद",
  //   "grah-nakshatra": "ग्रह-नक्षत्र",
  //   "greater-noida": "ग्रेटर नोएडा",
  //   gwalior: "ग्वालियर",
  //   "chandigarh-city": "चंडीगढ़",
  //   "chandigarh-punjab": "चंडीगढ़ (पंजाब)",
  //   chamba: "चंबा",
  //   chatra: "चतरा",
  //   chamoli: "चमोली",
  //   champawat: "चम्‍पावत",
  //   "charkhi-dadri": "चरखी दादरी",
  //   chittorgarh: "चित्तौड़गढ़",
  //   chitrakoot: "चित्रकूट",
  //   "chidiya-udh": "चिड़िया उड़",
  //   china: "चीन",
  //   churu: "चूरू",
  //   chhatarpur: "छतरपुर",
  //   chhattisgarh: "छत्तीसगढ़",
  //   chhindwara: "छिंदवाड़ा",
  //   jabalpur: "जबलपुर",
  //   jamshedpur: "जमशेदपुर",
  //   jamui: "जमुई",
  //   jaipur: "जयपुर",
  //   jashpur: "जशपुर",
  //   jehanabad: "जहानाबाद",
  //   janjgir: "जांजगीर",
  //   jamtara: "जामताड़ा",
  //   jalore: "जालोर",
  //   "jind-haryana": "जींद",
  //   "jeevan-samvad": "जीवन संवाद",
  //   jaisalmer: "जैसलमेर",
  //   jodhpur: "जोधपुर",
  //   jaunpur: "जौनपुर",
  //   jhajjar: "झज्‍जर",
  //   jhansi: "झांसी",
  //   jhabua: "झाबुआ",
  //   jharkhand: "झारखंड",
  //   jhalawar: "झालावाड़",
  //   jhunjhunu: "झुंझुनूं",
  //   "tehri-garhwal": "टिहरी गढ़वाल",
  //   tikamgarh: "टीकमगढ़",
  //   "teacher-vacancy": "टीचिंग",
  //   tv: "टीवी",
  //   tennis: "टेनिस",
  //   tonk: "टोंक",
  //   trends: "ट्रेंड्स",
  //   travel: "ट्रैवल",
  //   dindori: "डिंडोरी",
  //   "debate-shows": "डिबेट शो",
  //   diy: "डीआईवाई",
  //   dungarpur: "डूंगरपुर",
  //   "transfer-posting": "तबादला",
  //   "tarn-taran": "तरनतारन",
  //   thriller: "थ्रिलर",
  //   dantewada: "दंतेवाड़ा",
  //   datia: "दतिया",
  //   damoh: "दमोह",
  //   darbhanga: "दरभंगा",
  //   "delhi-ncr": "दिल्ली-एनसीआर",
  //   world: "दुनिया",
  //   dumka: "दुमका",
  //   durg: "दुर्ग",
  //   deoghar: "देवघर",
  //   deoria: "देवरिया",
  //   dewas: "देवास",
  //   nation: "देश",
  //   "desh-ka-devar": "देश का देवर",
  //   dehradun: "देहरादून",
  //   dausa: "दौसा",
  //   dhanbad: "धनबाद",
  //   dhamtari: "धमतरी",
  //   dharm: "धर्म",
  //   dharamsala: "धर्मशाला",
  //   dhar: "धार",
  //   dholpur: "धौलपुर",
  //   "narsinghpur-madhya-pradesh": "नरसिंहपुर",
  //   nawanshahr: "नवांशहर",
  //   nawada: "नवादा",
  //   nagaur: "नागौर",
  //   narayanpur: "नारायणपुर",
  //   nalanda: "नालंदा",
  //   nahan: "नाहन",
  //   neemuch: "नीमच",
  //   nepal: "नेपाल",
  //   nainital: "नैनीताल",
  //   knowledge: "नॉलेज",
  //   jobs: "नौकरी",
  //   panchkula: "पंचकुला",
  //   patna: "पटना",
  //   pathankot: "पठानकोट",
  //   panna: "पन्‍ना",
  //   palwal: "पलवल",
  //   palamu: "पलामू",
  //   "west-champaran": "पश्चिमी चंपारण",
  //   "west-singhbum": "पश्चिमी सिंहभूम",
  //   pakistan: "पाकिस्तान",
  //   pakur: "पाकुड़",
  //   panipat: "पानीपत​",
  //   pali: "पाली",
  //   pithoragarh: "पिथौरागढ़",
  //   pilibhit: "पीलीभीत",
  //   "police-investigation": "पुलिस कथा",
  //   pushkar: "पुष्कर",
  //   purnia: "पूर्णिया",
  //   "east-champaran": "पूर्वी चंपारण",
  //   "east-singhbum": "पूर्वी सिंहभूम",
  //   money: "पैसा",
  //   "money-making-tips": "पैसा बनाओ",
  //   poster: "पोस्टर",
  //   "pauri-garhwal": "पौड़ी गढ़वाल",
  //   pratapgarh: "प्रतापगढ़",
  //   "pratapgarh-uttar-pradesh-2": "प्रतापगढ़",
  //   "prime-debate": "प्राइम डिबेट",
  //   "fatehgarh-sahib": "फतेहगढ़ साहिब",
  //   fatehpur: "फतेहपुर",
  //   fatehabad: "फतेहाबाद",
  //   faridkot: "फरीदकोट",
  //   faridabad: "फरीदाबाद",
  //   farrukhabad: "फर्रुखाबाद",
  //   "film-review": "फ़िल्म रिव्यू",
  //   fazilka: "फाजिल्‍का",
  //   firozpur: "फिरोजपुर",
  //   firozabad: "फिरोजाबाद",
  //   football: "फुटबॉल",
  //   recipe: "फूड",
  //   faizabad: "फैजाबाद",
  //   fashion: "फैशन",
  //   photo: "फोटो",
  //   buxar: "बक्सर",
  //   bathinda: "बठिंडा",
  //   barwani: "बड़वानी",
  //   badaun: "बदायूं",
  //   barnala: "बरनाला",
  //   bareilly: "बरेली",
  //   "balrampur-ramanujganj": "बलरामपुर-रामानुजगंज",
  //   ballia: "बलिया",
  //   "baloda-bazar": "बलौदा बाजार",
  //   bastar: "बस्तर",
  //   basti: "बस्ती",
  //   bahraich: "बहराइच",
  //   "banka-bihar": "बांका",
  //   bangladesh: "बांग्लादेश",
  //   banda: "बांदा",
  //   banswara: "बांसवाड़ा",
  //   bikes: "बाइक",
  //   baghpat: "बागपत",
  //   bageshwar: "बागेश्‍वर",
  //   barmer: "बाड़मेर",
  //   baran: "बारां",
  //   barabanki: "बाराबंकी",
  //   balaghat: "बालाघाट",
  //   balod: "बालोद",
  //   bijnor: "बिजनौर",
  //   bilaspur: "बिलासपुर",
  //   "bilaspur-hp": "बिलासपुर (हिमाचल)",
  //   bihar: "बिहार",
  //   bikaner: "बीकानेर",
  //   bijapur: "बीजापुर",
  //   bulandshahr: "बुलंदशहर",
  //   bundi: "बूंदी",
  //   begusarai: "बेगूसराय",
  //   bemetara: "बेमेतरा",
  //   "bank-vacancy": "बैंकिंग",
  //   betul: "बैतूल",
  //   bollywood: "बॉलीवुड",
  //   bokaro: "बोकारो",
  //   blog: "ब्लॉग",
  //   bhadohi: "भदोही",
  //   bharatpur: "भरतपुर",
  //   bhagalpur: "भागलपुर",
  //   bhind: "भिंड",
  //   bhiwani: "भिवानी",
  //   bhilwara: "भीलवाड़ा",
  //   "bhaiyaji-kahin": "भैयाजी कहिन",
  //   bhojpur: "भोजपुर",
  //   bhojpuri: "भोजपुरी",
  //   bhopal: "भोपाल",
  //   mandla: "मंडला",
  //   mandi: "मंडी",
  //   mandsaur: "मंदसौर",
  //   mau: "मऊ",
  //   mathura: "मथुरा",
  //   madhubani: "मधुबनी",
  //   madhepura: "मधेपुरा",
  //   "madhya-pradesh": "मध्य प्रदेश",
  //   mansa: "मनसा",
  //   manali: "मनाली",
  //   business: "मनी",
  //   entertainment: "मनोरंजन",
  //   maharajganj: "महाराजगंज",
  //   maharashtra: "महाराष्ट्र",
  //   mahasamund: "महासमुंद",
  //   mahendragarh: "महेंद्रगढ़",
  //   mahoba: "महोबा",
  //   "middle-east": "मिडिल ईस्ट",
  //   mirzapur: "मिर्जापुर",
  //   munger: "मुंगेर",
  //   mungeli: "मुंगेली",
  //   muktsar: "मुक्तसर",
  //   muzaffarnagar: "मुजफ्फरनगर",
  //   muzaffarpur: "मुजफ्फरपुर",
  //   moradabad: "मुरादाबाद",
  //   morena: "मुरैना",
  //   meerut: "मेरठ",
  //   mewat: "मेवात",
  //   mainpuri: "मैनपुरी",
  //   moga: "मोगा",
  //   motihari: "मोतिहारी",
  //   tech: "मोबाइल-टेक",
  //   "young-parents": "यंग पेरेंट्स",
  //   yamunanagar: "यमुनानगर",
  //   youtube: "यूट्यूब",
  //   europe: "यूरोप",
  //   ratlam: "रतलाम",
  //   "rasoi-se": "रसोई से",
  //   ranchi: "रांची",
  //   rajgarh: "राजगढ़",
  //   rajgir: "राजगीर",
  //   rajnandgaon: "राजनांदगांव",
  //   rajsamand: "राजसमन्द‍",
  //   rajasthan: "राजस्थान",
  //   ramgarh: "रामगढ़",
  //   rampur: "रामपुर",
  //   raigarh: "रायगढ़",
  //   raipur: "रायपुर",
  //   "rae-bareli": "रायबरेली",
  //   raisen: "रायसेन",
  //   astro: "राशि",
  //   "reckong-peo": "रिकांग पिओ",
  //   relationships: "रिलेशनशिप",
  //   relationship: "रिलेशनशिप",
  //   "etv-shows": "रीजनल शो",
  //   rewa: "रीवा",
  //   rudraprayag: "रुद्रप्रयाग",
  //   rupnagar: "रूपनगर",
  //   "railway-vacancy": "रेलवे",
  //   rewari: "रेवाड़ी",
  //   rohtak: "रोहतक",
  //   rohtas: "रोहतास",
  //   lucknow: "लखनऊ",
  //   "lakhimpur-kheri-uttar-pradesh": "लखीमपुर खेरी",
  //   lakhisarai: "लखीसराय",
  //   lifestyle: "लाइफ़ NEWS",
  //   latehar: "लातेहार",
  //   "long-read": "लॉन्ग रीड",
  //   "launch-review": "लॉन्च/रिव्यू",
  //   lohardaga: "लोहरदगा",
  //   viral: "वायरल",
  //   varanasi: "वाराणसी",
  //   "vidisha-madhya-pradesh": "विदिशा",
  //   vaishali: "वैशाली",
  //   shakhsiyat: "शख्‍सियत",
  //   shahdol: "शहडोल",
  //   shajapur: "शाजापुर",
  //   shamli: "शामली",
  //   shahjahanpur: "शाहजहांपुर",
  //   shimla: "शिमला",
  //   shivpuri: "शिवपुरी",
  //   sheikhpura: "शेखपुरा",
  //   shows: "शो",
  //   shravasti: "श्रावस्ती",
  //   "sri-ganganagar": "श्रीगंगानगर",
  //   srilanka: "श्रीलंका",
  //   sheopur: "श्‍योपुर",
  //   sangrur: "संगरूर",
  //   sangini: "संगिनी",
  //   "sant-ravidas-nagar": "संत रविदास नगर",
  //   "sant-kabir-nagar": "संतकबीरनगर",
  //   sambhal: "संभल",
  //   "success-story": "सक्सेस स्टोरी",
  //   satna: "सतना",
  //   samastipur: "समस्तीपुर",
  //   "sarkari-naukri": "सरकारी नौकरी",
  //   surguja: "सरगुजा",
  //   "saraikela-kharsawan": "सराईकेला-खरसांवा",
  //   "sawai-madhopur": "सवाई माधोपुर",
  //   saharsa: "सहरसा",
  //   saharanpur: "सहारनपुर",
  //   "cyber-crime": "साइबर",
  //   sagar: "सागर",
  //   saran: "सारण",
  //   "saas-bahu-aur-devrani": "सास, बहू और देवरानी",
  //   sahebganj: "साहेबगंज",
  //   singrauli: "सिंगरौली",
  //   sidharthanagar: "सिद्धार्थनगर",
  //   simdega: "सिमडेगा",
  //   sirsa: "सिरसा",
  //   sirohi: "सिरोही",
  //   seoni: "सिवनी",
  //   sikar: "सीकर",
  //   sitapur: "सीतापुर",
  //   sitamarhi: "सीतामढ़ी",
  //   sidhi: "सीधी",
  //   siwan: "सीवान",
  //   sehore: "सीहोर",
  //   sukma: "सुकमा",
  //   supaul: "सुपौल",
  //   sultanpur: "सुल्तानपुर",
  //   surajpur: "सूरजपुर",
  //   sonbhadra: "सोनभद्र",
  //   sonipat: "सोनीपत",
  //   solan: "सोलन",
  //   "viral-social": "सोशल / वायरल",
  //   "social-viral": "सोशल/वायरल",
  //   "sau-baat-ki-ek-baat": "सौ बात की एक बात",
  //   hazaribagh: "हजारीबाग",
  //   hanumangarh: "हनुमानगढ़",
  //   "hum-to-poochenge": "हम तो पूछेंगे",
  //   "hamirpur-uttar-pradesh": "हमीरपुर",
  //   hamirpur: "हमीरपुर",
  //   harda: "हरदा",
  //   hardoi: "हरदोई",
  //   haridwar: "हरिद्वार",
  //   haryana: "हरियाणा",
  //   hathras: "हाथरस",
  //   "crime-news": "हादसा",
  //   hapur: "हापुड़",
  //   "himachal-pradesh": "हिमाचल प्रदेश",
  //   hisar: "हिसार",
  //   "history-18": "हिस्ट्री 18",
  //   health: "हेल्थ & फिटनेस",
  //   hockey: "हॉकी",
  //   hollywood: "हॉलीवुड",
  //   hoshangabad: "होशंगाबाद",
  //   hoshiarpur: "होशियारपुर",
  //   "human-stories": "ह्यूमन स्‍टोरी",
  // },
  // topStories: {
  //   loaded: false,
  //   data: [
  //     {
  //       id: "1",
  //       display_headline: "...",
  //       post_image: "",
  //     },
  //     {
  //       id: "2",
  //       display_headline: "...",
  //       post_image: "",
  //     },
  //     {
  //       id: "3",
  //       display_headline: "...",
  //       post_image: "",
  //     },
  //     {
  //       id: "4",
  //       display_headline: "...",
  //       post_image: "",
  //     },
  //     {
  //       id: "5",
  //       display_headline: "...",
  //       post_image: "",
  //     },
  //   ],
  // },
  // photoGallery: {
  //   loaded: false,
  //   data: [
  //     {
  //       id: "1",
  //       display_headline: "...",
  //       post_image: "",
  //     },
  //     {
  //       id: "2",
  //       display_headline: "...",
  //       post_image: "",
  //     },
  //     {
  //       id: "3",
  //       display_headline: "...",
  //       post_image: "",
  //     },
  //   ],
  // },
  // relatedArticles: {
  //   loaded: false,
  //   data: [
  //     {
  //       id: "1",
  //       headline: "...",
  //     },
  //     {
  //       id: "2",
  //       headline: "...",
  //     },
  //     {
  //       id: "3",
  //       headline: "...",
  //     },
  //   ],
  // },
  t20_country_list: {
    "oman": "ओमान",
    "papua new guinea": "पापुआ न्यू गिनी",
    "bangladesh": "बांग्लादेश",
    "scotland": "स्कॉटलैंड",
    "ireland": "आयरलैंड",
    "netherlands": "नीदरलैंड्स",
    "sri lanka": "श्रीलंका",
    "namibia": "नामीबिया",
    "australia": "ऑस्ट्रेलिया",
    "south africa": "दक्षिण अफ्रीका",
    "england": "इंग्लैंड",
    "west indies": "वेस्ट इंडीज़",
    "india": "भारत",
    "pakistan": "पाकिस्तान",
    "afghanistan": "अफ़ग़ानिस्तान",
    "new zealand": "न्यूज़ीलैंड",
    "Australia": 'ऑस्ट्रेलिया',
		"Bangladesh": 'बांग्लादेश',
		"England": 'इंग्लैंड',
		"India": 'भारत',
		"New Zealand": 'न्यूजीलैंड',
		"Pakistan": 'पाकिस्तान',
		"South Africa": 'दक्षिण अफ्रीका',
		"Sri Lanka": 'श्रीलंका',
		"West Indies": 'वेस्टइंडीज',
		"Zimbabwe": 'जिम्बाब्वे',
		"Bermuda": 'बरमूडा',
		"Canada": 'कनाडा',
		"Ireland": 'आयरलैंड',
		"Afghanistan": 'अफगानिस्तान',
		"Nepal": 'नेपाल',
		"Papua New Guinea": 'पापुआ न्यू गिनी',
		"Oman": 'ओमान',
		"Kenya": 'केन्या',
		"Netherlands": 'नीदरलैंड',
		"Scotland": 'स्कॉटलैंड',
		"Hong Kong": 'हॉन्गकॉन्ग',
		"Namibia": 'नामीबिया',
		"United Arab Emirates": 'यूएई',
		"Usa": 'अमेरिका',
  },
};

export default initialState;
