// const AD_TAGS = {
//   category: {
//     gujarat: {
//       header_ATF_728: 'NW18_GUJ_Desktop/NW18_GUJ_GUJARAT/NW18_GUJ_GUJARAT_AL/NW18_GUJ_GUJ_AL_ROS_ATF_728',
//       rhs_ATF_300: 'NW18_GUJ_Desktop/NW18_GUJ_GUJARAT/NW18_GUJ_GUJARAT_AL/NW18_GUJ_GUJ_AL_ROS_ATF_300',
//       rhs_MTF_300: 'NW18_GUJ_Desktop/NW18_GUJ_GUJARAT/NW18_GUJ_GUJARAT_AL/NW18_GUJ_GUJ_AL_ROS_MTF_300',
//       rhs_BTF_300: 'NW18_GUJ_Desktop/NW18_GUJ_GUJARAT/NW18_GUJ_GUJARAT_AL/NW18_GUJ_GUJ_AL_ROS_BTF_300',
//       BTF_728: 'NW18_GUJ_Desktop/NW18_GUJ_GUJARAT/NW18_GUJ_GUJARAT_AL/NW18_GUJ_GUJ_AL_ROS_BTF_728',
//     },
//     gujarat_ahmedabad: {
//       header_ATF_728: 'NW18_GUJ_Desktop/NW18_GUJ_GUJARAT/NW18_GUJ_GUJARAT_AHMEDABAD_AL/NW18_GUJ_AHM_AL_ROS_ATF_728',
//       rhs_ATF_300: 'NW18_GUJ_Desktop/NW18_GUJ_GUJARAT/NW18_GUJ_GUJARAT_AHMEDABAD_AL/NW18_GUJ_AHM_AL_ROS_ATF_300',
//       rhs_MTF_300: 'NW18_GUJ_Desktop/NW18_GUJ_GUJARAT/NW18_GUJ_GUJARAT_AHMEDABAD_AL/NW18_GUJ_AHM_AL_ROS_MTF_300',
//       rhs_BTF_300: 'NW18_GUJ_Desktop/NW18_GUJ_GUJARAT/NW18_GUJ_GUJARAT_AHMEDABAD_AL/NW18_GUJ_AHM_AL_ROS_BTF_300',
//       BTF_728: 'NW18_GUJ_Desktop/NW18_GUJ_GUJARAT/NW18_GUJ_GUJARAT_AHMEDABAD_AL/NW18_GUJ_AHM_AL_ROS_BTF_728',
//     },
//     business: {
//       header_ATF_728: 'NW18_GUJ_Desktop/NW18_GUJ_BUSINESS/NW18_GUJ_BUSINESS_AL/NW18_GUJ_BUS_AL_ROS_ATF_728',
//       rhs_ATF_300: 'NW18_GUJ_Desktop/NW18_GUJ_BUSINESS/NW18_GUJ_BUSINESS_AL/NW18_GUJ_BUS_AL_ROS_ATF_300',
//       rhs_MTF_300: 'NW18_GUJ_Desktop/NW18_GUJ_BUSINESS/NW18_GUJ_BUSINESS_AL/NW18_GUJ_BUS_AL_ROS_MTF_300',
//       rhs_BTF_300: 'NW18_GUJ_Desktop/NW18_GUJ_BUSINESS/NW18_GUJ_BUSINESS_AL/NW18_GUJ_BUS_AL_ROS_BTF_300',
//       BTF_728: 'NW18_GUJ_Desktop/NW18_GUJ_BUSINESS/NW18_GUJ_BUSINESS_AL/NW18_GUJ_BUS_AL_ROS_BTF_728',
//     },
//     national_international: {
//       header_ATF_728: 'NW18_GUJ_Desktop/NW18_GUJ_NATIONALINTERNATIONAL/NW18_GUJ_NATIONALINTERNATIONAL_AL/NW18_GUJ_NATINTL_AL_ROS_ATF_728',
//       rhs_ATF_300: 'NW18_GUJ_Desktop/NW18_GUJ_NATIONALINTERNATIONAL/NW18_GUJ_NATIONALINTERNATIONAL_AL/NW18_GUJ_NATINTL_AL_ROS_ATF_300',
//       rhs_MTF_300: 'NW18_GUJ_Desktop/NW18_GUJ_NATIONALINTERNATIONAL/NW18_GUJ_NATIONALINTERNATIONAL_AL/NW18_GUJ_NATINTL_AL_ROS_MTF_300',
//       rhs_BTF_300: 'NW18_GUJ_Desktop/NW18_GUJ_NATIONALINTERNATIONAL/NW18_GUJ_NATIONALINTERNATIONAL_AL/NW18_GUJ_NATINTL_AL_ROS_BTF_300',
//       BTF_728: 'NW18_GUJ_Desktop/NW18_GUJ_NATIONALINTERNATIONAL/NW18_GUJ_NATIONALINTERNATIONAL_AL/NW18_GUJ_NATINTL_AL_ROS_BTF_728',
//     },
//     entertainment: {
//       header_ATF_728: 'NW18_GUJ_Desktop/NW18_GUJ_ENTERTAINMENT/NW18_GUJ_ENTERTAINMENT_AL/NW18_GUJ_ENT_AL_ROS_ATF_728',
//       rhs_ATF_300: 'NW18_GUJ_Desktop/NW18_GUJ_ENTERTAINMENT/NW18_GUJ_ENTERTAINMENT_AL/NW18_GUJ_ENT_AL_ROS_ATF_300',
//       rhs_MTF_300: 'NW18_GUJ_Desktop/NW18_GUJ_ENTERTAINMENT/NW18_GUJ_ENTERTAINMENT_AL/NW18_GUJ_ENT_AL_ROS_MTF_300',
//       rhs_BTF_300: 'NW18_GUJ_Desktop/NW18_GUJ_ENTERTAINMENT/NW18_GUJ_ENTERTAINMENT_AL/NW18_GUJ_ENT_AL_ROS_BTF_300',
//       BTF_728: 'NW18_GUJ_Desktop/NW18_GUJ_ENTERTAINMENT/NW18_GUJ_ENTERTAINMENT_AL/NW18_GUJ_ENT_AL_ROS_BTF_728',
//     },
//     sport: {
//       header_ATF_728: 'NW18_GUJ_Desktop/NW18_GUJ_SPORTS/NW18_GUJ_SPORTS_AL/NW18_GUJ_SPT_AL_ROS_ATF_728',
//       rhs_ATF_300: 'NW18_GUJ_Desktop/NW18_GUJ_SPORTS/NW18_GUJ_SPORTS_AL/NW18_GUJ_SPT_AL_ROS_ATF_300',
//       rhs_MTF_300: 'NW18_GUJ_Desktop/NW18_GUJ_SPORTS/NW18_GUJ_SPORTS_AL/NW18_GUJ_SPT_AL_ROS_MTF_300',
//       rhs_BTF_300: 'NW18_GUJ_Desktop/NW18_GUJ_SPORTS/NW18_GUJ_SPORTS_AL/NW18_GUJ_SPT_AL_ROS_BTF_300',
//       BTF_728: 'NW18_GUJ_Desktop/NW18_GUJ_SPORTS/NW18_GUJ_SPORTS_AL/NW18_GUJ_SPT_AL_ROS_BTF_728',
//     },
//     sport_cricket: {
//       header_ATF_728: 'NW18_GUJ_Desktop/NW18_GUJ_SPORTS/NW18_GUJ_SPORTS_CRICKET_AL/NW18_GUJ_SPT_CRI_AL_ROS_ATF_728',
//       rhs_ATF_300: 'NW18_GUJ_Desktop/NW18_GUJ_SPORTS/NW18_GUJ_SPORTS_CRICKET_AL/NW18_GUJ_SPT_CRI_AL_ROS_ATF_300',
//       rhs_MTF_300: 'NW18_GUJ_Desktop/NW18_GUJ_SPORTS/NW18_GUJ_SPORTS_CRICKET_AL/NW18_GUJ_SPT_CRI_AL_ROS_MTF_300',
//       rhs_BTF_300: 'NW18_GUJ_Desktop/NW18_GUJ_SPORTS/NW18_GUJ_SPORTS_CRICKET_AL/NW18_GUJ_SPT_CRI_AL_ROS_BTF_300',
//       BTF_728: 'NW18_GUJ_Desktop/NW18_GUJ_SPORTS/NW18_GUJ_SPORTS_CRICKET_AL/NW18_GUJ_SPT_CRI_AL_ROS_BTF_728',
//     },
//     lifestyle: {
//       header_ATF_728: 'NW18_GUJ_Desktop/NW18_GUJ_LIFESTYLE/NW18_GUJ_LIFESTYLE_AL/NW18_GUJ_LFSTL_AL_ROS_ATF_728',
//       rhs_ATF_300: 'NW18_GUJ_Desktop/NW18_GUJ_LIFESTYLE/NW18_GUJ_LIFESTYLE_AL/NW18_GUJ_LFSTL_AL_ROS_ATF_300',
//       rhs_MTF_300: 'NW18_GUJ_Desktop/NW18_GUJ_LIFESTYLE/NW18_GUJ_LIFESTYLE_AL/NW18_GUJ_LFSTL_AL_ROS_MTF_300',
//       rhs_BTF_300: 'NW18_GUJ_Desktop/NW18_GUJ_LIFESTYLE/NW18_GUJ_LIFESTYLE_AL/NW18_GUJ_LFSTL_AL_ROS_BTF_300',
//       BTF_728: 'NW18_GUJ_Desktop/NW18_GUJ_LIFESTYLE/NW18_GUJ_LIFESTYLE_AL/NW18_GUJ_LFSTL_AL_ROS_BTF_728',
//     },
//     tech: {
//       header_ATF_728: 'NW18_GUJ_Desktop/NW18_GUJ_TECH/NW18_GUJ_TECH_AL/NW18_GUJ_TECH_AL_ROS_ATF_728',
//       rhs_ATF_300: 'NW18_GUJ_Desktop/NW18_GUJ_TECH/NW18_GUJ_TECH_AL/NW18_GUJ_TECH_AL_ROS_ATF_300',
//       rhs_MTF_300: 'NW18_GUJ_Desktop/NW18_GUJ_TECH/NW18_GUJ_TECH_AL/NW18_GUJ_TECH_AL_ROS_MTF_300',
//       rhs_BTF_300: 'NW18_GUJ_Desktop/NW18_GUJ_TECH/NW18_GUJ_TECH_AL/NW18_GUJ_TECH_AL_ROS_BTF_300',
//       BTF_728: 'NW18_GUJ_Desktop/NW18_GUJ_TECH/NW18_GUJ_TECH_AL/NW18_GUJ_TECH_AL_ROS_BTF_728',
//     },
//     xyz: {
//       header_ATF_728: 'website',
//       rhs_ATF_300: 'NW18_GUJ_GUJ_AL_ROS_ATF_300',
//       rhs_MTF_300: 'NW18_GUJ_GUJ_AL_ROS_MTF_300',
//       rhs_BTF_300: 'NW18_GUJ_GUJ_AL_ROS_BTF_300',
//       BTF_728: 'NW18_GUJ_GUJ_AL_ROS_BTF_728',
//     },
//   },
//   default: {
//     header_ATF_728: 'NW18_GUJ_Desktop/NW18_GUJ_ROS/NW18_GUJ_ROS_AL/NW18_GUJ_ROS_AL_ROS_ATF_728',
//     rhs_ATF_300: 'NW18_GUJ_Desktop/NW18_GUJ_ROS/NW18_GUJ_ROS_AL/NW18_GUJ_ROS_AL_ROS_ATF_300',
//     rhs_MTF_300: '',
//     rhs_BTF_300: 'NW18_GUJ_Desktop/NW18_GUJ_ROS/NW18_GUJ_ROS_AL/NW18_GUJ_ROS_AL_ROS_BTF_300',
//     BTF_728: 'NW18_GUJ_Desktop/NW18_GUJ_ROS/NW18_GUJ_ROS_AL/NW18_GUJ_ROS_AL_ROS_BTF_728',
//   },
// };

// export default AD_TAGS
// "news": ["DESH","DESH", "DSH"],
// nation: ["DESH", "DESH", "DSH"],
const adPairs = {
  nation: ["DUNIA", "DUNIA", "DUNYA"],
  states: ["PRADESH", "PRADESH", "PRADSH"],
  "uttar-pradesh": ["PRADESH", "PRADESH_UP", "PRADSH_UP"],
  "uttar_pradesh": ["PRADESH", "PRADESH_UP", "PRADSH_UP"],
  bihar: ["PRADESH", "PRADESH_BIH", "PRADSH_BR"],
  "madhya-pradesh": ["PRADESH", "PRADESH_MP", "PRADSH_MP"],
  "madhya_pradesh": ["PRADESH", "PRADESH_MP", "PRADSH_MP"],
  uttarakhand: ["PRADESH", "PRADESH_UTK", "PRADSH_UK"],
  rajasthan: ["PRADESH", "PRADESH_RAJ", "PRADSH_RJ"],
  haryana: ["PRADESH", "PRADESH_HAR", "PRADSH_HR"],
  jharkhand: ["PRADESH", "PRADESH_JKD", "PRADSH_JK"],
  chhattisgarh: ["PRADESH", "PRADESH_CHG", "PRADSH_CH"],
  "himachal-pradesh": ["PRADESH", "PRADESH_HP", "PRADSH_HP"],
  "himachal_pradesh": ["PRADESH", "PRADESH_HP", "PRADSH_HP"],
  maharashtra: ["PRADESH", "PRADESH_MAH", "PRADSH_MH"],
  "delhi-ncr": ["PRADESH", "PRADESH_DELHI", "PRADSH_DL"],
  punjab: ["PRADESH", "PRADESH_PUNJAB", "PRADSH_PJB"],
  tech: ["TECH", "TECH", "TECH"],
  dharm: ["DHARM", "DHARM", "DHARM"],
  world: ["DUNIA", "DUNIA", "DUNYA"],
  pakistan: ["DUNIA", "DUNIA_PAKISTAN", "DUNYA_PAK"],
  china: ["DUNIA", "DUNIA_CHINA", "DUNYA_CHI"],
  america: ["DUNIA", "DUNIA_AMERICA", "DUNYA_AME"],
  rest_of_world: ["DUNIA", "DUNIA_RESTOFWORLD", "DUNYA_RSTWLD"],
  entertainment: ["MANORANJAN", "MANORANJAN", "MANO"],
  bollywood: ["MANORANJAN", "MANORANJAN_BOLLYWOOD", "MANO_BLYWOD"],
  viral_social: ["MANORANJAN", "MANORANJAN_VIRALSOCIAL", "MANO_VRLSCL"],
  bhojpuri: ["MANORANJAN", "MANORANJAN_BHOJPURI", "MANO_BHO"],
  film_review: ["MANORANJAN", "MANORANJAN_FILMREVIEW", "MANO_FLMREV"],
  youtube: ["MANORANJAN", "MANORANJAN_YOUTUBE", "MANO_YUTUB"],
  hollywood: ["MANORANJAN", "MANORANJAN_HOLLYWOOD", "MANO_HLYWOD"],
  sports: ["KHEL", "KHEL", "KHEL"],
  cricket: ["KHEL", "CRI", "CRI"],
  business: ["MONEY", "MONEY", "MNY"],
  auto: ["AUTO", "AUTO", "AUTO"],
  crime: ["CRIME", "CRIME", "CRIME"],
  knowledge: ["SPECIAL", "SPL_KNOLEDGE", "SPL_KNWLDG"],
  career: ["SPECIAL", "SPL_CARRIER", "SPL_CAR"],
  lifestyle: ["SPECIAL", "SPL_LIFE", "SPL_LIFE"],
  recipe: ["SPECIAL", "SPL_LIFE", "SPL_LIFE"],
  "ajab-gajab": ["SPECIAL", "SPL_OMG", "SPL_OMG"],
  mobile: ["MOBILE_TECH", "MTECH", "MTECH"],
  shows: ["NW18_INDIASHOW", "NW18INDSHW", "SHW"],
  "regional-shows": ["REGIONALSHOW", "REGSHW", "REGSHW"],
  photogallery: ["PHOTO", "PHOTO", "PHT"],
  videos: ["VIDEO", "VIDEO", "VID"],
  LiveBlog: ["LIVEBLOG", "LIVEBLOG", "LIVBLG"],
  jobs: ["JOBS", "JOBS", "JOBS"],
  astro: ["ASTRO", "ASTRO", "ASTRO"],
  topic: ["TOPIC", "TOPIC", "TOPIC"],
  news: ["DESH", "DESH", "DSH"],
  manoranjan: ["MANORANJAN", "MANORANJAN", "MANO"],
  literature: ["LITERATURE", "LITERATURE", "LITE"],
  education: ["EDUCATION","EDUCATION","EDUC"]
};

const generateAdTags = (target = "listing", category, isPhoto, opt = {}, isDistrict = false) => {
  const targetCode = target == "listing" ? "AL" : "AS";
  if (!adPairs[category]) {
    return {
      header_ATF_728: isDistrict ?
        'NW18_HIND_Desktop/NW18_HIND_LOCAL18_NEWS/NW18_HIND_LOCAL18_NEWS_AS/NW18_HIND_LOCAS18_NWS_AS_ROS_ATF_728'
        : `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_ROS_ATF_728`,
      rhs_ATF_300: isDistrict ?
        `NW18_HIND_Desktop/NW18_HIND_LOCAL18_NEWS/NW18_HIND_LOCAL18_NEWS_AS/NW18_HIND_LOCAS18_NWS_AS_ROS_ATF_300`
        : `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_ROS_ATF_300`,
      rhs_MTF_300: "",
      MTF_300_id: isDistrict ? `NW18_HIND_Desktop/NW18_HIND_LOCAL18_NEWS/NW18_HIND_LOCAL18_NEWS_AS/NW18_HIND_LOCAS18_NWS_AS_ROS_MTF_300` : '',
      rhs_BTF_300: isDistrict ?
        `NW18_HIND_Desktop/NW18_HIND_LOCAL18_/NW18_HIND_LOCAL18_NEWS_AS/NW18_HIND_LOCAS18_NWS_AS_ROS_BTF_300`
        : `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_ROS_BTF_300`,
      BTF_728: isDistrict ?
        `NW18_HIND_Desktop/NW18_HIND_LOCAL18_NEWS/NW18_HIND_LOCAL18_NEWS_AS/NW18_HIND_LOCAS18_NWS_AS_ROS_BTF_728` :
        `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_ROS_BTF_728`,
      Shosh_OOP_id: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_ROS_Shosh_OOP`,
      Skin_OOP_id: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_ROS_Skin_OOP`,
      PG_1x1: !isPhoto
        ? `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_ROS_PG_1x1`
        : `NW18_HIND_Desktop/NW18_HIND_PHOTO/NW18_HIND_PHOTO_PG_${targetCode}/NW18_HIND_PHT_HP_${targetCode}_ROS_PG_1x1`,
      PG_Slider_1x1: !isPhoto
        ? `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_ROS_PG_Slider_1x1`
        : `NW18_HIND_Desktop/NW18_HIND_PHOTO/NW18_HIND_PHOTO_PG_${targetCode}/NW18_HIND_PHT_HP_${targetCode}_ROS_PG_Slider_1x1`,
      ATF_728_id: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_ROS_ATF_728`,
      ATF_300_id: `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_ROS_ATF_300`,
      BTF_300_id: isDistrict ?
        `NW18_HIND_Desktop/NW18_HIND_LOCAL18_NEWS/NW18_HIND_LOCAL18_NEWS_AS/NW18_HIND_LOCAS18_NWS_AS_ROS_BTF_300`
        : `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_ROS_BTF_300`,
      PG_1x1_2: !isPhoto
        ? `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_PG_1x1_2`
        : `NW18_HIND_Desktop/NW18_HIND_PHOTO/NW18_HIND_PHOTO_HP_${targetCode}/NW18_HIND_PHT_HP_${targetCode}_ROS_PG_1x1_2`,
      LBAND_480X60: `NW18_HIND_Desktop/NW18_HIND_LOCAL18_NEWS/NW18_HIND_LOCAL18_NEWS_AS/NW18_HIND_LOCAS18_NWS_AS_ROS_LBAND_480x60`,
      LBAND_1x1: `NW18_HIND_Desktop/NW18_HIND_LOCAL18_NEWS/NW18_HIND_LOCAL18_NEWS_AS/NW18_HIND_LOCAS18_NWS_AS_ROS_LBAND_1x1`,
    };
  }

  let [tagOne, tagTwo, tagThree] = adPairs[category];
  tagThree = isPhoto ? "PHT" : tagThree;
  tagOne = isPhoto ? "PHOTO" : tagOne;
  tagTwo = isPhoto ? "PHOTO" : tagTwo;
  let a = {
    header_ATF_728: isDistrict ?
      'NW18_HIND_Desktop/NW18_HIND_LOCAL18_NEWS/NW18_HIND_LOCAL18_NEWS_AS/NW18_HIND_LOCAS18_NWS_AS_ROS_ATF_728'
      : `NW18_HIND_Desktop/NW18_HIND_${tagOne}/NW18_HIND_${tagTwo}_${targetCode}/NW18_HIND_${tagThree}_${targetCode}_ROS_MID_728`,
    rhs_ATF_300: isDistrict ? `NW18_HIND_Desktop/NW18_HIND_LOCAL18_NEWS/NW18_HIND_LOCAL18_NEWS_AS/NW18_HIND_LOCAS18_NWS_AS_ROS_ATF_300`
      : `NW18_HIND_Desktop/NW18_HIND_${tagOne}/NW18_HIND_${tagTwo}_${targetCode}/NW18_HIND_${tagThree}_${targetCode}_ROS_ATF_300`,
    rhs_MTF_300: isDistrict
      ? `NW18_HIND_Desktop/NW18_HIND_LOCAL18_NEWS/NW18_HIND_LOCAL18_NEWS_AS/NW18_HIND_LOCAS18_NWS_AS_ROS_MTF_300`
      : `NW18_HIND_Desktop/NW18_HIND_${tagOne}/NW18_HIND_${tagTwo}_${targetCode}/NW18_HIND_${tagThree}_${targetCode}_ROS_MTF_300`,
    rhs_BTF_300: isDistrict
      ? `NW18_HIND_Desktop/NW18_HIND_LOCAL18_NEWS/NW18_HIND_LOCAL18_NEWS_AS/NW18_HIND_LOCAS18_NWS_AS_ROS_BTF_300`
      : `NW18_HIND_Desktop/NW18_HIND_${tagOne}/NW18_HIND_${tagTwo}_${targetCode}/NW18_HIND_${tagThree}_${targetCode}_ROS_BTF_300`,
    BTF_728: isDistrict ?
      `NW18_HIND_Desktop/NW18_HIND_LOCAL18_NEWS/NW18_HIND_LOCAL18_NEWS_AS/NW18_HIND_LOCAS18_NWS_AS_ROS_BTF_728` : `NW18_HIND_Desktop/NW18_HIND_${tagOne}/NW18_HIND_${tagTwo}_${targetCode}/NW18_HIND_${tagThree}_${targetCode}_ROS_BTF_728`,
    MTF_728: isDistrict ?
  `NW18_HIND_Desktop/NW18_HIND_LOCAL18_NEWS/NW18_HIND_LOCAL18_NEWS_AS/NW18_HIND_LOCAS18_NWS_AS_ROS_MTF_728` : `NW18_HIND_Desktop/NW18_HIND_${tagOne}/NW18_HIND_${tagTwo}_${targetCode}/NW18_HIND_${tagThree}_${targetCode}_ROS_MTF_728`,
    Shosh_OOP_id: isPhoto
      ? `NW18_HIND_Desktop/NW18_HIND_${tagOne}/NW18_HIND_${tagTwo}_${targetCode}/NW18_HIND_${tagThree}_${targetCode}_ROS_Shosh_OOP`
      : `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_ROS_Shosh_OOP`,
    Skin_OOP_id: isPhoto
      ? `NW18_HIND_Desktop/NW18_HIND_${tagOne}/NW18_HIND_${tagTwo}_${targetCode}/NW18_HIND_${tagThree}_${targetCode}_ROS_Skin_OOP`
      : `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_ROS_Skin_OOP`,
    PG_1x1: !isPhoto
      ? `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_ROS_PG_1x1`
      : `NW18_HIND_Desktop/NW18_HIND_PHOTO/NW18_HIND_PHOTO_${targetCode}/NW18_HIND_PHT_${targetCode}_ROS_PG_1x1`,
    PG_Slider_1x1: !isPhoto
      ? `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_ROS_PG_Slider_1x1`
      : `NW18_HIND_Desktop/NW18_HIND_PHOTO/NW18_HIND_PHOTO_${targetCode}/NW18_HIND_PHT_${targetCode}_ROS_PG_Slider_1x1`,
    ATF_728_id: isDistrict ? 'NW18_HIND_Desktop/NW18_HIND_LOCAL18_NEWS/NW18_HIND_LOCAL18_NEWS_AS/NW18_HIND_LOCAS18_NWS_AS_ROS_ATF_728'
      : `NW18_HIND_Desktop/NW18_HIND_${tagOne}/NW18_HIND_${tagTwo}_${targetCode}/NW18_HIND_${tagThree}_${targetCode}_ROS_ATF_728`,
    ATF_300_id: isDistrict ?
      `NW18_HIND_Desktop/NW18_HIND_LOCAL18_NEWS/NW18_HIND_LOCAL18_NEWS_AS/NW18_HIND_LOCAS18_NWS_AS_ROS_ATF_300`
      : `NW18_HIND_Desktop/NW18_HIND_${tagOne}/NW18_HIND_${tagTwo}_${targetCode}/NW18_HIND_${tagThree}_${targetCode}_ROS_ATF_300`,
    BTF_300_id: isDistrict ?
      `NW18_HIND_Desktop/NW18_HIND_LOCAL18_NEWS/NW18_HIND_LOCAL18_NEWS_AS/NW18_HIND_LOCAS18_NWS_AS_ROS_BTF_300`
      : `NW18_HIND_Desktop/NW18_HIND_${tagOne}/NW18_HIND_${tagTwo}_${targetCode}/NW18_HIND_${tagThree}_${targetCode}_ROS_BTF_300`,
    PG_1x1_2: !isPhoto
      ? `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_PG_1x1_2`
      //: `NW18_HIND_Desktop/NW18_HIND_PHOTO/NW18_HIND_PHOTO_HP_${targetCode}/NW18_HIND_PHT_HP_${targetCode}_ROS_PG_1x1_2`,
      :`NW18_HIND_Desktop/NW18_HIND_PHOTO/NW18_HIND_PHOTO_${targetCode}/NW18_HIND_PHT_${targetCode}_ROS_PG_1x1_2`,
    LBAND_480X60: `NW18_HIND_Desktop/NW18_HIND_LOCAL18_NEWS/NW18_HIND_LOCAL18_NEWS_AS/NW18_HIND_LOCAS18_NWS_AS_ROS_LBAND_480x60`,
    LBAND_1x1: `NW18_HIND_Desktop/NW18_HIND_LOCAL18_NEWS/NW18_HIND_LOCAL18_NEWS_AS/NW18_HIND_LOCAS18_NWS_AS_ROS_LBAND_1x1`,
    PG_1x1_3: target === 'listing' ? `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AL/NW18_HIND_ROS_AL_PG_1x1_3` : !isPhoto ? `NW18_HIND_Desktop/NW18_HIND_ROS/NW18_HIND_ROS_AS/NW18_HIND_ROS_AS_PG_1x1_3` :
      `NW18_HIND_Desktop/NW18_HIND_PHOTO/NW18_HIND_PHOTO_AS/NW18_HIND_PHT_AS_ROS_PG_1x1_3`

  };

  if (opt.isCryptoTag) {
    a.ATF_728_id = `NW18_HIND_Desktop/NW18_HIND_CRYTOCURRENCY/NW18_HIND_CRYTOCURRENCY_AL/NW18_HIND_CRYCRY_BNK_AL_ROS_ATF_728`;
    a.header_ATF_728 = `NW18_HIND_Desktop/NW18_HIND_CRYTOCURRENCY/NW18_HIND_CRYTOCURRENCY_AL/NW18_HIND_CRYCRY_BNK_AL_ROS_ATF_728`;
    a.rhs_ATF_300 = `NW18_HIND_Desktop/NW18_HIND_CRYTOCURRENCY/NW18_HIND_CRYTOCURRENCY_AL/NW18_HIND_CRYCRY_BNK_AL_ROS_ATF_300`;
    a.ATF_300_id = `NW18_HIND_Desktop/NW18_HIND_CRYTOCURRENCY/NW18_HIND_CRYTOCURRENCY_AL/NW18_HIND_CRYCRY_BNK_AL_ROS_ATF_300`;
    a.BTF_300_id = `NW18_HIND_Desktop/NW18_HIND_CRYTOCURRENCY/NW18_HIND_CRYTOCURRENCY_AL/NW18_HIND_CRYCRY_BNK_AL_ROS_BTF_300`;
    a.rhs_BTF_300 = `NW18_HIND_Desktop/NW18_HIND_CRYTOCURRENCY/NW18_HIND_CRYTOCURRENCY_AL/NW18_HIND_CRYCRY_BNK_AL_ROS_BTF_300`;
  }

  if (opt.isWomenWorldCupPage) {
    a = {};
    a.ATF_728_id = `CRINXT_HIND_DESKTOP/CRINXT_HIND_EVENT/CRINXT_HIND_EVENT_AL/CRINXT_HIND_EVNT_AL_ROS_ATF_728`;
    a.header_ATF_728 = `CRINXT_HIND_DESKTOP/CRINXT_HIND_EVENT/CRINXT_HIND_EVENT_AL/CRINXT_HIND_EVNT_AL_ROS_ATF_728`;
    a.rhs_ATF_300 = `CRINXT_HIND_DESKTOP/CRINXT_HIND_EVENT/CRINXT_HIND_EVENT_AL/CRINXT_HIND_EVNT_AL_ROS_ATF_300`;
    a.ATF_300_id = `CRINXT_HIND_DESKTOP/CRINXT_HIND_EVENT/CRINXT_HIND_EVENT_AL/CRINXT_HIND_EVNT_AL_ROS_ATF_300`;
    a.BTF_300_id = `CRINXT_HIND_DESKTOP/CRINXT_HIND_EVENT/CRINXT_HIND_EVENT_AL/CRINXT_HIND_EVNT_AL_ROS_BTF_300`;
    a.rhs_BTF_300 = `CRINXT_HIND_DESKTOP/CRINXT_HIND_EVENT/CRINXT_HIND_EVENT_AL/CRINXT_HIND_EVNT_AL_ROS_BTF_300`;
    a.BTF_728 = `CRINXT_HIND_DESKTOP/CRINXT_HIND_EVENT/CRINXT_HIND_EVENT_AL/CRINXT_HIND_EVNT_AL_ROS_BTF_728`;
    a.Shosh_OOP_id = `CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_Shosh_OOP`;
    a.Skin_OOP_id = `CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_SKIN_OOP`;
    a.PG_1x1 = `CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_1x1`;
    a.PG_1x1_2 = `CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_1x1_2`;
    a.PG_Slider_1x1 = `CRINXT_HIND_DESKTOP/CRINXT_HIND_ROS/CRINXT_HIND_ROS_AL/CRINXT_HIND_ROS_AL_ROS_PG_SLIDER_1x1`;
  }
  return a;
};

export { adPairs, generateAdTags };
