import { adPairs } from "config/ads.config";

const generateMobileAdTags = (target = 'listing', category, isPhoto, opt = {}, isDistrict = false) => {
  const targetCode = target == 'listing' ? 'AL' : 'AS';
  if (!adPairs[category]) {
    return {
      header_ATF_320: isDistrict ? `NW18_HIND_PWA/NW18_HIND_LOCAL18_NEWS_PWA/NW18_HIND_LOCAL18_NEWS_PWA_AS/NW18_HIND_LOCAS18_NWS_AS_PWA_ROS_ATF_320` :
        `NW18_HIND_PWA/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_ROS_ATF_320`,
      FBN_320: isDistrict ? `NW18_HIND_PWA/NW18_HIND_LOCAL18_NEWS_PWA/NW18_HIND_LOCAL18_NEWS_PWA_AS/NW18_HIND_LOCAS18_NWS_AS_PWA_ROS_FBN_320` :
        `NW18_HIND_PWA/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_ROS_FBN_320`,
      ATF_300: isDistrict ? `NW18_HIND_PWA/NW18_HIND_LOCAL18_NEWS_PWA/NW18_HIND_LOCAL18_NEWS_PWA_AS/NW18_HIND_LOCAS18_NWS_AS_PWA_ROS_ATF_300` :
        `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_PWA_ROS_ATF_300`,
      NAT1: `NW18_HIND_PWA/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_ROS_BTF_300`,
      NAT2: `NW18_HIND_PWA/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_ROS_BTF_728`,
      NAT3: `NW18_HIND_PWA/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_ROS_BTF_728`,
      BTF_300: isDistrict ? `NW18_HIND_PWA/NW18_HIND_LOCAL18_NEWS_PWA/NW18_HIND_LOCAL18_NEWS_PWA_AS/NW18_HIND_LOCAS18_NWS_AS_PWA_ROS_BTF_300`
        : `NW18_HIND_PWA/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_ROS_BTF_300`,
      PG_1x1: !isPhoto ? `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_${targetCode}/NW18_HIND_${targetCode}_PWA_ROS_PG_1x1` :
        `NW18_HIND_PWA/NW18_HIND_PHOTO_PWA/NW18_HIND_PHOTO_PWA_${targetCode}/NW18_HIND_PHT_${targetCode}_PWA_ROS_PG_1x1`,
      PG_Slider_1x1: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_${targetCode}/NW18_HIND_${targetCode}_PWA_ROS_PG_SLIDER_1x1`,
      SHOSH_OOP: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_${targetCode}/NW18_HIND_${targetCode}_PWA_ROS_SHOSH_OOP`,
      SKIN_OOP: `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_${targetCode}/NW18_HIND_${targetCode}_PWA_ROS_SKIN_OOP`,
      PG_1x1_2: !isPhoto ? `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_${targetCode}/NW18_HIND_${targetCode}_PWA_ROS_PG_1x1_2` :
        `NW18_HIND_PWA/NW18_HIND_PWA/NW18_HIND_PHOTO_PWA/NW18_HIND_PHOTO_PWA_${targetCode}/NW18_HIND_PHT_${targetCode}_PWA_ROS_PG_1x1_2`,
      PG_1x1_3: !isPhoto ? `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_${targetCode}/NW18_HIND_${targetCode}_PWA_ROS_PG_1x1_3` :
        `NW18_HIND_PWA/NW18_HIND_PWA/NW18_HIND_PHOTO_PWA/NW18_HIND_PHOTO_PWA_${targetCode}/NW18_HIND_PHT_${targetCode}_PWA_ROS_PG_1x1_3`,
      LBAND_340x60: `NW18_HIND_PWA/NW18_HIND_LOCAL18_NEWS_PWA/NW18_HIND_LOCAL18_NEWS_PWA_AS/NW18_HIND_LOCAS18_NWS_AS_PWA_ROS_LBAND_340x60`,
      PG_1x1_4: target === 'listing' ? `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_PG_1x1_4` : !isPhoto ? 'NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_PG_1x1_4' : `NW18_HIND_PWA/NW18_HIND_PHOTO_PWA/NW18_HIND_PHOTO_PWA_AS/NW18_HIND_PHT_AS_PWA_ROS_PG_1x1_4`,
    };
  }
  let [tagOne, tagTwo, tagThree] = adPairs[category];
  tagThree = isPhoto ? 'PHT' : tagThree;
  tagOne = isPhoto ? 'PHOTO' : tagOne;
  tagTwo = isPhoto ? 'PHOTO' : tagTwo;
  let a = {
    header_ATF_320: isDistrict ? `NW18_HIND_PWA/NW18_HIND_LOCAL18_NEWS_PWA/NW18_HIND_LOCAL18_NEWS_PWA_AS/NW18_HIND_LOCAS18_NWS_AS_PWA_ROS_ATF_320` :
      `NW18_HIND_PWA/NW18_HIND_${tagOne}_PWA/NW18_HIND_${tagTwo}_PWA_${targetCode}/NW18_HIND_${tagThree}_${targetCode}_PWA_ROS_ATF_320`,
    FBN_320: isDistrict ? `NW18_HIND_PWA/NW18_HIND_LOCAL18_NEWS_PWA/NW18_HIND_LOCAL18_NEWS_PWA_AS/NW18_HIND_LOCAS18_NWS_AS_PWA_ROS_FBN_320` :
      `NW18_HIND_PWA/NW18_HIND_${tagOne}_PWA/NW18_HIND_${tagTwo}_PWA_${targetCode}/NW18_HIND_${tagThree}_${targetCode}_PWA_ROS_FBN_320`,
    ATF_300: isDistrict ? `NW18_HIND_PWA/NW18_HIND_LOCAL18_NEWS_PWA/NW18_HIND_LOCAL18_NEWS_PWA_AS/NW18_HIND_LOCAS18_NWS_AS_PWA_ROS_ATF_300` :
      `NW18_HIND_PWA/NW18_HIND_${tagOne}_PWA/NW18_HIND_${tagTwo}_PWA_${targetCode}/NW18_HIND_${tagThree}_${targetCode}_PWA_ROS_ATF_300`,
    NAT1: '',
    NAT2: '',
    NAT3: '',
    BTF_300: isDistrict ? `NW18_HIND_PWA/NW18_HIND_LOCAL18_NEWS_PWA/NW18_HIND_LOCAL18_NEWS_PWA_AS/NW18_HIND_LOCAS18_NWS_AS_PWA_ROS_BTF_300`
      : `NW18_HIND_PWA/NW18_HIND_${tagOne}_PWA/NW18_HIND_${tagTwo}_PWA_${targetCode}/NW18_HIND_${tagThree}_${targetCode}_PWA_ROS_BTF_300`,
    MTF_300: isDistrict ? `NW18_HIND_PWA/NW18_HIND_LOCAL18_NEWS_PWA/NW18_HIND_LOCAL18_NEWS_PWA_AS/NW18_HIND_LOCAS18_NWS_AS_PWA_ROS_MTF_300`
  : `NW18_HIND_PWA/NW18_HIND_${tagOne}_PWA/NW18_HIND_${tagTwo}_PWA_${targetCode}/NW18_HIND_${tagThree}_${targetCode}_PWA_ROS_MTF_300`,
    SHOSH_OOP: isPhoto
      ? `NW18_HIND_PWA/NW18_HIND_${tagOne}_PWA/NW18_HIND_${tagTwo}_PWA_${targetCode}/NW18_HIND_${tagThree}_${targetCode}_PWA_ROS_SHOSH_OOP`
      : `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_${targetCode}/NW18_HIND_${targetCode}_PWA_ROS_SHOSH_OOP`,
    SKIN_OOP: isPhoto
      ? `NW18_HIND_PWA/NW18_HIND_${tagOne}_PWA/NW18_HIND_${tagTwo}_PWA_${targetCode}/NW18_HIND_${tagThree}_${targetCode}_PWA_ROS_SKIN_OOP`
      : `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_${targetCode}/NW18_HIND_${targetCode}_PWA_ROS_SKIN_OOP`,
    PG_1x1: (isPhoto)
      ? `NW18_HIND_PWA/NW18_HIND_PHOTO_PWA/NW18_HIND_PHOTO_PWA_${targetCode}/NW18_HIND_PHT_${targetCode}_PWA_ROS_PG_1x1`
      : `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_${targetCode}/NW18_HIND_${targetCode}_PWA_ROS_PG_1x1`,
    PG_Slider_1x1: (isPhoto)
      ? `NW18_HIND_PWA/NW18_HIND_PHOTO_PWA/NW18_HIND_PHOTO_PWA_AL/NW18_HIND_PHT_AL_PWA_ROS_PG_SLIDER_1x1`
      : `NW18_HIND_PWA/NW18_HIND_ROS/NW18_HIND_ROS_${targetCode}/NW18_HIND_ROS_${targetCode}_PG_Slider_1x1`,
    PG_1x1_2: !isPhoto ? `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_${targetCode}/NW18_HIND_${targetCode}_PWA_ROS_PG_1x1_2` :
      `NW18_HIND_PWA/NW18_HIND_PHOTO_PWA/NW18_HIND_PHOTO_PWA_${targetCode}/NW18_HIND_PHT_${targetCode}_PWA_ROS_PG_1x1_2`,
    PG_1x1_3: !isPhoto ? `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_${targetCode}/NW18_HIND_${targetCode}_PWA_ROS_PG_1x1_3` :
      `NW18_HIND_PWA/NW18_HIND_PHOTO_PWA/NW18_HIND_PHOTO_PWA_${targetCode}/NW18_HIND_PHT_${targetCode}_PWA_ROS_PG_1x1_3`,
    LBAND_340x60: `NW18_HIND_PWA/NW18_HIND_LOCAL18_NEWS_PWA/NW18_HIND_LOCAL18_NEWS_PWA_AS/NW18_HIND_LOCAS18_NWS_AS_PWA_ROS_LBAND_340x60`,
    PG_1x1_4: target === 'listing' ? `NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AL/NW18_HIND_AL_PWA_ROS_PG_1x1_4` : !isPhoto ? 'NW18_HIND_PWA/NW18_HIND_ROS_PWA/NW18_HIND_ROS_PWA_AS/NW18_HIND_AS_PWA_ROS_PG_1x1_4' : `NW18_HIND_PWA/NW18_HIND_PHOTO_PWA/NW18_HIND_PHOTO_PWA_AS/NW18_HIND_PHT_AS_PWA_ROS_PG_1x1_4`,
  };

  if (opt.isCryptoTag) {
    a.header_ATF_320 = `NW18_HIND_PWA/NW18_HIND_CRYPTOCURRENCY_PWA/NW18_HIND_CRYPTOCURRENCY_PWA_AL/NW18_HIND_CRYCRY_BNK_AL_PWA_ROS_ATF_320`;
    a.FBN_320 = `NW18_HIND_PWA/NW18_HIND_CRYPTOCURRENCY_PWA/NW18_HIND_CRYPTOCURRENCY_PWA_AL/NW18_HIND_CRYCRY_BNK_AL_PWA_ROS_FBN_320`;
    a.ATF_300 = `NW18_HIND_PWA/NW18_HIND_CRYPTOCURRENCY_PWA/NW18_HIND_CRYPTOCURRENCY_PWA_AL/NW18_HIND_CRYCRY_BNK_AL_PWA_ROS_ATF_300`;
    a.BTF_300 = `NW18_HIND_PWA/NW18_HIND_CRYPTOCURRENCY_PWA/NW18_HIND_CRYPTOCURRENCY_PWA_AL/NW18_HIND_CRYCRY_BNK_AL_PWA_ROS_BTF_300`;
  }

  if (opt.isCryptoTag && opt.isAmp) {
    a.header_ATF_320 = `NW18_HIND_AMP/NW18_HIND_CRYPTOCURRENCY_AMP/NW18_HIND_CRYPTOCURRENCY_AMP_AL/NW18_HIND_CRYCRY_BNK_AL_AMP_ROS_ATF_320`;
    a.FBN_320 = `NW18_HIND_AMP/NW18_HIND_CRYPTOCURRENCY_AMP/NW18_HIND_CRYPTOCURRENCY_AMP_AL/NW18_HIND_CRYCRY_BNK_AL_AMP_ROS_FBN_320`;
    a.ATF_300 = `NW18_HIND_AMP/NW18_HIND_CRYPTOCURRENCY_AMP/NW18_HIND_CRYPTOCURRENCY_AMP_AL/NW18_HIND_CRYCRY_BNK_AL_AMP_ROS_ATF_300`;
    a.BTF_300 = `NW18_HIND_AMP/NW18_HIND_CRYPTOCURRENCY_AMP/NW18_HIND_CRYPTOCURRENCY_AMP_AL/NW18_HIND_CRYCRY_BNK_AL_AMP_ROS_BTF_300`;
  }

  if (opt.isWomenWorldCupPage) {
    a = {};
    a.header_ATF_320 = `CRINXT_HIND_PWA/CRINXT_HIND_EVENT_PWA/CRINXT_HIND_EVENT_PWA_AL/CRINXT_HIND_EVNT_AL_PWA_ROS_ATF_320`;
    a.FBN_320 = `CRINXT_HIND_PWA/CRINXT_HIND_EVENT_PWA/CRINXT_HIND_EVENT_PWA_AL/CRINXT_HIND_EVNT_AL_PWA_ROS_FBN_320`;
    a.ATF_300 = `CRINXT_HIND_PWA/CRINXT_HIND_EVENT_PWA/CRINXT_HIND_EVENT_PWA_AL/CRINXT_HIND_EVNT_AL_PWA_ROS_ATF_300`;
    a.BTF_300 = `CRINXT_HIND_PWA/CRINXT_HIND_EVENT_PWA/CRINXT_HIND_EVENT_PWA_AL/CRINXT_HIND_EVNT_AL_PWA_ROS_BTF_300`;
    a.SHOSH_OOP = `CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SHOSH_OOP`;
    a.SKIN_OOP = `CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_SKIN_OOP`;
    a.PG_1x1 = `CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_1x1`;
    a.PG_Slider_1x1 = `CRINXT_HIND_PWA/CRINXT_HIND_ROS_PWA/CRINXT_HIND_ROS_PWA_AL/CRINXT_HIND_AL_PWA_ROS_PG_Slider_1x1`;
  }

  return a;
};
// export default AD_TAGS
export { generateMobileAdTags };
