const localization = {
    "HOME": "होम",
    "NEWS18_HOME": "પ્રદેશ ૧૮ હોમ",
    "SELECT_STATE": "राज्य चुनें",
    "STATE": "राज्य",
    "CITIES": "શહેર",
    "MY_FAVORITES": "મારી પસંદગીનું",
    "ADD_TO_FAVORITES": "પસંદગીનું જોડો",
    "RECENTLY_VISITED": "હમણાં જ જોયેલું",
    "FIND_YOUR_LOCATION": "વાંચો તમારા શહેરના સમાચાર",
    "FIND_YOUR_LOCATION_BY_STATECITY": "આપનો જિલ્લો અને શહેર",
    "LANGUAGE": "भाषा",
    "HINDI": "હિન્દી",
    "ENGLISH": "અંગ્રેજી",
    "GUJARATI": "ગુજરાતીં",
    "CHANGE_LANGUAGE": "भाषा चुनें",
    "DEFUALT_LANGUAGE_SET": "Your default language is set to",
    "SET_HOMEPAGE_DEFAULT": "Set home page as default page",
    "SET_DEFAULT_LANGUAGE": "set your default language",
    "BROWSE_LOCATION_BY_STATECITY": "આપનો જિલ્લો અને શહેર",
    "LIVE_TV": "लाइव टीवी",
    "BLOGS": "BLOGS",
    "NEWS18_PICKS": "પ્રદેશ ૧૮ ખાસ",
    "SHOWS": "શો",
    "ABOUT_US": "हमारे बारे में",
    "CONTACT_US": "संपर्क करें",
    "PRIVACY_POLICY": "गोपनीयता नीति",
    "SITEMAP": "साइट मैप",
    "APPS": "એપ્સ",
    "NATION": "देश",
    "ADD_YOUR_COMMENTS": "આપનો પ્રતિભાવ આપો",
    "CLICK_TO_CLOSE": "બંધ કરવા માટે ક્લિક કરો",
    "CLICK_TO_OPEN": "ખોલવા માટે ક્લિક કરો",
    "EDITOR_PICKS": "સંપાદક ખાસ",
    "BREAKING": "BREAKING",
    "ALERT": "એલર્ટ",
    "FACEBOOK_LINK": "https://www.facebook.com/EtvNewsGujrati",
    "TWITTER_LINK": "https://twitter.com/News18Gujarati",
    "FOLLOW_ON_FACEBOOK": "Follow us on Facebook",
    "FOLLOW_ON_TWITTER": "Follow us on Twitter",
    "NEWS18_POLL": "પ્રદેશ ૧૮ પોલ",
    "POLL": "પોલ",
    "NATIONAL_INTERNATIONAL": "દેશવિદેશ",
    "MOVIES": "મૂવીઝ",
    "EYE_CATCHER": "અજબગજબ",
    "MORE": "વધુ...",
    "SCORECARD": "સ્કોરકાર્ડ",
    "FULL": "ફૂલ",
    "QUICK": "ઝડપી",
    "COMMENTARY": "કોમેન્ટરી",
    "RECENT": "નવિનતમ",
    "COMING": "આગામી",
    "READ_THIS": "આ પણ વાંચો",
    "LATEST": "લેટેસ્ટ",
    "VIDEOS": "વીડિયો",
    "ALL": "બધું",
    "JUMP_TO": "JUMP TO",
    "NEWS18_STATE": "PRADESH18 STATE",
    "NEWS": "न्यूज",
    "LIVETV": "લાઇવ ટીવી",
    "BROWSE_YOUR_LOCATION_WITHIN": "Browse All Locations Within",
    "LEFT_FBOX_NEWS": "લેટેસ્ટ ન્યૂઝ",
    "LEFT_FBOX_VIDEOS": "લેટેસ્ટ વીડિયો",
    "LEFT_FBOX_SHOWS": "શો",
    "LEFT_FBOX_INFOPAGE": "ઇન્ફો પેજ",
    "LEFT_FBOX_LIVETV": "લાઇવ ટીવી",
    "LEFT_FBOX_MAP": "નકશો",
    "LEFT_FBOX_PHOTO": "photo",
    "LEFT_FBOX_SCORECARD": "ક્રિકેટ સ્કોર",
    "LATEST_VIDEOS": "લેટેસ્ટ વીડિયો",
    "LATEST_NEWS": "લેટેસ્ટ ન્યૂઝ",
    "LATEST_SHOW": "લેટેસ્ટ શો",
    "FILTER_BY_STATE": "Filter by state",
    "FILTER_BY_CITY": "Filter by city",
    "MAP": "નકશો",
    "SCORE": "સ્કોર",
    "GUJARAT": "ગુજરાત",
    "BROWSE_LOCATIONS": "Browse Locations",
    "RECOMMENDED_GALLERY": "સુચવેલા ફોટા",
    "RECOMMENDED_VIDEO": "સુચવેલા વીડિયો",
    "RECOMMENDED_STORY": "સુચવેલા સમાચાર",
    "RELATED_STORY": "સંબંધિત સમાચાર",
    "PHOTO": "તસવીરો",
    "LATEST_PHOTO": "લેટેસ્ટ ફોટો",
    "SEARCH_NEWS_TOPICS": "તમારા ન્યૂઝ સર્ચ કરો",
    "SETTINGS": "સેટિંગ્સ",
    "CHOOSE_LANGUAGE": "भाषा चुनें",
    "CATEGOTRY": "કેટેગરી",
    "WEATHER": "હવામાન",
    "ENTER_CITY_STATE": "ઉમેરો શહેર,રાજ્ય",
    "LIVE_SCORE": "લાઇવ સ્કોર",
    "SEARCH_STATE_CITY": "શોધો રાજ્ય/શહેર",
    "LIVE_NOW": "લાઇવ નાઉ",
    "LAST": "આખરી",
    "FIRST": "પ્રથમ",
    "LOCAL": "સ્થાનિક",
    "TRENDING_NEWS": "ટ્રેન્ડીંગ ન્યૂઝ",
    "SELECT_BLOGGER": "બ્લોગર પસંદ કરો",
    "SELECT_SHOW": "પસંદ કરો શો",
    "FILTER_BY": "ફિલ્ટર બાય",
    "JUMP_TO_CITY": "શહેર બદલો",
    "JUMP_TO_CATEGORY": "કેટેગરી બદલો",
    "MARKET": "બજાર",
    "TOP_STORIES": "મુખ્ય સમાચાર",
    "SEARCH": "સર્ચ",
    "BYLINE": "બાય લાઇન",
    "GUJARAT_SECTION": "ગુજરાત વિભાગ",
    "SECTION": "सेक्शन",
    "GUJARAT_NEWS": "ગુજરાત ન્યૂઝ",
    "ASTRO": "રાશિ ભવિષ્ય",
    "BLOGGER": "બ્લોગર",
    "TOP_STORY": "મુખ્ય સમાચાર",
    "TOP": "ટોપ ",
    "NEXT": "Next",
    "VIEW_MORE": "જુઓ વધુ",
    "NEXT_PROGRAM": "હવે પછીના કાર્યક્રમ",
    "SUPERHIT_GALLERY": "સુુપરહિટ ગૅલેરી",
    "LATEST_NEWS": "ताजा खबरें",
    "POPULAR": "લોકપ્રિય",
    "WATCH_LIVE": "લાઈવ જુઓ",
    "MOST_VIEWED": "સૌથી વધુ પસંદીદા",
    "OTHER_NEWS": "અન્ય સમાચાર",
    "SUPERHIT_JOKES": "સુપરહિટ બૉક્સ",
    "READ_MORE": "વધુ વાંચો",
    "DOWNLOAD_APP": "ऐप डाउनलोड करें",
    "DOWNLOAD_APP_HOME": "News18 ऐप डाउनलोड करें",
    "FOLLOW_US_ON": "हमें फॉलो करें",
    "NOTIFICATION": "अधिसूचना"
};

export default localization;
