export const OlympicDatePlaceList = [
  // {
  //   id: 1,
  //   place: "Athens",
  //   country: "Greece",
  //   year: 1896,
  // },
  {
    id: 2,
    place: "पेरिस",
    country: "France",
    year: 1900,
  },
  // {
  //   id: 3,
  //   place: "St. Louis",
  //   country: "United States",
  //   year: 1904,
  // },
  // {
  //   id: 4,
  //   place: "London",
  //   country: "United Kingdom",
  //   year: 1908,
  // },
  // {
  //   id: 5,
  //   place: "Stockholm",
  //   country: "Sweden",
  //   year: 1912,
  // },
  // {
  //   id: 6,
  //   place: "Berlin",
  //   country: "Germany",
  //   year: 1916,
  // },
  // {
  //   id: 7,
  //   place: "Antwerp",
  //   country: "Belgium",
  //   year: 1920,
  // },
  // {
  //   id: 8,
  //   place: "Chamonix/Paris",
  //   country: "France",
  //   year: 1924,
  // },
  {
    id: 10,
    place: "सेंट मोरिट्ज़ / एम्स्टर्डम",
    country: "Switzerland/Netherlands",
    year: 1928,
  },
  {
    id: 11,
    place: "लेक प्लेसिड / लॉस एंजिल्स",
    country: "United States",
    year: 1932,
  },
  {
    id: 12,
    place: "गार्मिश-पार्टेनकिर्चेन / बर्लिन",
    country: "Germany",
    year: 1936,
  },
  // {
  //   id: 13,
  //   place: "Sapporo - Tokyo/Garmisch-Partenkirchen/Helsinki",
  //   country: "Japan/Germany/Finland",
  //   year: 1940,
  // },
  // {
  //   id: 14,
  //   place: "Cortina d'Ampezzo/London",
  //   country: "United Kingdom",
  //   year: 1944,
  // },
  {
    id: 15,
    place: "सेंट मोरिट्ज़ / लंदन",
    country: "Switzerland/United Kingdom",
    year: 1948,
  },
  {
    id: 16,
    place: "ओस्लो / हेलसिंकी",
    country: "Norway/Finland",
    year: 1952,
  },
  {
    id: 17,
    place: "कॉर्टिना डी'अम्पेज़ो / मेलबोर्न / स्टॉकहोम",
    country: "Italy/Australia/Sweden",
    year: 1956,
  },
  {
    id: 18,
    place: "स्क्वॉ वैली / रोम",
    country: "United States/Italy",
    year: 1960,
  },
  {
    id: 19,
    place: "इंसब्रुक",
    country: "Japan",
    year: 1964,
  },
  {
    id: 20,
    place: "ग्रेनोबल / मेक्सिको सिटी",
    country: "France/Mexico",
    year: 1968,
  },
  {
    id: 21,
    place: "साप्पोरो / मास्को",
    country: "Japan/FR Germany",
    year: 1972,
  },
  // {
  //   id: 22,
  //   place: "Innsbruck/Montreal",
  //   country: "Austria/Canada",
  //   year: 1976,
  // },
  {
    id: 23,
    place: "लेक प्लेसिड / मास्को",
    country: "United States/Soviet Union",
    year: 1980,
  },
  // {
  //   id: 24,
  //   place: "Sarajevo/Los Angeles",
  //   country: "Yugoslavia/United States",
  //   year: 1984,
  // },
  // {
  //   id: 25,
  //   place: "Calgary/Seoul",
  //   country: "Canada/South Korea",
  //   year: 1988,
  // },
  // {
  //   id: 26,
  //   place: "Albertville/Barcelona",
  //   country: "France/Spain",
  //   year: 1992,
  // },
  // {
  //   id: 27,
  //   place: "Lillehammer",
  //   country: "Norway",
  //   year: 1994,
  // },
  {
    id: 28,
    place: "अटलांटा",
    country: "United States",
    year: 1996,
  },

  // {
  //   id: 29,
  //   place: "Nagano",
  //   country: "Japan",
  //   year: 1998,
  // },
  {
    id: 31,
    place: "सिडनी",
    country: "Australia",
    year: 2000,
  },
  // {
  //   id: 32,
  //   place: "Salt Lake City",
  //   country: "United States",
  //   year: 2002,
  // },
  {
    id: 33,
    place: "एथेंस",
    country: "Greece",
    year: 2004,
  },
  // {
  //   id: 34,
  //   place: "Turin",
  //   country: "Italy",
  //   year: 2006,
  // },
  {
    id: 35,
    place: "बीजिंग",
    country: "China",
    year: 2008,
  },
  // {
  //   id: 36,
  //   place: "Vancouver",
  //   country: "Canada",
  //   year: 2010,
  // },
  {
    id: 37,
    place: "लंदन",
    country: "United Kingdom",
    year: 2012,
  },
  // {
  //   id: 38,
  //   place: "Sochi",
  //   country: "Russia",
  //   year: 2014,
  // },
  {
    id: 39,
    place: "रियो डी जनेरियो",
    country: "Brazil",
    year: 2016,
  },
  // {
  //   id: 40,
  //   place: "Pyeongchang",
  //   country: "South Korea",
  //   year: 2018,
  // },
  {
    id: 41,
    place: "टोक्यो",
    country: "Japan",
    year: 2020,
  },
  // {
  //   id: 42,
  //   place: "Beijing",
  //   country: "China",
  //   year: 2022,
  // },
  //   {
  //     id: 42,
  //     place: "Paris",
  //     country: "France",
  //     year: 2022,
  //   },
];
